lib/Baser/Plugin/Feed/View/Feed/smartphone/ajax.php
先ほどのチケットの内容を書いてる最中に不具合を見つけたのでPR出します。
確認よろしくお願いします。
=> fixed #7725 スマートフォンでAjaxを利用してフィードが読み込めない 問題を修正

lib/Baser/basics.php
=> fixed #7727 isConsole()でコンソールからの実行が正しく判定されない場合がある 問題を修正

lib/Baser/Config/routes.php
このルート使ってないですよね？ TestsControllerも見当たらないですし。
=> 利用されていないユニットテスト用のルートを削除

lib/Baser/View/Helper/BcBaserHelper.php
管理画面ログインURLがadminに決め打ちになっていたものを修正しました。
=> 管理画面ログインURLがadminに決め打ちになっていたものを修正

lib/Baser/Controller/UploadsController.php, lib/Baser/View/Helper/BcUploadHelper.php
=> fixes タイポ見つけたので修正

lib/Baser/View/Helper/BcBaserHelper.php
fixture修正の中に別件PR予定のものが入ってしまっていました。
元に戻します。
=> 別コミット予定のBcBaserHelperの拡張が混じってしまっていたので元に戻す

.travis.yml
僕のミスでVagrantBox仕様になっているので忘れないうちに修正します。
=> Travis-CIへのインストール時のホストをlocalhostに変更

lib/Baser/View/Installations/admin/step2.php
=> インストールSTEP２の誤字を修正した。

baser/views/elements/admin/toolbar.php
特に最近流行のTwitter Bootstrapにて「btn」が予約語っぽかったので。
=> ツールバーのクラス名を変更し、ユーザーテーマのクラス名と重複しにくくした。

lib/Baser/Config/setting.php, lib/Baser/Controller/BcAppController.php, lib/Baser/Controller/Component/BcAuthComponent.php, lib/Baser/Controller/Component/BcAuthConfigureComponent.php, lib/Baser/Controller/PermissionsController.php, lib/Baser/Controller/PluginsController.php, lib/Baser/Controller/UserGroupsController.php, lib/Baser/Lib/BcUtil.php, lib/Baser/Model/Permission.php, lib/Baser/View/Helper/BcBaserHelper.php, lib/Baser/View/UserGroups/admin/form.php
=> 複数認証プレフィックスに対応

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
=> testBaseUrl, testGetBaseUrl, testGetHereのテストプログラムを追加

lib/Baser/Controller/UsersController.php
モデルの指定を固定値から変数に変更しました。
http://forum.basercms.net/modules/newbb/viewtopic.php?viewmode=thread&topic_id=1174&forum=3&post_id=6906#6906
この変更で、先日質問した内容が解決できました。
問題は、Memberコントローラーを使った場合、パスワードを2重にハッシュ化していたため、ログインできない。でした。
=> Change the specified model, the variable from a fixed value.

.travis.yml, lib/Baser/Plugin/Blog/Test/Case/BlogAllTest.php, lib/Baser/Plugin/Feed/Test/Case/FeedAllModelTest.php, lib/Baser/Plugin/Feed/Test/Case/FeedAllTest.php, lib/Baser/Plugin/Mail/Test/Case/Controller/MailControllerTest.php, lib/Baser/Plugin/Mail/Test/Case/MailAllControllerTest.php, lib/Baser/Plugin/Mail/Test/Case/MailAllHelpersTest.php, lib/Baser/Plugin/Mail/Test/Case/MailAllModelTest.php, lib/Baser/Plugin/Mail/Test/Case/MailAllTest.php, lib/Baser/Plugin/Mail/Test/Case/Model/MailContentTest.php, lib/Baser/Plugin/Mail/Test/Case/Model/MailFieldTest.php, lib/Baser/Plugin/Mail/Test/Case/Model/MessageTest.php, lib/Baser/Test/Case/BcAllConfigTest.php, lib/Baser/Test/Case/BcAllConfigureTest.php, lib/Baser/Test/Case/BcAllFilterTest.php, lib/Baser/Test/Case/BcAllHelpersTest.php, lib/Baser/Test/Case/BcAllLibTest.php, lib/Baser/Test/Case/BcAllModelTest.php, lib/Baser/Test/Case/BcAllNetworkTest.php, lib/Baser/Test/Case/BcAllPluginTest.php, lib/Baser/Test/Case/BcAllTest.php, lib/Baser/Test/Case/BcBasicsTest.php
各コアプラグインのテストをBcAllPluginTestにまとめ、BcAllTestに追加しました
=> TODO #8037 コアプラグインのテストをTravisCIで実行できるようにする

lib/Baser/View/Helper/BcGooglemapsHelper.php
指摘に基づいて修正しました。手元の環境で動作は確認しました。
=> Google Maps の地図でSSL を使用した時にChrome で地図が表示されない件を修正

lib/Baser/Plugin/Blog/View/Elements/admin/blog_posts/index_row.php
=> fixes #8166 管理画面のブログ記事一覧で公開・非公開を変更すると公開状態の表示が変更されない。

appveyor.yml, lib/Baser/Configure/BcThemeConfigReader.php, lib/Baser/Lib/TestSuite/BaserTestCase.php, lib/Baser/Model/Page.php, lib/Baser/Test/Case/Configure/BcThemeConfigReaderTest.php, lib/Baser/Test/Case/Model/PageTest.php, lib/Baser/basics.php
プルリクエスト出し直します。
手元で何回かCIを回してみましたが、処理速度には割とばらつきがあるようです。
とはいえ長くても12分程度です。
先ほどのプルリクエストの時ほど極端に遅くなることもあるんでしょうかね。
焼け石に水レベルですが、キャッシュ設定を追加しました。
=> fixed #8177 Windows環境の自動テスト追加

lib/Baser/Config/Schema/contents.php, lib/Baser/Config/Schema/dblogs.php, lib/Baser/Config/Schema/editor_templates.php, lib/Baser/Config/Schema/favorites.php, lib/Baser/Config/Schema/menus.php, lib/Baser/Config/Schema/page_categories.php, lib/Baser/Config/Schema/pages.php, lib/Baser/Config/Schema/permissions.php, lib/Baser/Config/Schema/plugin_contents.php, lib/Baser/Config/Schema/plugins.php, lib/Baser/Config/Schema/site_configs.php, lib/Baser/Config/Schema/user_groups.php, lib/Baser/Config/Schema/users.php, lib/Baser/Config/Schema/widget_areas.php, lib/Baser/Plugin/Blog/Config/Schema/blog_categories.php, lib/Baser/Plugin/Blog/Config/Schema/blog_comments.php, lib/Baser/Plugin/Blog/Config/Schema/blog_configs.php, lib/Baser/Plugin/Blog/Config/Schema/blog_contents.php, lib/Baser/Plugin/Blog/Config/Schema/blog_posts.php, lib/Baser/Plugin/Blog/Config/Schema/blog_posts_blog_tags.php, lib/Baser/Plugin/Blog/Config/Schema/blog_tags.php, lib/Baser/Plugin/Feed/Config/Schema/feed_configs.php, lib/Baser/Plugin/Feed/Config/Schema/feed_details.php, lib/Baser/Plugin/Mail/Config/Schema/contact_messages.php, lib/Baser/Plugin/Mail/Config/Schema/mail_configs.php, lib/Baser/Plugin/Mail/Config/Schema/mail_contents.php, lib/Baser/Plugin/Mail/Config/Schema/mail_fields.php, lib/Baser/Plugin/Mail/Config/Schema/messages.php
=> fixed #1390 携帯での更新時、全角文字「～(から)」が「?」と文字化けする 修正

lib/Baser/Lib/TestSuite/Fixture/BaserTestFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogCategoryFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogCommentFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogConfigFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogContentFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogPostFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogPostsBlogTagFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/Default/BlogTagFixture.php, lib/Baser/Plugin/Feed/Test/Fixture/Default/FeedConfigFixture.php, lib/Baser/Plugin/Feed/Test/Fixture/Default/FeedDetailFixture.php, lib/Baser/Plugin/Mail/Test/Fixture/Default/ContactMessageFixture.php, lib/Baser/Plugin/Mail/Test/Fixture/Default/MailConfigFixture.php, lib/Baser/Plugin/Mail/Test/Fixture/Default/MailContentFixture.php, lib/Baser/Plugin/Mail/Test/Fixture/Default/MailFieldFixture.php, lib/Baser/Plugin/Mail/Test/Fixture/Default/MessageFixture.php
https://github.com/baserproject/basercms/pull/285
上記PRでプラグインのフィクスチャの分が抜けていたので追加です。
=> プラグインのフィクスチャを調整

app/Config/routes.php
=> fixed #8224 CakePHPのPagesコントローラーのデフォルトの挙動を無効にする

Vagrantfile.default
=> #8299 Vagrantのプロビジョニングが始まらない 修正

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/View/Helper/BcBaserHelper.php
テストが抜けていたり正しい仕様になっていなかった部分もあるので整理しました。
確認お願いします。
=> fixed #8304 $this->BcBaser->getDescription が siteConfig['description'] の値を反映しないようです　修正

lib/Baser/Controller/PluginsController.php, lib/Baser/Model/Plugin.php
PluginController::admin_install()とadmin_add()で
処理が重複したのでついでにPluginモデルに移しました。
確認お願いします。
=> fixed #8179 プラグインをZIPファイルでアップロードして有効化した場合よく使う項目に管理機能へのリンクが追加されない 修正

lib/Baser/View/Helper/BcFormHelper.php
=> fixes #8403 登録したアイキャッチ画像の削除ボタンが出ない問題の対応

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
確認お願いします。
* コード整形
* assertEqual() → assertEquals()
* 出力系テストをexpectOutputString()等専用のメソッドで書き換え
* データプロバイダ
=> BcBaserHelperTestのリファクタリング

lib/Baser/Controller/UsersController.php
=> ユーザ認証系の変更に伴う代理ログイン後ログアウトが出来ない問題の修正

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
オプションの説明が不明瞭だったので変更しました。
※ついでに不要なスペース削除しています。
=> BlogHelper::getCategory関連のオプション説明を変更

lib/Baser/Model/Page.php
=> fixes 固定ページの削除時、固定ページテンプレートが削除されない動作を改修

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/View/Helper/BcBaserHelper.php
adminのaliasを変更した際に正しく出ない状態が発生していました。
ご確認おねがいします！
=> 認証プリフィックスのaliasを変更した際にツールバーが正しく出ない問題の修正

lib/Baser/Plugin/Mail/Controller/MailController.php
=> ファイル送信タイプがSecurityCompornentにて弾かれていたため設定を追加

lib/Baser/Config/setting.php
=> baserマーケットのURL変更に伴う変更です。

lib/Baser/Controller/UploadsController.php
=> smartphone/mobilenにてアクセスした場合のupload controllerに対応

lib/Baser/Plugin/Mail/Model/MailContent.php
=> fixed #8874 メールフォームの複数送信先指定ができるように改修

lib/Baser/View/Elements/paginations/simple.php
=> /lib/Baser/View/Elements/paginations/simple.php の編集

lib/Baser/Config/theme/m-single/Elements/mail_form.php, lib/Baser/Plugin/Mail/Controller/MailController.php, lib/Baser/Plugin/Mail/View/Elements/mail_form.php
=> #9122 メールフォームでブラウザの戻るボタンが使えない件の対応（ヒストリーバック対応）

lib/Baser/Config/theme/skelton/Mail/smartphone/default/submit.php
フォーラムで指摘のあったtypoを修正しました。
* skeltonテーマのメールプラグインでタイポ有り  
http://forum.basercms.net/modules/newbb/viewtopic.php?viewmode=thread&topic_id=1952&forum=8
=> スマホ版メールフォーム送信完了ページのtypo修正

lib/Baser/Controller/BcAppController.php, lib/Baser/Controller/PermissionsController.php
=> adminprefixを変更した際にPermissionの新規登録と、チェックが正しく走っていない問題を修正

lib/Baser/Test/Case/View/Helper/BcGooglemapsHelperTest.php
=> BcGooglemapsHelperTest::testGetLocation()の修正

lib/Baser/Config/theme/nada-icons/LICENCE.txt, lib/Baser/View/Elements/admin/sidebar.php, lib/Baser/View/Elements/admin/themes/index_list.php
よろしくお願いします！
barket.jp -> market.basercms.net
magazine.barket.jp -> magazine.basercms.net
=> barket.jpドメイン変更に伴う修正

lib/Baser/Model/Page.php
=> Page::_getPageFilePath()をパブリックに変更

lib/Baser/Test/Case/BcAllComponentsTest.php, lib/Baser/Test/Case/BcAllTest.php
BcAllTest を BcAllComponentsTest を読み込むように変更
=> Component の testSuite を追加

lib/Baser/Controller/Component/BcManagerComponent.php, lib/Baser/Test/Case/Controller/Component/BcManagerComponentTest.php, lib/Baser/Test/Fixture/Default/BlogCommentFixture.php, lib/Baser/Test/Fixture/Default/FeedDetailFixture.php
- BcManagerComponentTestを追加
- BcManagerComponentのコメントとtypoを修正
- BlogCommentFixtureを追加
- FeedDetailFixtureを追加
DBのテーブルなどを削除するメソッドのテストは、復元する方法がまだわかっていないためスキップしています
=> BcManagerComponentのテストを追加

lib/Baser/Test/Case/Controller/Component/BcCaptchaComponentTest.php
- BcCaptchaComponentTestを作成
BcCaptchaComponent::render()は、hedderを生成するためスキップしています
=> BcCaptchaComponentのテストを追加

lib/Baser/Test/Case/Controller/Component/BcGmapsComponentTest.php
- BcGmapsComponentTestを作成
Googlemaps関連のテストですが、テストが成功したのでプルリクを送っておきます
=> BcGmapsComponentのテストを追加

lib/Baser/Test/Case/Controller/Component/BcReplacePrefixComponentTest.php
=> BcReplacePrefixComponentのテストを追加

lib/Baser/Test/Case/Controller/Component/BcAuthConfigureComponentTest.php, lib/Baser/Test/Fixture/Default/UserFixture.php
- BcAuthConfigureComponentTestの作成
- UserFixtureの管理ユーザーのpasswordを変更。ユーザーのパスワードがわからなかったため
=> BcAuthConfigureComponentのテストを追加

lib/Baser/Config/theme/skelton/Elements/googlemaps.php, lib/Baser/View/Elements/google_analytics.php, lib/Baser/View/Elements/google_maps.php
=> コメントのtypo修正

lib/Baser/Plugin/Mail/Config/Schema/mail_contents.php, lib/Baser/Plugin/Mail/Controller/MailController.php, lib/Baser/Plugin/Mail/Model/MailContent.php, lib/Baser/Plugin/Mail/View/MailContents/admin/form.php
=> メールフォームにオプションを追加

lib/Baser/Lib/BcUtil.php, lib/Baser/Test/Case/Lib/BcUtilTest.php
- BcUtilTest.phpを作成
- BcUtil.phpのリファクタリング
=> BcUtilのテストを追加

lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Mail/Model/MailContent.php
=> 検索インデックス作成時の処理でIDが設定されていない場合の対応 

lib/Baser/Plugin/Blog/View/Elements/blog_comments.php
=> エレメントファイルのtypo修正

lib/Baser/Controller/PagesController.php
SP用のテンプレをPCと別で作成した際に下層ベージの表示にてエラーがでていたので修正しました。
=> PagesControllerのcheckPublishメソッドの引数修正

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php, lib/Baser/Test/Case/View/Helper/BcUploadHelperTest.php, lib/Baser/View/Helper/BcFormHelper.php, lib/Baser/View/Helper/BcUploadHelper.php
アスタリスク追加しただけなんですが。http://api.basercms.net/ とかに反映されてなかったので
=> phpDoc 用のコメントの書き方になってなかったので修正

app/Config/core.php, lib/Baser/Model/Page.php, lib/Baser/Test/Case/Model/PageTest.php
=> fix #10680 Viewとデータのキャッシュ時間を分離

lib/Baser/Config/bootstrap.php, lib/Baser/Model/Page.php, lib/Baser/Test/Case/Config/BootstrapTest.php, lib/Baser/Test/Case/Model/PageTest.php
=> キャッシュのテストコード追加と調整

lib/Baser/View/Helper/BcBaserHelper.php
=> fix #11132 BcBaserHelper::isPageの判定をURLからRequest情報に変更

lib/Baser/View/WidgetAreas/admin/form.php
=> 管理画面でのウィジェット削除時の文言修正

lib/Baser/View/Pages/admin/form.php
システム管理グループのユーザーでログイン中時に表示されるようにしました。
=> 固定ページのcode欄に記述が有る場合は文言を表示して判別しやすくする

lib/Baser/Plugin/Blog/View/BlogContents/admin/form.php
=> ブログ設定画面の記述ミスを修正

lib/Baser/Config/theme/m-single/Elements/mail_form.php, lib/Baser/Plugin/Mail/Controller/MailController.php, lib/Baser/Plugin/Mail/Model/Message.php, lib/Baser/Plugin/Mail/View/Elements/mobile/mail_form.php
以下のスレッド（私はmozacoという名前で投稿しています）の不具合を含む、メールフォームまわりの不具合を修正しました。
* [メールフォーム「書き直す」で戻ったページに「送信する」などのボタンが表示されません。｜フォーラム｜baserCMSユーザーズ](http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=2098&forum=3)
ご検討よろしくお願いいたします。
=> メールフォームの不具合修正

lib/Baser/Controller/UsersController.php
=> fix #11762 cookieに保存するログイン情報の修正

lib/Baser/Plugin/Mail/Model/Message.php
=> fix #11773

lib/Baser/Plugin/Mail/Model/Message.php
=> Fix #11781 - メールフォームのvalidationメッセージ追加

lib/Baser/Model/Page.php, lib/Baser/Plugin/Blog/Model/BlogPost.php
=> Dev 3 request

lib/Baser/Config/update/3.0.9/updater.php
=> fixed #11925 3.0.9へのアップデータ実行時に Class 'MailAppModel' not found が発生する

lib/Baser/Plugin/Blog/Test/Case/BlogAllHelpersTest.php, lib/Baser/Plugin/Blog/Test/Case/BlogAllTest.php, lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
getPostDetail の第2引数を、optionsでまとめてますが、現状 cutしかないので他のmethodとの引数のバランスで問題ある場合は修正いたします。
=> fixed #12011 getPostDetail methodの作成とそれに伴うテストファイルの追加

lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
キレイにしてプルリクつくりなおしました。
御確認お願いします。
http://project.e-catchup.jp/issues/12014
の分の実装になります。
=> fixes #12014 blogName getBlogName のmethodをBlogHelperに追加

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/View/Helper/BcBaserHelper.php
=> siteName getSiteName の実装

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/View/Helper/BcBaserHelper.php
なんやかんやで、これが一番シンプルでわかりやすそうなんで、こちらにおちつきました
引数で、'ssl' って書かれても希望の動作になりますしね。'http'ってかかれるとやっかいですけど。。
=> fixes #12015 siteUrl getSiteUrl のhelperを実装

lib/Baser/Controller/ToolsController.php, lib/Baser/View/Elements/admin/helps/tools_log.php, lib/Baser/View/Elements/admin/submenus/site_configs.php, lib/Baser/View/Tools/admin/log.php
test書いて無いですが、必要でしょうか。。。
急ぎの機能ではないと思うので、3.1.xでも問題ないかと思います。
=>     fixes #12060 logのバックアップ及び、error_logの削除インターフェイスの作成

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/View/Helper/BcBaserHelper.php
自分で作っておいてなんなんですが、これほんと必要なんですかね。
一応、あまり表に出さない方が良い情報は、unsetしています。_Tokenとか
=> fixes #12058 BcBaser::getParams() Helperの実装

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/View/Helper/BlogBaserHelper.php
(ソート順にてランダムを指定可能に）
よろしくお願いします！
=> fix #12070 blogPosts拡張：記事のランダム取得

lib/Baser/Vendor/Imageresizer.php
=> fix #12071 画像のリサイズ時（サムネイル作成時など）の透過画像対応

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/View/Helper/BlogBaserHelper.php
=> fix #12069 blogPosts拡張：複数ブログから記事を拾ってこれるようにしたい

lib/Baser/Config/theme/bccolumn/css/top.css
=> TOPページのblogPostsでWORKS（実績）を4件以上表示する時にずれてしまう件を調整

lib/Baser/View/Tools/admin/log.php
=>      fixed #12204 エラーログ削除インターフェイスの文言修正

lib/Baser/Plugin/Blog/View/Elements/admin/submenus/blog_posts.php
=> #fixes 12265 ブログ管理画面の不要なコメントリンク非表示

lib/Baser/View/Installations/admin/step3.php
=> インストール [ステップ３]画面でデフォルトテーマ名がテンプレート内固定だったので設定値を表示

lib/Baser/View/Installations/admin/step3.php
=> warningが出てしまうパターンがあったので修正

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/View/Helper/BlogBaserHelper.php
=> #fixes 12300 blogPostsにてブログが非公開の時にもデータが表示されてしまう

lib/Baser/Controller/Component/BcAuthConfigureComponent.php
=> fixes #12415 管理画面ログイン時に「ログイン状態を保存する」を利用するし変更を行うとログインできなくなる問題の修正

lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/Test/Fixture/Model/BlogPostsBlogTagModelFixture.php
- BlogHelperTestクラスを作成
- BlogPostsBlogTagのFixtureを追加
=> BlogHelperのテストを追加しました

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fixes #12501 デバッグモード時、ブログコンテンツにアクセスするとUndefinedが発生する

lib/Baser/Controller/BcAppController.php, lib/Baser/Plugin/Mail/Controller/MailController.php
Return-Pathの設定にはちょっと調整が必要という情報を得ましたので、提案のpull request送ります。
- 参考URL: http://norm-nois.com/blog/archives/2865
よろしくお願いします。
=> fixes #12533 メール通知動作時にReturn－Pathを設定する

lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogBaserHelperTest.php, lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/Test/Fixture/Model/BlogCategoryModelFixture.php, lib/Baser/Plugin/Blog/Test/Fixture/View/Helper/BlogPostBlogBaserHelperFixture.php, lib/Baser/Test/Case/Controller/Component/BcGmapsComponentTest.php
- BlogBaserHelperTestクラスを追加
- BlogPostBlogBaserHelperFixtureを追加
- BlogCategoryModelFixtureの同じカテゴリ名があったのと関連ファイルを修正
=> BlogBaserHelperのテストを追加

lib/Baser/Plugin/Blog/View/Elements/admin/blog_posts/index_list.php
=> fixes #12968 管理画面の記事一覧で記事がない時に一覧の表示がずれる不具合を修正

lib/Baser/Controller/Component/BcGmapsComponent.php, lib/Baser/Test/Fixture/Default/SiteConfigFixture.php, lib/Baser/View/Helper/BcGooglemapsHelper.php, lib/Baser/View/SiteConfigs/admin/form.php
=> Fixes #12761 google maps api key 対応

lib/Baser/Plugin/Blog/View/BlogCategories/admin/form.php, lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php, lib/Baser/Plugin/Blog/View/BlogTags/admin/form.php, lib/Baser/Plugin/Blog/webroot/js/admin/blog_contents/edit.js, lib/Baser/Plugin/Blog/webroot/js/admin/blog_posts/form.js, lib/Baser/Plugin/Feed/View/FeedConfigs/admin/form.php, lib/Baser/Plugin/Feed/View/FeedDetails/admin/form.php, lib/Baser/Plugin/Mail/View/MailConfigs/admin/form.php, lib/Baser/Plugin/Mail/View/MailFields/admin/form.php, lib/Baser/Plugin/Mail/webroot/js/admin/mail_contents/edit.js, lib/Baser/Plugin/Mail/webroot/js/admin/mail_fields/form.js, lib/Baser/Plugin/Uploader/View/UploaderCategories/admin/form.php, lib/Baser/Plugin/Uploader/View/UploaderConfigs/admin/index.php, lib/Baser/Plugin/Uploader/View/UploaderFiles/admin/index.php, lib/Baser/View/Elements/admin/content_fields.php, lib/Baser/View/Elements/admin/sites/form.php, lib/Baser/View/Menus/admin/form.php, lib/Baser/View/Permissions/admin/form.php, lib/Baser/View/SearchIndices/admin/add.php, lib/Baser/View/SiteConfigs/admin/form.php, lib/Baser/View/ThemeFiles/admin/form.php, lib/Baser/View/ThemeFiles/admin/form_folder.php, lib/Baser/View/Themes/admin/form.php, lib/Baser/View/UserGroups/admin/form.php, lib/Baser/View/Users/admin/form.php, lib/Baser/View/Users/admin/login.php, lib/Baser/View/WidgetAreas/admin/form.php, lib/Baser/webroot/js/admin/pages/edit.js, lib/Baser/webroot/js/admin/site_configs/form.js
イベント駆動のJSではなく、HTML5のautofocus属性での実装に変更
=> ページ遷移時のオートフォーカスの実装の変更

lib/Baser/Plugin/Uploader/webroot/js/admin/uploader_files/uploader_list.js
ライブラリが読み込みできておらずエラーになっていたので削除。
検索をかけたところ他に利用していそうなところもなかったので、ライブラリ自体を削除したほうがいいかもしれない。
=> jquery.cornerの削除

lib/Baser/Lib/BcUtil.php
=> MAMP等、ポートが別の環境に対応

lib/Baser/View/Installations/admin/step3.php
他のアラートと同様に、jsでデータベース名にドットがあれば
アラートを出すようにせっていしました。
=> fixes #2653

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
=> Fixes #13614 ブログ概要の文字列をgetPostContentにてカットした時に文字数が合わない

lib/Baser/Plugin/Blog/View/Blog/rss/index.php, lib/Baser/Plugin/Blog/View/Blog/rss/mobile/index.php
=> ブログのRSS表示時にNotice,Warningが毎回エラーログに出力されていたので修正

lib/Baser/Plugin/Blog/View/Blog/rss/index.php, lib/Baser/Plugin/Blog/View/Blog/rss/mobile/index.php
=> Fixes #13620 ブログのRSSが動作していない

lib/Baser/Plugin/Blog/Controller/BlogPostsController.php, lib/Baser/Plugin/Blog/View/Elements/admin/submenus/blog_posts.php, lib/Baser/View/Elements/admin/contents/index_row_tree.php, lib/Baser/View/Elements/admin/crumbs.php
=>  fixes #12059  管理画面の表示でタグを削除するロジックを追加

lib/Baser/View/Elements/admin/contents/index_view_setting.php
=>  fixes #13669  siteが1つしか無い場合に、site_idをhiddenで保持する様に調整

lib/Baser/Plugin/Feed/Controller/FeedController.php
=>  fixes #13840 feed pluginのwanningを解消

lib/Baser/Controller/ThemesController.php, lib/Baser/View/Elements/admin/themes/index_list.php, lib/Baser/View/Elements/admin/themes/index_row.php
theme/[themename]/Pages の書き込み権限チェック削除
=> Fixes #13890 変更になった書き込み権限チェックの削除

lib/Baser/webroot/js/admin/contents/edit.js
http://project.e-catchup.jp/issues/14108
=> Fixes #14108 管理画面　コンテンツ管理　プレビューボタンのリンク先が404??

lib/Baser/Controller/Component/BcManagerComponent.php, lib/Baser/Controller/InstallationsController.php
=> fixes #14069 インストールstep4でメアドのバリデーションエラーで文字化け

lib/Baser/basics.php
こちらの件を解消すると、チケット #14111 も同時に解消されます。
よろしくお願いします！
=> Fixes #13941 Windows xamp環境でカテゴリURLの異常

lib/Baser/View/Installations/admin/step4.php
id名が変更されていたので、それにあわせてjsの指定を調整しました。
=> fixes #14146 jsの参照ID名を調整

lib/Baser/webroot/js/admin/libs/jquery.bcToken.js
=> Fixes #14048 Firefoxのみthemeの切り替えができない

lib/Baser/Config/theme/bccolumn/Elements/footer.php
=> Fixes #14083 テーマbcColumn：footer部分の表示がおかしい

lib/Baser/Model/BcAppModel.php, lib/Baser/Plugin/Blog/Model/BlogCategory.php, lib/Baser/Plugin/Blog/Model/BlogComment.php, lib/Baser/Plugin/Blog/Model/BlogConfig.php, lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Blog/Model/BlogPost.php, lib/Baser/Plugin/Blog/Model/BlogTag.php, lib/Baser/Plugin/Blog/Test/Case/Model/BlogPostTest.php
BcAppModelに checkDateRange のvalidation定義を追加しています。
下記ファイルのarrayをショート表記に変換しています。
lib/Baser/Model/BcAppModel.php
lib/Baser/Plugin/Blog/Model/BlogCategory.php
lib/Baser/Plugin/Blog/Model/BlogComment.php
lib/Baser/Plugin/Blog/Model/BlogConfig.php
lib/Baser/Plugin/Blog/Model/BlogContent.php
lib/Baser/Plugin/Blog/Model/BlogPost.php
lib/Baser/Plugin/Blog/Model/BlogTag.php
=> #Fixes 13934 ブログ記事公開期限範囲validation追加

lib/Baser/Config/setting.php, lib/Baser/View/Elements/admin/submenus/site_configs.php, lib/Baser/View/Elements/admin/submenus/tools.php
メニュー調整入れました。
http://project.e-catchup.jp/issues/14217
=> Modify #14217 管理側のシステム設定メニューとシステムナビのメニューを調整

lib/Baser/View/Helper/BcPageHelper.php
./Console/cake baser_test baser BcAll　が通るため、テストコードの書き直しは行っておりません。
よろしくお願いします。
=> fix #14795 BcPage->getCategoryName() 削除

lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php
=> ブログの保存前確認ボタンを押すと記事の保存ができない  fixes #14942

lib/Baser/Plugin/Blog/Config/setting.php, lib/Baser/View/Helper/BcContentsHelper.php, lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
http://project.e-catchup.jp/issues/14100
=> コンテンツツリー ブログダブルクリックの遷移先を記事一覧に

lib/Baser/Config/setting.php, lib/Baser/Controller/InstallationsController.php
install時のdbのversionチェックをいれました。
=> fixes #11131 postgresql,mysqlのversionチェックを導入

lib/Baser/Plugin/Blog/View/Elements/admin/blog_posts/index_list.php, lib/Baser/Plugin/Blog/View/Elements/admin/blog_posts/index_row.php
=> fixes #14947 管理画面のブログ記事一覧で、アイキャッチを使用するとカラムがずれて表示される 固定表示に変更

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fix #14986 ブログ一覧で別ブログの一覧を「blogPost」で取得しようとするとエラーが発生する件の対応[

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
=> fixes #15071 ブログ詳細の詳細画面の「前に戻る」「次に進む」のリンク先が正しくない場合がある。

lib/Baser/Controller/BcPluginAppController.php
=> 非推奨メッセージの文言間違いを修正

lib/Baser/Model/Plugin.php
=> fixes #15312 プラグインインストール時によく使う項目に追加された項目にアクセスできない

lib/Baser/Controller/InstallationsController.php
=> fixes #15241 dev-3ブランチのbaserCMSがインストールできない

lib/Baser/Plugin/Blog/Model/BlogContent.php
=> fixes #15420 ウィジェット内のブログ名が数字になっている

lib/Baser/View/Helper/BcAppHelper.php
=> Fix #15570 BcAppHelper::urlの判別を修正

lib/Baser/View/Helper/BcAppHelper.php
=> #15770のdev-3対応

lib/Baser/Config/theme/bc_sample/Elements/google_analytics.php
=> fix #15795 コアテーマ「bc sample」のgoogle analitycsタグが古い

lib/Baser/Plugin/Blog/Config/Schema/blog_posts.php
=> fixed #15072 ブログ記事一覧画面での「非公開」切替に失敗してエラー表示がでる

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
=> fix #15418 ブログ記事詳細で概要を利用していない設定でも表示される

lib/Baser/Controller/PagesController.php, lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/webroot/js/admin/blog_posts/form.js, lib/Baser/webroot/js/admin/contents/edit.js
=> fix #8170 固定ページ、ブログ詳細ページの草稿プレビューURL払い出し機能追加

lib/Baser/View/Sites/admin/edit.php, lib/Baser/webroot/js/admin/sites/edit.js
=> fix #16352 admin prefixを変更していた場合にサブサイトが削除出来ない問題を修正

lib/Baser/Plugin/Mail/Test/Case/View/Helper/MailHelperTest.php, lib/Baser/Plugin/Mail/View/Helper/MailHelper.php
=> MailHelperのテストを追加

lib/Baser/View/Elements/admin/toolbar.php, lib/Baser/webroot/css/admin/toolbar.css
=> fix #16318 #UserMenu ul ulのpd-rの影響でツールバーの表示が壊れる idをBcUserMenuに

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
=> 次の記事、前の記事が存在するか確認するヘルパ追加

lib/Baser/View/Elements/template_dump.php
=> fix #16586 _viewFilesLog判別の修正

lib/Baser/Model/ContentFolder.php, lib/Baser/webroot/js/admin/site_configs/form.js
使われなくなった機能が残っているかと思います。
確認よろしくお願いします。
=> fixex #16597 #16593 システム保存処理修正

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fix #16832 ブログのプレビューが正しく表示されない問題の修正

lib/Baser/View/Elements/admin/search_indices/index_list.php, lib/Baser/View/Elements/admin/search_indices/index_row.php
以前に同様の改修が入っていましたが、初回表示時（ajax処理実行前）のみ、
動作していなかったので修正しました。
よろしくお願いします！
=> fix #15237 検索インデックス管理が動作しない問題を改善 dev-4

lib/Baser/View/Contents/admin/ajax_index.php, lib/Baser/View/Elements/admin/contents/index_list.php, lib/Baser/View/Elements/admin/contents/index_row.php
以前に同様の改修が入っていましたが、初回表示時（ajax処理実行前）のみ、
動作していなかったので修正しました。（dev-3版）
よろしくお願いします！
=> fix #15237 検索インデックス管理が動作しない問題を改善 dev-3

lib/Baser/Config/Schema/pages.php, lib/Baser/Plugin/Blog/Config/Schema/blog_posts.php
=> fix #17028 MySQLの場合に本稿／草稿でカラムのデータ型が異る

lib/Baser/View/Elements/admin/content_fields.php, lib/Baser/webroot/css/admin/contents.css
=> fix #17082 上位フォルダ非表示の際の注意文を目立つように変更

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/View/Elements/widgets/blog_recent_entries.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
- https://github.com/baserproject/basercms/commit/e1220b4094321a4675d73686a17fd2cc4c40f00a
よろしくお願いしますっ！
=> add イベント Blog.Blog.beforeGetPostLink を追加（4系改修から3系に調整して適用）

lib/Baser/Model/ContentFolder.php
=> fix #17230 コンテンツ管理でフォルダのURLを変更するとフォルダ配下の固定ページのコンテンツが表示されなくなる

lib/Baser/Plugin/Mail/View/Elements/mail_form.php, lib/Baser/View/Helper/BcBaserHelper.php
=> fix #17611 [サブドメイン]フォーム"入力→確認"の遷移でエラー

lib/Baser/webroot/css/admin/colorbox/colorbox-1.6.1.css
Colorboxのデザインがデフォルトの状態でしたので、調整してみました。
よろしければ、ご検討ください。
よろしくお願いいたします。
=> colorboxデザイン変更

lib/Baser/Test/Case/View/Helper/BcAdminHelperTest.php, lib/Baser/Test/Case/View/Helper/BcMobileHelperTest.php, lib/Baser/Test/Case/View/Helper/BcPageHelperTest.php, lib/Baser/Test/Case/View/Helper/BcSmartphoneHelperTest.php, lib/Baser/Test/Case/View/Helper/BcWidgetAreaHelperTest.php, lib/Baser/View/Helper/BcPageHelper.php, lib/Baser/View/Helper/BcWidgetAreaHelper.php
=> BcSmartphoneHelper修正

composer.json, lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/View/Helper/BcCsvHelperTest.php, lib/Baser/Test/Case/View/Helper/BcFormHelperTest.php, lib/Baser/Test/Case/View/Helper/BcFreezeHelperTest.php, lib/Baser/Test/Case/View/Helper/BcGooglemapsHelperTest.php, lib/Baser/Test/Case/View/Helper/BcPageHelperTest.php, lib/Baser/Test/Case/View/Helper/BcWidgetAreaHelperTest.php, lib/Baser/View/Helper/BcPageHelper.php
View/
BcPageHelper/treeList削除
BcCsvHelper/testDownload追加
property追加
BcPageHelper/testContentと
BcWidgetHelper/testShowはファイル操作ができないため詰まってます。
他、実装できてないのでスキップのままですが、テストコードを追加
=> View/BcPageHelper/treeList削除 BcCsvHelper/testDownload追加

lib/Baser/Plugin/Blog/Controller/BlogCategoriesController.php, lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php, lib/Baser/Plugin/Blog/webroot/js/admin/blog_posts/form.js
http://project.e-catchup.jp/issues/14158
実装中にこちらのバグに引っかかりました。
いっそURLに日本語カテゴリ名を許可するほうが簡単ではないかと思います。
http://project.e-catchup.jp/issues/15424
=> fix #14158 [BLOG]新規記事登録（記事編集）で【新しいカテゴリを追加】した際に URL を指定できない

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fix #17775 4.0.5でブログのページネーションがエラーになる問題の修正

lib/Baser/Controller/PagesController.php
POSTパラメータに含まれるscriptタグを直にHTML出力するとXSS判定を受ける。
最近のブラウザは賢いので。
セッションに退避させる小細工で回避。
=> fix #17729 固定ページのコード欄にjavascriptを入力するとプレビューが動作しない

lib/Baser/View/Helper/BcBaserHelper.php, lib/Baser/webroot/css/admin/toolbar.css
=> fix #5813 スマートフォンページでツールバー（上部黒帯）を出力

lib/Baser/Controller/Component/BcManagerComponent.php, lib/Baser/Controller/InstallationsController.php
=> fix #14145 インストール時に DB が初期化されることを強くアピール

lib/Baser/Plugin/Blog/webroot/js/admin/blog_posts/form.js
=> [WIP] fix #17794 IE11にて管理画面のURLコピーボタンを押すと、画面最下部へスクロールしてしまう

lib/Baser/Test/Case/Model/PageTest.php
array()を[]に変更しました。
書き方が混ざって嫌なので、何回かに分けて全部変えようと思います。
=> PageTestのarrayを[]に変更

lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/Model/PageTest.php, lib/Baser/Test/Case/View/Helper/BcAdminHelperTest.php, lib/Baser/Test/Case/View/Helper/BcArrayHelperTest.php, lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
=> BcAppTestのarray()を[]に変更

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fix #17775 ページネーションが正しく動作しない問題の再修正

lib/Baser/Plugin/Blog/webroot/js/admin/blog_posts/form.js
=> fix #17890 ブログ記事のプレビューを復数回行うとURLの末尾に?preview=defaultが連続して付与されてしまう を解消

lib/Baser/webroot/js/admin/users/edit.js
=> fix #17892 よく使う項目の初期値設定後のメッセージの種類が警告メッセージになっている を解消

lib/Baser/Plugin/Blog/Controller/BlogPostsController.php, lib/Baser/Plugin/Blog/Model/BlogPost.php
=> fix #17891 管理画面 ブログ記事一覧の表示件数の初期状態のURLがおかしい の解消

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
=> fix #17881 フロント側での表示時にブログアイキャッチサイズが指定できない。の件の解消

lib/Baser/Model/Page.php, lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Mail/Model/MailContent.php
=> fix #18043 コンテンツ管理の一覧で右クリック→コピーを行うと、アイキャッチ画像がコピーされない

lib/Baser/Model/Page.php, lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Blog/Model/BlogPost.php, lib/Baser/Plugin/Mail/Model/MailContent.php, lib/Baser/Plugin/Mail/Model/MailField.php, lib/Baser/Plugin/Uploader/Model/UploaderCategory.php
beforeCopyのパラメータを揃えました。こちらでよろしくお願いします！
=> fix #18044 ModelのcopyメソッドにbeforeCopy, afterCopy のようなイベントを追加したい

lib/Baser/Config/theme/bccolumn/Blog/topics/posts.php, lib/Baser/Config/theme/bccolumn/Blog/works/posts.php
・/lib/Baser/Config/theme/bccolumn/Blog/works/posts.php
・/lib/Baser/Config/theme/bccolumn/Blog/topics/posts.php
$this->request->params['Content']['name'] を　$postのコンテントネームに変更
=> fix dev-18268 標準テーマbccolumnのトップページの画像リンクの不具合

lib/Baser/Plugin/Mail/Controller/MailContentsController.php
=> fix #17896 お問い合わせフォームのURL、タイトル欄の必須チェックが効いていない

lib/Baser/basics.php
=> fix #18272 SSLの判別をapacheの環境変数からCakeRequestへ切替

lib/Baser/Controller/UsersController.php
こちらバグというより提案になるかと思います。
管理画面ログイン中にログイン画面にアクセスした場合管理画面TOPにリダイレクトするように修正を加えております。
宜しくお願い致します。
=> change #18276 ログイン中にログイン画面にアクセスできる(ログインしている場合トップへリダイレクト)

lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
=> fix #18371 ブログ記事一覧で記事件数が多いときにエラーになる問題を改善

.travis.yml, secure_test/vaddy.sh
=> vaddy ループ修正

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
こちら修正致しました。
http://project.e-catchup.jp/issues/18367
お手数おかけ致しますが宜しくお願い致します。
=> fix #18367 Blogヘルパのカテゴリーアーカイブへのリンク生成処理修正

lib/Baser/Controller/BcAppController.php
=> Topic 18420

lib/Baser/View/Installations/admin/step5.php
=> fix #18621 インストール完了画面で表示している「管理者ダッシュボードに移動する」のリンクがエラーとなっている

lib/Baser/Controller/FavoritesController.php
FavoriteControllerのaddとeditの２箇所のname変数をsanitizeしました。
=> FavoriteControllerにサニタイズ処理を追加

lib/Baser/Controller/EditorTemplatesController.php
- afterAdd で渡している変数が未定義のため
取込検討、よろしくお願いします。
=> fix #18809 エディタテンプレート追加時のafterAddイベントにおいて、フック処理時にデータが取得できない

lib/Baser/Model/Tool.php
=> fix #18807 スキーマ書き出し時の読み込みリスト修正

lib/Baser/Plugin/Mail/Model/MailContent.php
=> fix #18890 メールフォームで100フィールドまでしか表示されない問題を改善

lib/Baser/Plugin/Mail/View/MailMessages/admin/view.php
[modify] 受信メール詳細で隠し(hidden)フィールドを表示するよう修正
http://project.e-catchup.jp/issues/18919
こちらユーザーからの要望となります。
宜しくお願い致します。
=> #18919 受信メール詳細に隠しフィールドを表示したい

lib/Baser/Plugin/Mail/View/Helper/MailHelper.php
存在しないキーを参照しようとして Undefined が発生するため。
取込検討お願いします。
=> fix #18918 デバッグモードでメールフォームを表示すると、文字化け起こす

lib/Baser/Test/Case/BcAllAuthTest.php, lib/Baser/Test/Case/BcAllTest.php, lib/Baser/Test/Case/BcAllViewTest.php, lib/Baser/Test/Case/Controller/Component/Auth/BcNoPasswordHaserTest.php, lib/Baser/Test/Case/Controller/Component/BcAuthComponentTest.php, lib/Baser/Test/Case/Controller/Component/BcContentsComponent.php, lib/Baser/Test/Case/Controller/Component/BcEmailConponentTest.php, lib/Baser/Test/Case/Controller/Component/BcGmapsComponentTest.php, lib/Baser/Test/Case/Controller/Component/BcManagerComponentTest.php, lib/Baser/Test/Case/Controller/Component/BcReplacePrefixComponentTest.php, lib/Baser/Test/Case/View/BcAppViewTest.php, lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php, lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/Test/Case/View/Helper/BcCkeditorHelperTest.php, lib/Baser/Test/Case/View/Helper/BcContentsHelperTest.php, lib/Baser/Test/Case/View/Helper/BcFormHelperTest.php, lib/Baser/Test/Case/View/Helper/BcFormTableHelperTest.php, lib/Baser/Test/Case/View/Helper/BcFreezeHelperTest.php, lib/Baser/Test/Case/View/Helper/BcHtmlHelperTest.php, lib/Baser/Test/Case/View/Helper/BcLayoutHelperTest.php, lib/Baser/Test/Case/View/Helper/BcListTableHelper.php, lib/Baser/Test/Case/View/Helper/BcMobileHelperTest.php, lib/Baser/Test/Case/View/Helper/BcPageHelperTest.php, lib/Baser/Test/Case/View/Helper/BcSearchBoxHelperTest.php, lib/Baser/Test/Case/View/Helper/BcSmartphoneHelperTest.php, lib/Baser/Test/Case/View/Helper/BcTextHelperTest.php, lib/Baser/Test/Case/View/Helper/BcUploadHelperTest.php
Helper終わりです。Test.phpファイルをいくつか追加しています。
BcListTableHelper.php、BcSearchBoxHelper.phpなど
=> Helperに未実装テストメソッド追加2

lib/Baser/Test/Case/BcBasicsTest.php
basics.phpに未実装のテストメソッドを追加しました。
=> basicsに未実装テストメソッド追加

lib/Baser/Plugin/Uploader/Controller/UploaderFilesController.php
=> fix #19158 Uploaderの公開期間チェック時にファイルを読み込むパスでUndefinedが発生している

lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/Model/CakeSchemaTest.php, lib/Baser/Test/Case/Model/ContentFolderTest.php, lib/Baser/Test/Case/Model/ContentTest.php, lib/Baser/Test/Case/Model/FavoriteTest.php, lib/Baser/Test/Case/Model/PageTest.php, lib/Baser/Test/Case/Model/PermissionTest.php, lib/Baser/Test/Case/Model/SiteConfigTest.php, lib/Baser/Test/Case/Model/SiteTest.php, lib/Baser/Test/Case/Model/ThemeFileTest.php, lib/Baser/Test/Case/Model/ThemeFolderTest.php, lib/Baser/Test/Case/Model/ThemeTest.php, lib/Baser/Test/Case/Model/UserTest.php
Modelディレクトリの各クラスに未実装テストメソッドを追加しました。
=> Modelディレクトリの各クラスに未実装テストメソッド追加

lib/Baser/Test/Case/Lib/BcAbstractDetectorTest.php, lib/Baser/Test/Case/Lib/BcAgentTest.php, lib/Baser/Test/Case/Lib/BcLangTest.php, lib/Baser/Test/Case/Lib/BcSiteTest.php, lib/Baser/Test/Case/Lib/BcUtilTest.php, lib/Baser/Test/Case/Lib/BcZipTest.php, lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/Model/Behavior/BcCacheBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/BcContentsBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/BcSearchIndexManagerBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/BcUploadBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/SoftDeleteBehaviorTest.php, lib/Baser/Test/Case/Model/CakeSchemaTest.php, lib/Baser/Test/Case/Model/ContentFolderTest.php, lib/Baser/Test/Case/Model/ContentTest.php, lib/Baser/Test/Case/Model/FavoriteTest.php, lib/Baser/Test/Case/Model/PageTest.php, lib/Baser/Test/Case/Model/PermissionTest.php, lib/Baser/Test/Case/Model/SiteConfigTest.php, lib/Baser/Test/Case/Model/SiteTest.php, lib/Baser/Test/Case/Model/ThemeFileTest.php, lib/Baser/Test/Case/Model/ThemeFolderTest.php, lib/Baser/Test/Case/Model/ThemeTest.php, lib/Baser/Test/Case/Model/UserTest.php
Libディレクトリの各クラスに未実装テストメソッドを追加しました。
=> Libディレクトリの各クラスに未実装テストメソッド追加

lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/Model/Behavior/BcCacheBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/BcContentsBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/BcSearchIndexManagerBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/BcUploadBehaviorTest.php, lib/Baser/Test/Case/Model/Behavior/SoftDeleteBehaviorTest.php, lib/Baser/Test/Case/Model/CakeSchemaTest.php, lib/Baser/Test/Case/Model/ContentFolderTest.php, lib/Baser/Test/Case/Model/ContentTest.php, lib/Baser/Test/Case/Model/FavoriteTest.php, lib/Baser/Test/Case/Model/PageTest.php, lib/Baser/Test/Case/Model/PermissionTest.php, lib/Baser/Test/Case/Model/SiteConfigTest.php, lib/Baser/Test/Case/Model/SiteTest.php, lib/Baser/Test/Case/Model/ThemeFileTest.php, lib/Baser/Test/Case/Model/ThemeFolderTest.php, lib/Baser/Test/Case/Model/ThemeTest.php, lib/Baser/Test/Case/Model/UserTest.php
Behaviorディレクトリの各クラスに未実装テストメソッドを追加しました。
=> Behaviorディレクトリの各クラスに未実装テストメソッド追加

lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php, lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
BcBaserHelper/testSetPageEditLink追加です。
=> testSetPageEditLink追加

lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php, lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php, lib/Baser/View/Helper/BcBaserHelper.php
=> BcBaserHelperのArrayを[]に変更

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
BcBaserHelper->testContentsName()追加しました。
=> testContentsName()追加

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
テストtestGetRoot()の追加とラッパーtestRoot()のコメントアウトをしました。
=> testGetRoot()追加、testRoot()削除

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
BcBaserHelper:testGetCurrentContent()追加しました。
=> testGetCurrentContent()追加

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
BcBaserHelper:testGetContentsMenu()追加 
BcBaserHelper:testContentsMenu()追加 >> テスト不要のためコメントアウト
=> getContentsMenu()追加

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
BcBaserHelper:getContentModifiedDate()追加しました。
=> getContentModifiedDate()追加

lib/Baser/Test/Case/BcAllControllerTest.php, lib/Baser/Test/Case/BcAllTest.php, lib/Baser/Test/Case/Controller/ContentFoldersControllerTest.php, lib/Baser/Test/Case/Controller/ContentLinksControllerTest.php, lib/Baser/Test/Case/Controller/ContentsControllerTest.php, lib/Baser/Test/Case/Controller/DashboardControllerTest.php, lib/Baser/Test/Case/Controller/DblogsControllerTest.php, lib/Baser/Test/Case/Controller/EditorTemplatesControllerTest.php, lib/Baser/Test/Case/Controller/FavoritesControllerTest.php, lib/Baser/Test/Case/Controller/InstallationsControllerTest.php, lib/Baser/Test/Case/Controller/MaintenanceControllerTest.php, lib/Baser/Test/Case/Controller/MembersControllerTest.php, lib/Baser/Test/Case/Controller/MobileControllerTest.php, lib/Baser/Test/Case/Controller/PagesControllerTest.php, lib/Baser/Test/Case/Controller/PermissionsControllerTest.php, lib/Baser/Test/Case/Controller/PluginsControllerTest.php, lib/Baser/Test/Case/Controller/SearchIndicesControllerTest.php, lib/Baser/Test/Case/Controller/SiteConfigsControllerTest.php, lib/Baser/Test/Case/Controller/SitesControllerTest.php, lib/Baser/Test/Case/Controller/ThemeConfigsControllerTest.php, lib/Baser/Test/Case/Controller/ThemeFilesControllerTest.php, lib/Baser/Test/Case/Controller/ThemesControllerTest.php, lib/Baser/Test/Case/Controller/ToolsControllerTest.php, lib/Baser/Test/Case/Controller/UpdatersControllerTest.php, lib/Baser/Test/Case/Controller/UploadsControllerTest.php, lib/Baser/Test/Case/Controller/UserGroupsControllerTest.php, lib/Baser/Test/Case/Controller/UsersControllerTest.php, lib/Baser/Test/Case/Controller/WidgetAreasControllerTest.php
Controllerディレクトリの各クラスに未実装テストメソッドを追加しました。
=> Controllerディレクトリの各クラスに未実装テストメソッド追加

lib/Baser/Test/Case/BcAllEventTest.php, lib/Baser/Test/Case/BcAllTest.php, lib/Baser/Test/Case/Event/BcContentsEventListenerTest.php, lib/Baser/Test/Case/Event/BcControllerEventDispatcherTest.php, lib/Baser/Test/Case/Event/BcControllerEventListenerTest.php, lib/Baser/Test/Case/Event/BcEventDispatcherTest.php, lib/Baser/Test/Case/Event/BcEventListenerTest.php, lib/Baser/Test/Case/Event/BcModelEventDispatcherTest.php, lib/Baser/Test/Case/Event/BcShortCodeEventListenerTest.php, lib/Baser/Test/Case/Event/BcViewEventDispatcherTest.php, lib/Baser/Test/Case/Event/CakeEventManagerTest.php, lib/Baser/Test/Case/Event/PagesControllerEventListenerTest.php
Eventディレクトリの各クラスに未実装テストメソッドを追加しました。
=> Eventディレクトリの各クラスに未実装テストメソッド追加

lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
・BcBaserHelper/testGetGoogleMaps追加
・#770の際に追加されていたテストの際に発生した不要残留ファイルの削除
=> testGetGoogleMaps追加

lib/Baser/Test/Case/BcAllRoutingTest.php, lib/Baser/Test/Case/BcAllTest.php
Routingディレクトリのテストシート作成用記述が抜けていたため追加しました。
=> Routingディレクトリのテストシート作成用記述が抜けていたため追加

lib/Baser/Test/Case/View/Helper/BcFreezeHelperTest.php, lib/Baser/Test/Case/View/Helper/BcHtmlHelperTest.php, lib/Baser/View/Helper/BcFreezeHelper.php
BcFreezeHelper:Freeze()追加
BcHtmlHelper:testGetStripCrumbs()追加
=> testFreeze() / testGetStripCrumbs()追加

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fix #19371 ブログ記事のプレビュー時にコンテンツが表示されない場合がある問題を改善

lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php
=> testAfterLayout修正

lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php
=> testSave追加

lib/Baser/View/Elements/admin/footer.php
管理画面 フッターの各種リンクの更新を行っています。よろしくお願いします。
- SSL化したURLのリンク調整
- URLが変更になったページのリンク調整
=> 管理画面 フッターのリンク調整

lib/Baser/Test/Case/Model/BcAppTest.php, lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php, lib/Baser/Test/Case/View/Helper/BcPageHelperTest.php
BcPageHelperTest/testGetPageList追加しました。
NextLinkとPrevLinkがラッパーだったため、コメントアウト
=> testGetPageList追加

lib/Baser/Controller/SearchIndicesController.php
=> fix #19480 サイト内検索でカテゴリ選択時に正しく検索できていない問題を修正

lib/Baser/Plugin/Blog/Controller/BlogController.php
=> fix #19530 複数ブログのフィードをひとつのRSSで出力されるブログ記事の並び順がおかしい問題を修正

lib/Baser/Plugin/Blog/View/Blog/rss/index.php, lib/Baser/Plugin/Blog/View/Blog/rss/mobile/index.php
こちらでいかがでしょうか。
あと、mobileだけ別でテンプレがあったのであわせて変更しました。
よろしくお願いします！
=> fix #19531 複数ブログのフィードをひとつのRSSで出力されるブログ記事のURLが正しくない問題の修正

lib/Baser/Test/Case/Model/ContentTest.php
Model/ContentTest testCopy追加しました。
=> Model/ContentTest testCopy追加

lib/Baser/Controller/BcAppController.php
取込検討、よろしくお願いします。
http://project.e-catchup.jp/issues/19591
=> fix #19591 サブサイトの404エラーページが、メインサイトのエラーページになる

.travis.yml, lib/Baser/Controller/Component/BcGmapsComponent.php, lib/Baser/Model/Content.php, lib/Baser/View/Helper/BcBaserHelper.php, lib/Baser/View/Helper/BcContentsHelper.php, lib/Baser/View/Helper/BcGooglemapsHelper.php, lib/Baser/basics.php, travis.php.ini
=> travis-ciのテストをtrustyで通す

lib/Baser/Controller/Component/BcGmapsComponent.php, lib/Baser/Lib/BcGmaps.php, lib/Baser/Test/Case/Controller/Component/BcGmapsComponentTest.php, lib/Baser/View/Helper/BcGooglemapsHelper.php
BcGmapComponentがAPIキーを正しく取り扱えていない問題を改善
=> fix #19635 GoogleMaps関連の処理をリファクタリング

lib/Baser/Test/Case/Model/ContentTest.php
Model/ContentTest : testIsPublish追加しました。
=> Model/ContentTest testIsPublish追加

lib/Baser/Plugin/Blog/Test/Case/Model/BlogCategoryTest.php, lib/Baser/Plugin/Blog/Test/Case/Model/BlogCommentTest.php, lib/Baser/Plugin/Blog/Test/Case/Model/BlogContentTest.php
BlogTest/testCheckEyeCatchSize追加しました。
=>  BlogTest/testCheckEyeCatchSize追加

lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Blog/Test/Case/Model/BlogContentTest.php
BlogTest/testGetDefaultValue追加しました。
=>  BlogTest/testGetDefaultValue追加

lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Blog/Test/Case/Model/BlogContentTest.php
BlogTest/testDeconstructEyeCatchSize追加しました。
=>  BlogTest/testDeconstructEyeCatchSize追加

lib/Baser/View/UserGroups/admin/form.php
ユーザーグループ管理が、削除ボタンの多言語化対応において、typoにより正常に動作しなくなっていたことを修正しました。
=>  修正: 削除ボタンの多言語化対応においてtypoによりユーザーグループ管理が正常に動作しなくなっていた

lib/Baser/Plugin/Blog/Config/setting.php
=> 言語関数の配置箇所を追加（ブログプラグイン）

lib/Baser/Controller/SiteConfigsController.php, lib/Baser/Model/Plugin.php, lib/Baser/Plugin/Feed/View/FeedDetails/admin/form.php, lib/Baser/Plugin/Mail/Model/MailContent.php, lib/Baser/Plugin/Uploader/View/Elements/admin/uploader_categories/index_list.php
__d関数の第二引数で、二重に__d関数を渡している箇所を修正しました。
=> fix: 言語関数の使用が正しく記述されていない箇所を修正

lib/Baser/View/Helper/BcFreezeHelper.php
=>  fix: 言語関数でのtypo (baserがbaesrとなっていた) を修正

lib/Baser/Plugin/Blog/View/Blog/rss/index.php, lib/Baser/Plugin/Blog/View/Blog/rss/mobile/index.php, lib/Baser/Plugin/Feed/Model/Feed.php
フィード情報にアイキャッチ画像のパスが含まれるように調整入れてみました。
取込検討してもらえますと幸いです。
http://project.e-catchup.jp/issues/21131
=> fix #21131 ブログ記事のフィード情報に、アイキャッチ画像を含めるようにするため

lib/Baser/Plugin/Mail/Test/Case/View/Helper/MaildataHelperTest.php, lib/Baser/Plugin/Mail/View/Helper/MaildataHelper.php
=> fix #21172 メールフォームの選択リストを変更すると受信メール一覧に正しく表示されなくなる問題を改善

lib/Baser/Plugin/Mail/View/Elements/mail_token.php
=> メールフォームでjQueryのloadイベントをトリガーにエラーが起こっている fixes #21296

lib/Baser/Event/BcShortCodeEventListener.php
=> fix #21539 ショートコードが1記事内で複数利用できない

lib/Baser/Config/setting.php, lib/Baser/Routing/Route/BcContentsRoute.php
lib/Baser/Config/setting.php
挙動を指定できる値を追加。
lib/Baser/Routing/Route/BcContentsRoute.php
(1) コメントと記載コードに不一致があったのでそれを修正
(2) setting.phpで追加した値を使った処理を追加
=> 管理画面URLが知れてしまう事象の修正 fixes #21689

lib/Baser/Controller/BcAppController.php
=> BcAppControllerのsendMailのアクセス権を変更

lib/Baser/View/Elements/admin/users/index_row.php
調整してみたので取込検討お願いします_(．．)_
http://project.e-catchup.jp/issues/21983
=> fix 管理側ユーザー一覧画面で、アカウント名が表示されない点を調整

lib/Baser/Model/BcAppModel.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
調整入れてみました。取込検討お願いします_(．．)_
http://project.e-catchup.jp/issues/22022
=> fix #22022 配列の記述に角括弧「[ ]」が利用されているためphp5.3の環境で動作しないため

lib/Baser/Config/session.php
=> fix #22024 管理画面から短時間でログアウトする場合がある件の改修

lib/Baser/Plugin/Mail/Controller/MailController.php
=> #21987 フォームのエラーメッセージにbrタグが表示される

lib/Baser/Model/Behavior/BcSearchIndexManagerBehavior.php
江頭さん
先程打ち合わせたとおり、調整を行いました。
お手数ですが、ご確認お願い申し上げます。
=> fix #22082 スクラッチコンテンツなどでcontent_idが存在しない物でもsearchindexに保存できるようにする

lib/Baser/Plugin/Uploader/webroot/css/uploader.css
=> #22132 アップローダープラグインのファイル一覧にて、スタイル崩れ

lib/Baser/Plugin/Mail/View/Elements/mail_form.php
=> fix #22191 メールプラグイン submitボタンをダブルクリックするとエラー表示になる問題を解決

lib/Baser/Controller/BcAppController.php
調整入れてみました。可能な際に、取込検討よろしくお願いします
http://project.e-catchup.jp/issues/22084
=> fix #22084 フロント認証設定時、ログイン中に公開側ページに表示されるツールバーが表示されない点を調整

lib/Baser/Config/setting.php, lib/Baser/Controller/BcAppController.php, lib/Baser/Controller/Component/BcAuthConfigureComponent.php
=> 認証について、Form以外の認証タイプも選択できるように変更

docker/README.md
Dockerのドキュメントの情報が古かったため更新しています。
ご確認よろしくお願いします。
=> DockerのREADME.mdの情報が古かったため更新

lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
=> fix #22743 メールフィールドのオプション欄でinput属性を指定すると、確認画面でhidden項目にならない問題を改善

lib/Baser/Controller/PagesController.php, lib/Baser/Model/BcAppModel.php
=> 固定ページ変更・追加時のメッセージにpath情報を追加

lib/Baser/Plugin/Mail/Controller/MailMessagesController.php
表題の変更を行っています（画像参照）。
ご確認後、問題なければマージをよろしくお願いします。
=> 変更: 管理画面で受信メール一覧のタイトルがフォームのタイトルを含むよう変更

lib/Baser/Model/BcAppModel.php, lib/Baser/Plugin/Blog/Model/BlogCategory.php, lib/Baser/Plugin/Blog/View/BlogCategories/admin/form.php
http://project.e-catchup.jp/issues/15424 の件も関連のようでした。
よろしくお願いします！
=> fix #22773 ブログカテゴリ名に半角スペースを入れた際にフロント側からカテゴリアーカイブページの閲覧ができない件の修正

lib/Baser/View/Elements/admin/footer.php
Copyright (C) baserCMS Users Community 2009 - 2019 All rights reserved.
↓↓
Copyright (C) baserCMS Users Community 2009 - 2019.
にして文字幅を狭めています。
=> fix #22767 スマホ閲覧時、管理画面の保存ボタンが表示されない問題を解決

lib/Baser/View/Elements/admin/sidebar.php
現状HTTPで取得するようになっているので、このままではブラウザから警告が出てしまいます。
HTTPSで取得するように変更をお願いします。
=> 管理画面サイドバーの画像をHTTPSで取得

lib/Baser/View/Elements/admin/searches/contents_index.php, lib/Baser/View/Elements/admin/searches/search_indices_index.php
- コンテンツ一覧
- 検索インデックス一覧
の検索ボックスの<form>の閉じタグが出力されていない点を修正しました。
=> 検索フォームのform閉じタグが出力されていない点を修正

lib/Baser/Controller/PagesController.php
Noticeエラーが発生していたので修正しています。よろしくお願いします。
=> 固定ページ追加時に固定ページのURLがログに記録されない問題を修正

.gitignore, __assets/basercms.sql
=> fix ignore / add sql

lib/Baser/Plugin/Mail/Controller/MailController.php
フォーム利用時、なんらかの原因でメール送信に失敗した際にエラーメッセージを表示するよう変更しています。
メール送信に失敗したにもかかわらず、完了ページを表示してしまうとユーザーに勘違いをさせてしまうためです。
以下の変更を行っています。ご確認よろしくお願いします。
- MailController->submit()内で、_sendEmail()を呼び出した際に、返り値がfalseの場合は関数内の以降の処理を実行せずにエラーを表示する
- 現状は送信データの保存に失敗した際、thanksページにリダイレクトするようになっているので、indexページにリダイレクトするよう変更
- _sendEmail()内で、管理者かユーザーどちらかへのメールの送信に失敗した場合、falseを返却
- _sendEmail()内のメール送信順序を変更
- 現状はユーザーに送信後、管理者に送信する順番だが、重要度を考えて管理者宛の送信を先に変更
- ただ単に順番を変更しただけだと、管理者送信時の`カンマ区切りで複数設定されていた場合先頭のアドレスをreplayToに利用`の部分で$userMailに誤った値が代入されてしまうため、変数名を修正
=> メール送信に失敗した場合にエラーメッセージを表示する

lib/Baser/Model/Behavior/BcUploadBehavior.php, lib/Baser/View/Helper/BcUploadHelper.php
=> BcUploadBehaviorでprimarykeyがidというカラム名以外でも対応できるよう変更

app/webroot/theme/admin-third/SiteConfigs/admin/form.php, lib/Baser/Controller/BcAppController.php, lib/Baser/View/SiteConfigs/admin/form.php
=> additionalParametersをシステム管理より設定できるよう項目を追加

lib/Baser/View/Helper/BcBaserHelper.php
可能な際に見ていただけたらうれしいです_(．．)_
よろしくお願いしますー
=> fix #1230 コンテンツメニューを表示するエレメントが固定化されているため、自由にエレメント名を指定できるようにするため

lib/Baser/Controller/ThemeFilesController.php
=> fix #1234 管理側からのテーマのテンプレート編集にPagesを追加する

lib/Baser/Network/CakeRequest.php
=> #1207 urlのアクション部分に"://"があるとトップページに遷移してしまう問題を修正

lib/Baser/Controller/PagesController.php, lib/Baser/Model/Page.php
良かったら取込検討をよろしくお願いします_(．．)_
また、固定ページテンプレート読込の結果表示時、フォルダに対する更新情報も表示するようにし、
実行者に対する更新案内を少し充実させてみました。
=> 固定ページテンプレート読込時、設定ファイルで定義したフォルダタイトルが反映されないため調整入れました

lib/Baser/Model/BcAppModel.php
=> メールプラグインの和暦フィールドで令和を選択すると、確認画面で平成に変換される問題を改善

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
どちらかというと開発側向けで、
ブログカテゴリアーカイブのビュー側で、現在のブログカテゴリ情報が一通り取れるようにしておきたかったための調整です。
可能な際に取込検討してもらえるとうれしいです。
=> fix #1279 ブログのカテゴリアーカイブで、閲覧中のブログカテゴリ情報をビュー側で取得したいため

app/webroot/theme/admin-third/Elements/admin/blog_categories/index_row.php, lib/Baser/Plugin/Blog/View/Elements/admin/blog_categories/index_row.php
管理画面のブログカテゴリ一覧でHTMLタグのエスケープが行われていなかったので追加しています。
ご確認よろしくお願いします。
=> 管理画面のブログカテゴリ一覧にカテゴリ名のエスケープを追加

lib/Baser/Plugin/Blog/Controller/BlogController.php
https://github.com/baserproject/basercms/issues/1303
こちらの件、対応しておりますのでご確認いただけますと幸いです。
Blogコントローラのindexアクションでパスを検証する処理を追加しております。
どうぞよろしくお願いいたします。
=> fix #1303 ブログ記事一覧ページ表示の際、パスを検証する処理追加

lib/Baser/Config/theme/bc_sample/css/style.css
確認画面のFormにcssがなかったので追加しました。
マージお願いします！
=> fix #1323 サンプルテーマにて、確認画面のスタイルが外れる

app/webroot/theme/admin-third/Elements/admin/sidebar.php, app/webroot/theme/admin-third/__assets/css/components/_nav.scss, app/webroot/theme/admin-third/css/admin/style.css, app/webroot/theme/admin-third/js/admin/contents/index.js, lib/Baser/View/Helper/BcAdminHelper.php, lib/Baser/webroot/js/admin/contents/index.js
確認お願いします @gondoh 
Issueはこちら
https://github.com/baserproject/basercms/issues/1310
=> admin-third でサブサイトでコンテンツを作成した際、メニューに全てのコンテンツが表示されてしまう fix #1310

app/webroot/theme/admin-third/Elements/admin/feed_configs/index_row.php, lib/Baser/Plugin/Feed/View/Elements/admin/feed_configs/index_row.php, lib/Baser/View/Elements/admin/editor_templates/index_row.php
=> fix #1330 管理機能の一部にエスケープを追加

lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/View/Helper/BcBaserHelper.php
@ryuring 
本日相談させていただいた件です。
よろしくおねがいします。
=> fix 1335 ブログindexページのツールバーのエディターへのリンクを管理画面ブログ記事一覧にしたい要望に対応

lib/Baser/Controller/PagesController.php
Issue https://github.com/baserproject/basercms/issues/1321
ちょっと無理やりな方法かもしれませんが、他の箇所を参考に調整してみました。
ひとまず固定ページのみの対応です。
ご確認よろしくお願いします。
=> fix #1321 コンテンツプレビュー時、アイキャッチ画像がプレビューで表示されない

app/webroot/theme/admin-third/js/admin/libs/jquery.bcTree.js, lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
ご確認よろしくお願いします。
Issue: https://github.com/baserproject/basercms/issues/1272
=> fix #1272 コンテンツ移動操作時のアラート時、キャンセル操作後、コンテンツ一覧画面が正常に表示されない

app/webroot/theme/admin-third/Elements/admin/toolbar.php
@ryuring 
細かい修正ですみません。
ご確認お願いできますでしょうか？
=> fix #1349 【新管理画面】ツールバーのspanタグが閉じていない問題を解決

lib/Baser/Controller/UsersController.php
http://trial.basercms.net/admin/users/reset_password
現仕様は、
1. メールアドレスの入力直後、対象ユーザのパスワードをランダムな文字列に変更する。
2. 新パスワードを記載したメールを対象ユーザ宛に送信する。
3. 対象ユーザはメールを受信することで新パスワードを知ることができる。
とお見受けしましたが、深刻な脆弱性が存在するため、暫定的な対応を施しました。
https://github.com/baserproject/basercms/blob/d31661c8a47a3956c3f554afaeb21063ce557c69/lib/Baser/Controller/UsersController.php#L538-L541
ユーザがメールアドレスを公表している場合など、前提条件付きですが、
メールアドレスを入力するだけでパスワードが変わるため、外部から定期的に変更リクエストを送信されるとログインに支障をきたします。
攻撃者の立場として、前提条件を満たすために、
https://github.com/baserproject/basercms/blob/d31661c8a47a3956c3f554afaeb21063ce557c69/lib/Baser/Controller/UsersController.php#L534-L537
この反応を活用することも想定されますが、利用者が欲する情報でもあるため、反応の良し悪しは仕様次第かと存じます。
https://github.com/baserproject/basercms/blob/d31661c8a47a3956c3f554afaeb21063ce557c69/lib/Baser/Controller/UsersController.php#L546-L549 …
=> 外部からユーザをログイン不能にされる脆弱性の暫定対応

lib/Baser/Controller/UpdatersController.php
=> fix #1412 /updateにアクセスすると An Internal Error Has Occurred. が発生する件を修正

lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Blog/View/BlogContents/admin/form.php
=> fix #1411 ブログの一覧に表示する件数について100件以内となるようバリデーションを追加

lib/Baser/Controller/InstallationsController.php
xampp環境で動作を確認いたしました。よろしくお願いいたします。
=> improved #1427 Windwos環境(xamppなど含む)でのSQLite対応を復活させる

lib/Baser/Config/setting.php, lib/Baser/Controller/InstallationsController.php
=> #1430 Windows版SQLiteの対応バージョンをconfig化する

lib/Baser/Controller/UpdatersController.php
`if (file_exists($updateLogFile))` の前に持ってきました。
=> Fix #1058 /update コンテンツに誰でもアクセスできてしまう

lib/Baser/View/Pages/admin/form.php
=> fix #1422 システム管理グループに属していないユーザーで、固定ページのプレビュー時、code欄に記載した内容が反映されないため

app/Config/session.php, lib/Baser/Config/session.php
@gondoh @kaburk セッションの設定を見直して有効期限のデフォルトを2日間にしました。
レビューお願いします。
=>  fix #1473 #1468 セッションの設定を見直した

app/webroot/theme/admin-third/Elements/admin/footer.php, lib/Baser/View/Elements/admin/footer.php
非ログイン時にversion情報を表示しないように変更しています。
ご確認おねがいします。
=> fix #1488 不要なversion情報の表示の改善

lib/Baser/Plugin/Mail/Model/MailField.php, lib/Baser/Plugin/Mail/Model/MailMessage.php
メールフィールドのチェック項目に「全角ひらがな」を加えました。
https://github.com/baserproject/basercms/issues/1505
=> 【メール】フィールドのチェックに「全角ひらがな」を加える #1505

lib/Baser/Controller/BcAppController.php, lib/Baser/Controller/SearchIndicesController.php, lib/Baser/Plugin/Mail/Controller/MailController.php
issueはこちら。
https://github.com/baserproject/basercms/issues/1511
よかったら可能な際に取込み検討お願いします。
=> 公開側検索のsubmitボタンがtype=imageで作成されている場合、座標情報が送信されエラーとなる点を修正

app/webroot/theme/admin-third/BlogPosts/admin/form.php
https://github.com/baserproject/basercms/issues/1522
こちら修正対応しておりますのでご確認ください。
何卒宜しくお願いいたします。
=> fix #1522 admin-thirdテーマ ブログ記事公開日エラー表示箇所修正

lib/Baser/Model/Datasource/Database/BcSqlite.php
=> 【システム】SQLite運用環境で Undefined offset noticeが発生する #1544

app/webroot/theme/admin-third/js/admin/libs/jquery.bcTree.js, lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
=> 【システム】コンテンツ管理のゴミ箱のプログレスインジケーターが完了しない #1543

LICENSE
=> Changed copyright year

lib/Baser/Controller/InstallationsController.php
=> 【システム】インストール時のSQLite判定を改善 #1542

lib/Baser/Controller/ToolsController.php
issue はこれになります。 https://github.com/baserproject/basercms/issues/1555
=> fix #1555 [ユーティリティ]ツリー構造チェック時、問題ないがメッセージ色が赤色となっている

lib/Baser/Plugin/Blog/Config/setting.php
詳細についてはissueのほうに書きました。レビューをよろしくお願いします。
=> #1564 【ブログ】コメント・タグを設定で無効にしている場合はサイドバーに表示しないようにする

app/webroot/theme/admin-third/__assets/css/components/_jquery-ui.scss, app/webroot/theme/admin-third/css/admin/style.css
以下のissueに対応しています。
https://github.com/baserproject/basercms/issues/1239
変更前
変更後
ご確認お願いします。
=> fix #1239 【システム】admin-thirdテーマでカレンダーの選択日と当日の判別が出来ない

app/webroot/.htaccess
=> Fix #1575 【システム】favicon.icoを配置しない場合に404エラーが発生する

lib/Baser/Config/bootstrap.php
フォーラムの報告からの改善PRです！
https://forum.basercms.net/t/topic/492/2
=> fix #1584 テーマ編集機能でcss,jsなどが編集出来ない問題の改善

lib/Baser/Model/Content.php
issue #1582 #1574 の改善を行いました。
よろしくお願いいたします。
=> fix #1582 コンテンツ管理でコンテンツを1つ下に並び替えると2つ下に移動する問題を修正

app/webroot/theme/admin-third/Elements/admin/blog_posts/index_list.php
=>  Fix #1589 【管理画面】不要な閉じタグを削除する 

lib/Baser/Plugin/Blog/Config/setting.php, lib/Baser/Plugin/Mail/Config/setting.php
issueはこちらです。 https://github.com/baserproject/basercms/issues/1603  
=> fix #1603 ブログコンテンツ、メールコンテンツのデータキャッシュが無限に生成されてしまう問題を修正

lib/Baser/Plugin/Mail/Model/MailMessage.php
和暦フィールドの値は、全て選択しないとDB保存時にエラーになるため対応を入れています。
ご確認よろしくお願いします。
- https://github.com/baserproject/basercms/issues/1041
- https://github.com/baserproject/basercms/issues/1516
- 和暦は、年・月・日 どれか一部しか入力されていない状態だとバリデーションエラーにする
- DB保存前の時点で配列だった場合はnullに変換
=> fix #1041 【メール】和暦フィールドの値を入力しない場合、データベースエラーが発生する

lib/Baser/Plugin/Blog/Config/setting.php, lib/Baser/Plugin/Blog/Controller/BlogController.php, lib/Baser/Plugin/Blog/Model/BlogContent.php, lib/Baser/Plugin/Blog/Model/BlogPost.php, lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
@ryuring 
https://github.com/baserproject/basercms/pull/1604 のリファクタ含めたキャッシュの変更になります。
確認お願いします！
=> 公開期間を利用しているBlogContent,BlogPostモデルにてキャッシュを利用しないよう変更

lib/Baser/basics.php
=> 【システム】fix #1618 PHP8の新関数をポリフィルとして追加

lib/Baser/Controller/BcAppController.php, lib/Baser/Controller/Component/BcManagerComponent.php, lib/Baser/Controller/InstallationsController.php, lib/Baser/Vendor/ga.php, lib/Baser/View/Helper/BcFreezeHelper.php, lib/Baser/View/Helper/BcUploadHelper.php
古い関数rand()をmt_rand()に変更しました。動作に違いはありません。
=> fix #1647 rand()をmt_rand()に変更

lib/Baser/View/Elements/admin/toolbar.php
issueはこちらです。 https://github.com/baserproject/basercms/issues/1694
良かったら取り込み検討お願いします。
=> fix #1694 toolbar.php内のescape指定のタイポを修正

lib/Baser/Lib/BcSite.php, lib/Baser/Routing/Router.php, lib/Baser/View/Helper/BcBaserHelper.php, lib/Baser/View/Helper/BcSmartphoneHelper.php
https://github.com/baserproject/basercms/issues/1013
上記の件について修正しました。確認をお願いします。
=> fix #1013 カノニカルURLの出力を修正

lib/Baser/Config/theme/bc_sample/__assets/css/common/_header.scss, lib/Baser/Config/theme/bc_sample/css/style.css
=> fix #1613 bc_sample 余白を削除

lib/Baser/Controller/UsersController.php
ブランチ操作していたら自動でクローズしてしまったので再度送ります。
指摘部分を反映しております。
※ https://github.com/baserproject/basercms/pull/1541 の続きです。
↓ 念の為、動作確認用のControllerEventListener です。
app/Event/HogeControllerEventListener.php
[HogeControllerEventListener.zip](https://github.com/baserproject/basercms/files/6465364/HogeControllerEventListener.zip)
=> fix  #1529 管理画面ログイン、ログアウト時の処理を拡張する為のイベントを追加

lib/Baser/Plugin/Mail/Model/MailField.php
=> fix #1568 【メール】フィールド名が長すぎるとエラーが発生する件を修正

lib/Baser/Controller/Component/BcAuthConfigureComponent.php
=> fix #1710 （未ログイン時）管理画面にアクセスした際のエラーメッセージを表示しないように修正

app/webroot/theme/admin-third/Elements/admin/blog_categories/index_list.php, app/webroot/theme/admin-third/Elements/admin/blog_comments/index_list.php, app/webroot/theme/admin-third/Elements/admin/blog_posts/index_list.php, app/webroot/theme/admin-third/Elements/admin/blog_tags/index_list.php, app/webroot/theme/admin-third/Elements/admin/contents/index_list_table.php, app/webroot/theme/admin-third/Elements/admin/feed_configs/index_list.php, app/webroot/theme/admin-third/Elements/admin/feed_details/index_list.php, app/webroot/theme/admin-third/Elements/admin/mail_fields/index_list.php, app/webroot/theme/admin-third/Elements/admin/mail_messages/index_list.php, app/webroot/theme/admin-third/Elements/admin/permissions/index_list.php, app/webroot/theme/admin-third/Elements/admin/plugins/index_list.php, app/webroot/theme/admin-third/Elements/admin/search_indices/index_list.php, app/webroot/theme/admin-third/Elements/admin/theme_files/index_list.php, app/webroot/theme/admin-third/Elements/admin/uploader_categories/index_list.php, app/webroot/theme/admin-third/Elements/admin/widget_areas/index_list.php
=> fix #1247【テーマ】admin-thirdテーマ：一覧系の画面の空欄を減らして一行の表示を増やしたい件の改修

lib/Baser/Plugin/Mail/View/Helper/MaildataHelper.php, lib/Baser/View/Helper/BcFreezeHelper.php
=> fix #1724【フォーム】セレクト・チェックボックス・ラジオボタンで値が0の選択肢を選択した場合に確認画面に表示されない件を修正

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
=> fix #1717 年別＋カテゴリーアーカイブが404になる問題の解消

app/webroot/theme/admin-third/WidgetAreas/admin/form.php, app/webroot/theme/admin-third/__assets/css/theme/_unknown.scss, app/webroot/theme/admin-third/css/admin/style.css, app/webroot/theme/admin-third/js/admin/widget_areas/form.js
=> fix #1671 ウィジェットエリア編集でドラッグ&ドロップできない問題を改善

app/webroot/theme/admin-third/MailFields/admin/form.php, lib/Baser/Plugin/Mail/Config/Schema/mail_fields.php, lib/Baser/Plugin/Mail/Config/setting.php, lib/Baser/Plugin/Mail/Controller/MailFieldsController.php, lib/Baser/Plugin/Mail/View/Helper/MailfieldHelper.php
フォームのフィールドに、「autocomplete属性」の設定項目を追加しました。
フィールド設定メニューにて、セレクトボックスにて選択できるようになります。
=> 【フォーム】フィールドへのオートコンプリート機能の付加

app/webroot/theme/admin-third/Elements/admin/content_actions.php, app/webroot/theme/admin-third/Plugins/admin/form.php, app/webroot/theme/admin-third/Sites/admin/add.php, app/webroot/theme/admin-third/Sites/admin/edit.php, app/webroot/theme/admin-third/ThemeFiles/admin/form.php, app/webroot/theme/admin-third/ThemeFiles/admin/form_folder.php, app/webroot/theme/admin-third/__assets/css/components/_actions.scss, app/webroot/theme/admin-third/css/admin/style.css
admin-thirdのボタン位置がおかしい箇所を調整しました。
よろしくお願いします！
=> fix #1759 admin-thirdのプラグインインストール時のUI調整

app/webroot/theme/admin-third/Elements/admin/sites/index_row.php, lib/Baser/webroot/js/admin/libs/baser_ajax_batch_config.js, lib/Baser/webroot/js/admin/libs/baser_ajax_data_list_config.js
=> fix #1420【ブログ】管理画面の記事一覧にて、公開・非公開を変更すると「作成者名」が非表示になる問題を改善

INSTALL.md
https://basercms.net/about/guide.html にインストールの項目を追加し、install.mdをそちらに誘導するようにしました！
=> fix 1805 install.mdが古く分かりづらい問題の改善

lib/Baser/View/Helper/BcCsvHelper.php
=> fix #1819 【フォーム】ダウンロードしたCSVがExcelなどで正しく読み込めない問題を解消

lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php, lib/Baser/Plugin/Feed/Vendor/simplepie/library/SimplePie/Item.php, lib/Baser/Plugin/Feed/Vendor/simplepie/library/SimplePie/Parse/Date.php, lib/Baser/Vendor/kcaptcha/kcaptcha.php, lib/Cake/Utility/Folder.php
=> baserCMS標準テーマフロント側PHP8対応

app/webroot/theme/admin-third/Elements/admin/blog_categories/index_row.php, app/webroot/theme/admin-third/Elements/admin/blog_comments/index_row.php, app/webroot/theme/admin-third/Elements/admin/blog_posts/index_row.php, app/webroot/theme/admin-third/Elements/admin/contents/form_alias.php, app/webroot/theme/admin-third/Elements/admin/mail_fields/index_row.php, app/webroot/theme/admin-third/Elements/admin/plugins/index_row.php, app/webroot/theme/admin-third/Elements/admin/plugins/index_row_market.php, app/webroot/theme/admin-third/Elements/admin/themes/index_list.php, app/webroot/theme/admin-third/Elements/admin/themes/index_row.php, app/webroot/theme/admin-third/Elements/admin/themes/index_row_market.php, app/webroot/theme/admin-third/SiteConfigs/admin/ajax_credit.php, app/webroot/theme/admin-third/UserGroups/admin/form.php, app/webroot/theme/admin-third/Users/admin/form.php, lib/Baser/Plugin/Blog/View/Elements/admin/blog_categories/index_row.php, lib/Baser/Plugin/Blog/View/Elements/admin/blog_comments/index_row.php, lib/Baser/Plugin/Mail/View/Elements/admin/mail_fields/index_row.php, lib/Baser/Plugin/Mail/View/Elements/admin/submenus/mail_fields.php, lib/Baser/View/Elements/admin/contents/form_alias.php, lib/Baser/View/Elements/admin/permissions/index_row.php, lib/Baser/View/Elements/admin/plugins/index_row.php, lib/Baser/View/Elements/admin/plugins/index_row_market.php, lib/Baser/View/Elements/admin/search_indices/index_row.php, lib/Baser/View/Elements/admin/themes/index_list.php, lib/Baser/View/Elements/admin/themes/index_row.php, lib/Baser/View/Elements/admin/themes/index_row_market.php, lib/Baser/View/Elements/admin/toolbar.php, lib/Baser/View/Elements/admin/user_groups/index_row.php, lib/Baser/View/SiteConfigs/admin/ajax_credit.php, lib/Baser/View/UserGroups/admin/form.php
=> 管理画面 HTMLエスケープ処理を追加

lib/Baser/Plugin/Uploader/Model/UploaderFile.php
=> fix #1844 ファイルアップローダーのファイル削除動作時、ファイルの実体が削除されない

lib/Baser/Controller/UsersController.php
afterLoginイベントが消えていたので追加しました。
ご確認お願いします。
=> Users.afterLoginイベントが消えていたため追加

lib/Baser/Config/setting.php, lib/Baser/View/Helper/BcCkeditorHelper.php
@ryuring 
@gondoh 
/app/Config/setting.phpで上書き可能な状態にしています。
ご確認の上、マージお願いできますでしょうか？
=> fix #1855 [CKEditor] aタグ内にブロック要素を置くと、勝手にaタグの外に吐き出される問題を解決

lib/Baser/Plugin/Blog/webroot/css/admin/blog_admin.css
=>  fix #1815 ブログタイプのアイコン（fontawesome）のみitalic表示になっている問題を修正

lib/Baser/Controller/PagesController.php
症状内容のissueはこちらです。 https://github.com/baserproject/basercms/issues/1863
良かったら取り込み検討お願いします。
=> fix #1863 固定ページのプレビュー時、選択している固定ページテンプレートが適用されない動作を調整

lib/Baser/View/Helper/BcFormHelper.php
関連issue: baserproject#1884
@gondoh 
cc @ryuring 
お手数ですが、ご確認の上マージをお願いします！
=> fix #1884 【フォーム】datetimePickerの刻み時間を指定できるようにしたい を解決

lib/Baser/Plugin/Mail/Model/MailField.php, lib/Baser/Plugin/Mail/Model/MailMessage.php
@ryuring 
@gondoh 
こちらご検討の上マージをお願いできますでしょうか？
=> fix #1882 [要望]メールフォーム入力チェックに「数値とハイフン」のチェックを入れたい要望を解決

plugins/bc-search-index/src/Model/Behavior/BcSearchIndexManagerBehavior.php
@ryuring 
すみません。
https://github.com/baserproject/basercms/issues/1959
https://github.com/baserproject/basercms/pull/1961 
こちらのコミットの変数が間違っておりましたので、
修正して再コミットします。
お手数ですが、マージをお願いできますでしょうか？
=> 変数が先祖返りを起こしていたため再コミット

__assets/plugins/baser-core/src/basics.php, plugins/baser-core/src/Utility/BcUtil.php, plugins/bc-mail/src/Model/Validation/MailMessageValidation.php, plugins/bc-mail/tests/TestCase/Model/Validation/MailMessageValidationTest.php
fix #1951 MailMessageValidation::checkSame のユニットテスト実装
fix #1950 MailMessageValidation::checkdate のユニットテスト実装
fix #1949 MailMessageValidation::dateArray のユニットテスト実装
fix #1948 MailMessageValidation::dateArray のユニットテスト実装
=> fix #1948 #1949 #1950 #1951 in mail message validation test

plugins/baser-core/src/Service/PagesService.php, plugins/baser-core/tests/TestCase/Service/PagesServiceTest.php
fix #2020 PagesService::createIndexConditions のユニットテスト実装
=> fix #2020 PagesService::createIndexConditions のユニットテスト実装

plugins/baser-core/src/Service/Admin/PermissionGroupsAdminService.php, plugins/baser-core/tests/TestCase/Service/Admin/PermissionGroupsAdminServiceTest.php
PermissionGroupsAdminService::getViewVarsForEdit のユニットテスト実装 #2081
PermissionGroupsAdminService::getViewVarsForIndex のユニットテスト実装 #2080
=> Dev#2080 #2081 PermissionGroupsAdminServiceのユニットテスト

plugins/bc-blog/src/Service/Front/BlogFrontService.php, plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
=> fix #2275 BlogFrontService::getViewVarsForBlogCategoryArchivesWidget のユニットテスト実装

plugins/bc-search-index/src/Model/Table/SearchIndexesTable.php
=> fix #2369 BcSearchIndexプラグインのModel関連のイベントが発生しない件を修正

plugins/bc-front/templates/plugin/BcBlog/Blog/rss/index.php
=> fix #2368 RSSフィードにてブログ記事へのURLが正しく生成されない問題を修正

plugins/bc-front/templates/plugin/BcBlog/Blog/rss/index.php
=> fix #2400 RSSフィードにてブログ記事のカテゴリ名が正しく生成されない問題を修正

plugins/bc-theme-file/tests/TestCase/Controller/Api/Admin/ThemeFilesControllerTest.php, plugins/bc-theme-file/tests/TestCase/Controller/Api/Admin/ThemeFoldersControllerTest.php, plugins/bc-theme-file/tests/TestCase/Service/Admin/ThemeFilesAdminServiceTest.php, plugins/bc-theme-file/tests/TestCase/Service/ThemeFilesServiceTest.php, plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
・データ削除用のFixtureを削除する
・ユニットテストから setFixtureTruncate を除外する
=> bc-theme-file

plugins/baser-core/src/Model/Validation/BcValidation.php, plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php, plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php
=> fix #2744 バリデーションエラーを表示する

plugins/bc-theme-file/src/Controller/Api/Admin/ThemeFilesController.php
既にユニットテストを書いてありましたのでアノテーションを付与だけです。
=> ThemeFilesController::add のユニットテスト

lib/Baser/Plugin/Mail/Model/MailMessage.php
@ryuring 
@gondoh 
@kaburk 
こちらご確認の上マージをお願いします。
=> fix #2720フィールド設定の全角ひらがなチェックに"ー”(長音符)が含まれていない問題を解決

lib/Baser/Plugin/Mail/Model/MailContent.php
issueはこちらです。 https://github.com/baserproject/basercms/issues/2842
調整したので取込検討お願いします
=> fix #2842 php8の環境において、コンテンツ一覧画面でメールフォーム複製時にエラーが表示される

plugins/bc-admin-third/templates/Admin/element/content_options.php
以下のissueに対応しました。ご確認お願いします。
https://github.com/baserproject/basercms/issues/2881
=> fix #2881 【コンテンツ】コンテンツの作成者・作成日・更新日の変更ができない

plugins/bc-admin-third/templates/Admin/layout/default.php
=> fix #3021 ViewEventListenerにて管理画面だと header, footer などのイベントが発生しない件を修正

plugins/baser-core/src/BcPlugin.php, plugins/baser-core/src/Controller/Admin/UtilitiesController.php, plugins/bc-admin-third/templates/Admin/Utilities/index.php
@ryuring
こちら、調整を入れております。
お手数ですが、ご確認お願い申し上げます。
cc @kaburk
=> fix #3050ユーティリティ機能にシンボリックリンク作成機能する問題を解決

plugins/baser-core/src/Model/Validation/BcValidation.php, plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php, plugins/bc-theme-config/src/Service/ThemeConfigsService.php, plugins/bc-theme-config/tests/TestCase/Service/ThemeConfigsServiceTest.php
=> fix #3038【5.1】ファイルを選択し保存をするとエラーが発生する【テーマ設定】

plugins/bc-admin-third/templates/plugin/BcBlog/Admin/element/BlogCategories/form.php
@ryuring 
https://github.com/baserproject/basercms/issues/3127
こちらのissueの修正です。
ご確認お願いします。
=> カテゴリ編集画面のヘルプメッセージを調整

plugins/baser-core/src/Model/Table/PermissionGroupsTable.php, plugins/baser-core/tests/TestCase/Model/Table/PermissionsGroupsTableTest.php, plugins/bc-admin-third/templates/Admin/element/PermissionGroups/form.php
=> fix #3141 【5.1】必須項目を入力せずに保存ボタンを押下すると保存されてしまう【アクセスルールグループ＞アクセスルールグループ新規登録】

plugins/bc-blog/src/View/Helper/BlogHelper.php, plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
=> add BlogHelper::getPostId

plugins/bc-blog/src/View/Helper/BlogHelper.php
=> add @unitTest to func

plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php, plugins/bc-blog/tests/TestCase/Model/BlogCategoriesTableTest.php
BlogCategories::testBeforeDelete
=>  add BlogCategories::testBeforeDelete

plugins/bc-admin-third/templates/plugin/BcUploader/Admin/element/search/uploader_files_index.php
issueはこちら https://github.com/baserproject/basercms/issues/3108
可能な際に取り込み検討お願いします
=> fix #3108 アップロードファイル一覧の絞り込み検索に「クリア」ボタンがないため追加

plugins/bc-blog/src/View/Helper/BlogHelper.php, plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
add BlogHelper::removeCtrlChars
=> BlogHelper::removeCtrlChars

plugins/bc-blog/src/View/Helper/BlogHelper.php, plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
=> add BlogHelper::isHome

plugins/bc-blog/src/Service/BlogPostsService.php, plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
add BlogPostsService::createOrder
=> add BlogPostsService::createOrder

plugins/bc-custom-content/src/Model/Entity/CustomField.php, plugins/bc-custom-content/tests/TestCase/Model/Entity/CustomFieldTest.php
add Entity CustomField::getTypeTitle
=> add CustomField::getTypeTitle

plugins/bc-custom-content/src/Model/Entity/CustomTable.php, plugins/bc-custom-content/tests/TestCase/Model/Entity/CustomTableTest.php
add Entity CustomTable::isContentTable
=> add CustomTable::isContentTable

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setLinks
=> add CustomEntriesTable_setLinks

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
=> add CustomEntriesTable_isJson

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_validationDefault
=>  add CustomEntriesTable_validationDefault

plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomFieldsTableTest.php
add CustomFieldsTable_beforeMarshal
=> add CustomFieldsTable_beforeMarshal

plugins/bc-custom-content/src/View/Helper/BcCustomContentBaserHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/BcCustomContentBaserHelperTest.php
add BcCustomContentBaserHelper_methods
=> add BcCustomContentBaserHelper_methods

plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentHelperTest.php
add CustomContentHelper_descriptionExists
=> add CustomContentHelper_descriptionExists

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_description
=> add CustomContentAdminHelper_description

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_beforeHead
=> add CustomContentAdminHelper_beforeHead

plugins/bc-custom-content/src/View/Helper/CustomContentAppHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAppHelperTest.php
add CustomContentAppHelper_isEnableField
=> add CustomContentAppHelper_isEnableField

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_getFieldName
=> add CustomContentAdminHelper_getFieldName

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_isAllowPublishEntry
=> add CustomContentAdminHelper_isAllowPublishEntry

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_getFields
=>  add CustomContentAdminHelper_getFields

plugins/bc-custom-content/src/View/Helper/CustomContentAppHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAppHelperTest.php
add CustomContentAppHelper::getEntryUrl
=>  add CustomContentAppHelper_getEntryUrl

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_getEntryColumnsNum
=> add CustomContentAdminHelper_getEntryColumnsNum

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_required
=>  add CustomContentAdminHelper_required

plugins/bc-custom-content/src/View/Helper/CustomContentArrayTrait.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentArrayTraitTest.php
add CustomContentArrayTrait_arrayValue
=> add CustomContentArrayTrait_arrayValue

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
add CustomContentAdminHelper_getEntryIndexTitle
=> add CustomContentAdminHelper_getEntryIndexTitle

plugins/bc-custom-content/src/View/Helper/CustomContentArrayTrait.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentArrayTraitTest.php
add CustomContentArrayTrait_textToArray
=> add CustomContentArrayTrait_textToArray

plugins/bc-custom-content/src/View/CustomContentFrontAppView.php, plugins/bc-custom-content/tests/TestCase/View/CustomContentFrontAppViewTest.php
add CustomContentFrontAppView_initialize
=> add CustomContentFrontAppView_initialize

plugins/bc-custom-content/src/View/CustomContentAdminAppView.php, plugins/bc-custom-content/tests/TestCase/View/CustomContentAdminAppViewTest.php
add CustomContentAdminAppView_initialize
=> add CustomContentAdminAppView_initialize

plugins/bc-custom-content/src/Plugin.php, plugins/bc-custom-content/tests/PluginTest.php
add bc_custom_contentPlugin_plugin
=> BcCustomContent/src/Plugin::services のユニットテスト

lib/Baser/Config/theme/bc_sample/Elements/widgets/search.php, lib/Baser/Config/theme/bccolumn/Elements/site_search_form.php, lib/Baser/Config/theme/nada-icons/Elements/site_search_form.php, lib/Baser/View/Elements/site_search_form.php, lib/Baser/View/Elements/widgets/search.php, lib/Baser/View/Helper/BcFormHelper.php
=> fix dev-4-202403

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateNumber
=> add CustomEntriesTable_setValidateNumber

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateEmailConfirm
=> add CustomEntriesTable_setValidateEmailConfirm

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateZenkakuHiragana
=> add CustomEntriesTable_setValidateZenkakuHiragana

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateHankaku
=> add CustomEntriesTable_setValidateHankaku

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateDatetime
=> add CustomEntriesTable_setValidateDatetime

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateZenkakuKatakana
=> add CustomEntriesTable_setValidateZenkakuKatakana

plugins/bc-custom-content/src/ServiceProvider/BcCustomContentServiceProvider.php, plugins/bc-custom-content/tests/TestCase/ServiceProvider/BcCustomContentServiceProviderTest.php
add BcCustomContentServiceProvider_services
=> add BcCustomContentServiceProvider_services

plugins/bc-editor-template/src/ServiceProvider/BcEditorTemplateServiceProvider.php, plugins/bc-editor-template/tests/TestCase/ServiceProvider/BcEditorTemplateServiceProviderTest.php
add BcEditorTemplateServiceProvider_services
=> add BcEditorTemplateServiceProvider_services

plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
add CustomEntriesTable_setValidateEmail
=> add CustomEntriesTable_setValidateEmail

plugins/bc-editor-template/src/Controller/Admin/EditorTemplatesController.php, plugins/bc-editor-template/tests/TestCase/Controller/Admin/EditorTemplatesControllerTest.php
add EditorTemplatesController_delete
=> add EditorTemplatesController_delete

plugins/bc-mail/src/Controller/Admin/MailAdminAppController.php, plugins/bc-mail/tests/TestCase/Controller/Admin/MailAdminAppControllerTest.php
add MailAdminAppController_beforeRender
=> add MailAdminAppController_beforeRender

plugins/bc-mail/src/Controller/Admin/MailFieldsController.php, plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
add Admin_MailFieldsController_index
=> add Admin_MailFieldsController_index

plugins/bc-mail/src/Controller/Admin/MailFieldsController.php, plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
add Admin_MailFieldsController_publish
=> add Admin_MailFieldsController_publish

plugins/bc-mail/src/Controller/Admin/MailFieldsController.php, plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
Add Admin_MailFieldsController_edit
=> Add Admin_MailFieldsController_edit

plugins/bc-mail/src/Controller/Admin/MailFieldsController.php, plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
add Admin_MailFieldsController_add
=> add Admin_MailFieldsController_add

plugins/bc-mail/src/Controller/Admin/MailFieldsController.php, plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
add Admin_MailFieldsController_unpublish
=> add unitTest_Admin_MailFieldsController_unpublish

plugins/bc-widget-area/src/Controller/Admin/WidgetAreasController.php, plugins/bc-widget-area/tests/TestCase/Controller/Admin/WidgetAreasControllerTest.php
=> add WidgetAreasController_add

plugins/bc-mail/src/Model/Table/MailFieldsTable.php, plugins/bc-mail/tests/TestCase/Model/Table/MailFieldsTableTest.php
add Table_MailFields_halfTextMailField
=> add unitTest_Table_MailFields_halfTextMailField

plugins/bc-mail/src/Model/Table/MailFieldsTable.php, plugins/bc-mail/tests/TestCase/Model/Table/MailFieldsTableTest.php
add MailFieldsTable_formatSource
=> add MailFieldsTable_formatSource

plugins/bc-mail/src/View/MailAdminAppView.php, plugins/bc-mail/tests/TestCase/View/MailAdminAppViewTest.php
add unitTest_MailAdminAppView_initalize
=> add unitTest_MailAdminAppView_initalize

plugins/bc-mail/src/View/MailFrontAppView.php, plugins/bc-mail/tests/TestCase/View/MailFrontAppViewTest.php
unitTest_MailFrontAppView_initialize
=> unitTest_MailFrontAppView_initialize

plugins/bc-mail/src/View/Helper/BcMailBaserHelper.php, plugins/bc-mail/tests/TestCase/View/Helper/BcMailBaserHelperTest.php
add unitTest_BcMailBaserHelper_methods
=> add unitTest_BcMailBaserHelper_methods

plugins/bc-mail/src/View/MailFrontEmailView.php, plugins/bc-mail/tests/TestCase/View/MailFrontEmailViewTest.php
add unitTest_MailFrontEmailView_initialize
=> add unitTest_MailFrontEmailView_initialize

plugins/bc-mail/src/BcMailPlugin.php, plugins/bc-mail/tests/BcMailPluginTest.php
add unitTest_BcMailPlugin_services
=> add unitTest_BcMailPlugin_services

plugins/bc-mail/src/ServiceProvider/BcMailServiceProvider.php, plugins/bc-mail/tests/TestCase/ServiceProvider/BcMailServiceProviderTest.php
add unitTest_BcMailServiceProvider_services
=> add unitTest_BcMailServiceProvider_services

plugins/bc-theme-file/src/BcThemeFilePlugin.php, plugins/bc-theme-file/tests/TestCase/BcThemeFilePluginTest.php
unitTest_BcThemeFilePlugin_services
=> unitTest_BcThemeFilePlugin_services

plugins/bc-theme-config/src/BcThemeConfigPlugin.php, plugins/bc-theme-config/tests/TestCase/BcThemeConfigPluginTest.php
add unitTest_BcThemeConfigPlugin_services
=> add unitTest_BcThemeConfigPlugin_services

plugins/bc-widget-area/src/BcWidgetAreaPlugin.php, plugins/bc-widget-area/tests/TestCase/BcWidgetAreaPluginTest.php
add unitTest_BcWidgetAreaPlugin_services
=> add unitTest_BcWidgetAreaPlugin_services

plugins/bc-uploader/src/Controller/Admin/UploaderFilesController.php, plugins/bc-uploader/tests/TestCase/Controller/Admin/UploaderFilesControllerTest.php
add unitTest_UploaderFilesController_delete
=> add unitTest_UploaderFilesController_delete

plugins/bc-widget-area/src/Model/Entity/WidgetArea.php, plugins/bc-widget-area/tests/TestCase/Model/Entity/WidgetAreaTest.php
add unitTest_WidgetArea_getWidgetsArray
=> add unitTest_WidgetArea_getWidgetsArray

plugins/bc-widget-area/src/Model/Entity/WidgetArea.php, plugins/bc-widget-area/tests/TestCase/Model/Entity/WidgetAreaTest.php
add unitTest_WidgetArea_setWidgets
=> add unitTest_WidgetArea_setWidgets

plugins/bc-custom-content/src/Service/CustomEntriesService.php, plugins/bc-custom-content/tests/TestCase/Service/CustomEntriesServiceTest.php
add unitTest_CustomEntriesService_getFieldControlType
=> add unitTest_CustomEntriesService_getFieldControlType

plugins/bc-favorite/src/ServiceProvider/BcFavoriteServiceProvider.php, plugins/bc-favorite/tests/TestCase/ServiceProvider/BcFavoriteServiceProviderTest.php
add unitTest_BcFavoriteServiceProvider_service
=> add unitTest_BcFavoriteServiceProvider_service

plugins/bc-favorite/src/BcFavoritePlugin.php, plugins/bc-favorite/tests/TestCase/BcFavoritePluginTest.php
add unitTest_BcFavoritePlugin_service
=> add unitTest_BcFavoritePlugin_service

plugins/bc-uploader/src/Controller/Admin/UploaderCategoriesController.php, plugins/bc-uploader/tests/TestCase/Controller/Admin/UploaderCategoriesControllerTest.php
add unitTest_UploaderCategoriesController_copy
=> add unitTest_UploaderCategoriesController_copy

plugins/bc-uploader/src/Controller/Admin/UploaderFilesController.php, plugins/bc-uploader/tests/TestCase/Controller/Admin/UploaderFilesControllerTest.php
add unitTest_UploaderFilesController_edit
=> add unitTest_UploaderFilesController_edit

plugins/bc-mail/src/Model/Table/MailContentsTable.php, plugins/bc-mail/tests/TestCase/Model/Table/MailContentsTableTest.php
add unitTest_MailContentsTable_createSearchIndex
=> add unitTest_MailContentsTable_createSearchIndex

plugins/bc-uploader/src/ServiceProvider/BcUploaderServiceProvider.php, plugins/bc-uploader/tests/TestCase/ServiceProvider/BcUploaderServiceProviderTest.php
unittest_BcUploaderServiceProvider_services
=> unittest_BcUploaderServiceProvider_services

plugins/bc-uploader/src/Controller/Admin/UploaderConfigsController.php, plugins/bc-uploader/tests/TestCase/Controller/Admin/UploaderConfigsControllerTest.php
add unitTest_UploaderConfigsController_index
=> add unitTest_UploaderConfigsController_index

plugins/bc-uploader/src/Controller/Admin/UploaderCategoriesController.php, plugins/bc-uploader/tests/TestCase/Controller/Admin/UploaderCategoriesControllerTest.php
add unitTest_UploaderCategoriesController_index
=>  add unitTest_UploaderCategoriesController_index

plugins/bc-mail/src/Model/Table/MailMessagesTable.php, plugins/bc-mail/tests/TestCase/Model/Table/MailMessagesTableTest.php
add unitTest_MailMessagesTable_initialize
=> add unitTest_MailMessagesTable_initialize

plugins/bc-uploader/src/Model/Table/UploaderFilesTable.php, plugins/bc-uploader/tests/TestCase/Model/Table/UploaderFilesTableTest.php
add unitTest_UploaderFilesTable_getSourceFileName
=> add unitTest_UploaderFilesTable_getSourceFileName

plugins/baser-core/src/Model/Entity/UserGroup.php, plugins/baser-core/tests/TestCase/Model/Entity/UserGroupTest.php
add unitTest_UserGroup_isAdmin
=> add unitTest_UserGroup_isAdmin

plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php, plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
unitTest_CustomContentAdminHelper_isEnabledMoveDownEntry
=> unitTest_CustomContentAdminHelper_isEnabledMoveDownEntry

plugins/bc-mail/src/Controller/MailFrontAppController.php, plugins/bc-mail/tests/TestCase/Controller/MailFrontAppControllerTest.php
add unitTest_MailFrontAppController_beforeRender
=> add unitTest_MailFrontAppController_beforeRender

plugins/bc-mail/src/View/Helper/MailHelper.php, plugins/bc-mail/tests/TestCase/View/Helper/MailHelperTest.php
Add unitTest_MailHelper_descriptionExists
=> Add unitTest_MailHelper_descriptionExists

plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php, plugins/bc-custom-content/tests/TestCase/Model/Table/CustomFieldsTableTest.php
add unitTest_CustomFieldsTable_encodeEntity
=> add unitTest_CustomFieldsTable_encodeEntity

plugins/bc-custom-content/src/Utility/CustomContentUtil.php, plugins/bc-custom-content/tests/TestCase/Utility/CustomContentUtilTest.php
add unitTest_CustomContentUtil_getPluginSetting
=> add unitTest_CustomContentUtil_getPluginSetting

plugins/baser-core/src/Model/Entity/User.php, plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
=> add unitTest_User_isSuper

plugins/baser-core/src/View/Helper/BcArrayHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcArrayHelperTest.php
add unitTest_BcArrayHelper_addTest
=> add unitTest_BcArrayHelper_addTest

plugins/bc-installer/src/ServiceProvider/BcInstallerServiceProvider.php, plugins/bc-installer/tests/TestCase/ServiceProvider/BcInstallerServiceProviderClass.php
add unitTest_BcInstallerServiceProvider_services
=> add unitTest_BcInstallerServiceProvider_services

plugins/baser-core/src/Model/Entity/UserGroup.php, plugins/baser-core/tests/TestCase/Model/Entity/UserGroupTest.php
add unitTest_UserGroup_getAuthPrefixSettingsArray
=> add unitTest_UserGroup_getAuthPrefixSettingsArray

plugins/baser-core/src/Model/Entity/UserGroup.php, plugins/baser-core/tests/TestCase/Model/Entity/UserGroupTest.php
add unitTest_UserGroup_getAuthPrefixArray
=> add unitTest_UserGroup_getAuthPrefixArray

plugins/baser-core/src/View/Helper/BcCkeditorHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
add unitTest_BcCkeditorHelper_createDomId
=> add unitTest_BcCkeditorHelper_createDomId

plugins/baser-core/src/Model/Entity/UserGroup.php, plugins/baser-core/tests/TestCase/Model/Entity/UserGroupTest.php
add unitTest_UserGroup_isAuthPreFixAvailabled
=> add unitTest_UserGroup_isAuthPreFixAvailabled

plugins/baser-core/src/Model/Validation/BcValidation.php, plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php
add unitTest_BcValidation_reserved
=> add unitTest_BcValidation_reserved

plugins/baser-core/src/View/Helper/BaserCoreBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BaserCoreBaserHelperTest.php
add unitTest_BaserCoreBaserHelper_method
=> add unitTest_BaserCoreBaserHelper_method

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
add unitTest_BcBaserHelper_getPluginBaser
=> add unitTest_BcBaserHelper_getPluginBaser

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
add unitTest_BcBaserHelper_copyYear
=> add unitTest_BcBaserHelper_copyYear

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
add unitTest_BcBaserHelper_getSiteUrl
=> add unitTest_BcBaserHelper_getSiteUrl

plugins/baser-core/src/View/Helper/BcFreezeHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
add unitTest_BcFreezeHelper_datepicker
=> add unitTest_BcFreezeHelper_datepicker

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
add unitTest_BcBaserHelper_isCategoryTop
=> add unitTest_BcBaserHelper_isCategoryTop

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
add unitTest_BcBaserHelper_getHere
=> add unitTest_BcBaserHelper_getHere

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
add unitTest_BcBaserHelper_mark
=> add unitTest_BcBaserHelper_mark

plugins/baser-core/src/View/Helper/BcContentsHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcContentsHelperTest.php
add unitTest_BcContentHelper_getJsonItems
=> add unitTest_BcContentHelper_getJsonItems

plugins/baser-core/src/View/Helper/BcFreezeHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
add unitTest_BcFreezeHelper_password
=> add unitTest_BcFreezeHelper_password

plugins/baser-core/src/View/Helper/BcBaserHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
=> BcBaserHelper::icon

plugins/bc-admin-third/templates/Admin/element/Contents/index_list_tree.php
コンテンツ一覧のツリー表示時のちらつきを少し軽減しています。
issue作成時はローディングがいいと思っていたのですが、以前よりも速度が改善したのかそこまでは不要そうです。
ご確認お願いします。
issue: https://github.com/baserproject/basercms/issues/1932
=> コンテンツ管理ちらつき軽減

plugins/baser-core/src/View/Helper/BcFreezeHelper.php, plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
@ryuring 
お手数ですが、こちらご確認の上マージをお願いします。
=> fix #3587 メールフィールド textareaが確認画面でも入力欄が出てしまう問題を解決

plugins/bc-blog/src/View/Helper/BlogHelper.php
#3674 のIssueに対するプルリクになります。
よろしくお願いします。
=> fix baserproject#3674 BlogHelperの一部関数が5.1系に対応していない

plugins/baser-core/src/Utility/BcComposer.php, plugins/baser-core/tests/TestCase/Utility/BcComposerTest.php
@ryuring Docker中にフォルダーの権限を変更・確認できないみたいなので異常ケースをテストを書きませんでした。
確認お願いします。
=> BcComposer::checkEnv　のユニットテスト

plugins/baser-core/src/Model/Table/AppTable.php, plugins/baser-core/tests/TestCase/Model/Table/AppTableTest.php
@ryuring イベントのテストはすでにありましたのでイベントテストを書かないです。
=> AppTable::find　のユニットテスト

plugins/bc-admin-third/templates/Admin/element/Themes/index_row.php
=> テーマ一覧 テーマのdescriptionが設定されていないとエラー

plugins/bc-uploader/src/Controller/UploaderFilesController.php
issue: #3847 のプルリクになります。よろしくお願いします。
=> fix #3847 フロント側のログインユーザーに公開期間外のアップロードファイルが表示されてしまう

plugins/bc-blog/src/Service/BlogPostsService.php
@ryuring 
お手数ですが、ご確認の上マージをお願いできますでしょうか？
=> fix #3959 【blog】一覧表示でブログIDを指定する場合、IDが複数の場合エラーになる問題を解決

plugins/baser-core/src/Service/BcDatabaseService.php
狙った動作、独自プラグインの初期データが入ったのでPR送ります。
=> 独自プラグインの初期データが復元されない #4023

plugins/baser-core/src/Model/Validation/BcValidation.php, plugins/bc-admin-third/templates/plugin/BcThemeConfig/Admin/ThemeConfigs/index.php, plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
https://github.com/baserproject/basercms/issues/4021
上記の修正です。ご確認お願いします。
=> URL形式以外の文字が入力できてしまう #4021

config/bootstrap.php, plugins/baser-core/config/bootstrap.php
@ryuring 
x-powerd-byヘッダを削除しました。
=> X-Powered-Byヘッダーを送信しない機能が欲しい #4125

webroot/.htaccess
@ryuring 
お手数ですがご確認お願いできますでしょうか？
=> fix #4151 【コンテンツ】フォルダの実体参照が出来ない問題を解決

docker/docker-compose.yml.default
#4156 の対応を実施いたしました。お手数をおかけしますが、ご確認よろしくお願いいたします。
=> fix #4156 PostgreSQLのバインドマウント設定を修正

plugins/baser-core/src/Controller/AppController.php
issue: https://github.com/baserproject/basercms/issues/4161
ご確認お願いします。
=> 未ログイン状態だと、サブフォルダに設置したbaserの管理画面の特定のURL以外にアクセスできない

plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php, plugins/bc-custom-content/tests/Scenario/CustomEntriesScenario.php
@ryuring 
こちら、ご確認の上マージをお願いします。
=> fix #4178 【カスタムコンテンツ】CustomContentHelperのgetPublishedが作成日を取得してしまう問題を解決

plugins/bc-admin-third/templates/plugin/BcCustomContent/Admin/CustomEntries/edit.php
@ryuring 
カスタムコンテンツ エントリー編集画面の公開URL表示調整です。
ご確認お願いします。
=> カスタムコンテンツ エントリー編集画面の公開URL表示を調整

plugins/bc-admin-third/templates/Admin/layout/default.php
@ryuring 
先ほどお話ししましたcssの重複読込の件です。
お手数ですが、ご確認の上、マージをお願いします。
=> fix #4203 【システム】管理画面でcssが重複して読み込まれてしまう問題を解決

plugins/bc-front/templates/ContentFolders/default.php, plugins/bc-front/templates/ContentFolders/eyecatch.php
@ryuring 
お手数ですが、御確認お願いできますでしょうか？
=> fix #4222【コンテンツ】コンテンツフォルダ内が空のときにコンテンツのタイトルだけが表示される問題 を解決

plugins/baser-core/src/Model/Behavior/BcContentsBehavior.php, plugins/baser-core/src/Service/ContentsService.php
テーブルのアソシエーションを追加した際にSQLのエラーになる場合があるので調整しています。
ご確認お願いします。
=> クエリの項目指定にテーブル名追加

plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php
@ryuring 
https://github.com/baserproject/basercms/issues/4255
こちらの件解消しました！
レビューお願いします！
=> fix #4255 getEntriesメソッドで正しいエントリーが取得できない問題を解消

plugins/baser-core/src/Service/UsersService.php
#4261 
こちらの修正プルリクエストになります。
よろしくお願いします。
=> 【ユーザー】ユーザー一覧に表示される検索で、「クリア」が上手く動かない #4261
