baserproject/basercms

- vagrant_cookbooks/yum-packages/recipes/default.rb
プラグインをアップロードしようとしたところunzipが入っていなかったので追加しておきます。
> Vagrantの開発マシンにunzipを追加

- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
現在のmainImage()で生成されるHTMLが、idのみしかつかなくて自由度が少なく、CSS指定などで不自由があるのでclass属性がつけられるようにしました。またidも無効化出来るようにしました。よろしくお願いします。
> BcBaserHelperのmainImage()でクラス名の指定とidの無効化ができる拡張

- lib/Baser/View/Helper/BcBaserHelper.php
https://github.com/baserproject/basercms/pull/239
の修正です。
$_View のクラスのヒントとなるコメントはBcAppHelperに書いたほうが良さそうなので外しました。
他はほぼ前と同じです。
>if-elseのネストが深いところを修正
>deprecatedなメソッドを置換
>CakeRequest経由のマジックプロパティを不使用に
>extract()を利用している部分を修正（IDEや静的コード解析の恩恵を受けにくいので）
>コメント・コード整形
> BcBaserHelperのリファクタリング

- lib/Baser/Config/bootstrap.php
- lib/Baser/Configure/BcThemeConfigReader.php
- lib/Baser/Model/Theme.php
- lib/Baser/Test/Case/BcAllConfigureTest.php
- lib/Baser/Test/Case/BcAllTest.php
- lib/Baser/Test/Case/Configure/BcThemeConfigReaderTest.php
https://github.com/baserproject/basercms/pull/234
の続きです。チケット切り忘れてたので追加しました。
http://project.e-catchup.jp/issues/8013
ConfigReaderInterfaceを実装しました。
ディレクトリはCakeに倣いConfigureに置きました。
Configureクラスからも使えるみたいですが、ややこしそうなので直に使っています。
使い方は下記のような感じです。引数や戻り値は連想配列にしてあります。
$reader = new BcThemeConfigReader();
$config = $reader->read($themeName);
$reader->dump($themeName, array(
'title' => 'hogehoge',
'description' => 'hoge',
'author' => 'hoge',
'url' => 'http://example.com'
));
> 問題点 #8013 テーマの保存時に入力内容にシングルクォーテーションが含まれるとエラーになる 修正

- lib/Baser/Lib/BcAgent.php
- lib/Baser/Routing/Filter/BcRequestFilter.php
ConfigureのBcRequest以下のキーに書き込む条件を間違っていました。
この部分は特に$_SERVER['HTTP_USER_AGENT']の値にかかわらず、
単純にURLのプリフィックスが対応するエージェントを探してその情報を書き出せばよかったんですね。
> fixes #8034 3.0.7開発版でスマートフォンが動作していない

- .travis.yml
追加したバージョン全てでテストは通りましたが、
念のためHHVMとPHP7.0は失敗しても問題ない設定にしてます。
本当は5.2も追加したかったんですがcomposer対応してないのでどうしようもない感じです。
あとデータベースも増やさないとですね。
> Travis-CIで実行するPHPのバージョンに5.6,HHVM,7.0を追加

- .travis.yml
- lib/Baser/Lib/BcAgent.php
- lib/Baser/Plugin/Blog/Test/Case/BlogAllTest.php
- lib/Baser/Plugin/Feed/Test/Case/FeedAllModelTest.php
- lib/Baser/Plugin/Feed/Test/Case/FeedAllTest.php
- lib/Baser/Plugin/Mail/Test/Case/MailAllControllerTest.php
- lib/Baser/Plugin/Mail/Test/Case/MailAllHelpersTest.php
- lib/Baser/Plugin/Mail/Test/Case/MailAllModelTest.php
- lib/Baser/Plugin/Mail/Test/Case/MailAllTest.php
環境変数で条件分岐して5.2の時はcomposer installをスキップしています。
PHPUnitはTravisに元々入ってるものを使って動きました。
また、一部でPHP5.3で追加された機能の利用があったので修正しました。
* BcAgentクラスで静的遅延束縛(static)を利用 →特に継承予定はないのでselfに変更
* プラグインのテストスイートのクラスで__DIR__を利用　→dirname(__FILE__)に変更
> Travis-CIで実行するPHPのバージョンに5.2を追加

- .travis.yml
- lib/Baser/Controller/Component/BcManagerComponent.php
ビルドのジョブが増えてきたので。
sudo: false と書くだけでDockerベースの高速なスタックを使ってくれるらしいので変えてみました。
参考：http://postd.cc/faster-builds-with-container-based-infrastructure/
また、Composerのデータをキャッシュさせるようにしました。
数回実行してみた印象は、ビルド開始までの待ち時間が減り、テスト実行時間の振れ幅は増えたというところです。
総実行時間はビルド待ち時間とComposerの短縮分で減ったかなと。
なお、コンテナのPHP7環境が5.3で非推奨となったeregi()関数をサポートしていないらしく、
インストール前のcheckenvがこけたのでpreg_match()とi修飾子に入れ替えています。
http://php.net/manual/ja/function.eregi.php
> Travisのビルドを高速化

- lib/Baser/Model/Page.php
- lib/Baser/Test/Case/Model/PageTest.php
> fixed #3325 固定ページで、文法エラーとなるPHPコードをソースに書くと編集画面が開けなくなる 修正

- lib/Baser/Model/Page.php
http://project.e-catchup.jp/issues/1850
確認お願いします。
> fixed #1850 ページ機能でページ名の先頭を大文字にすると対象のページを確認できない 修正

- lib/Baser/Test/Case/View/Helper/BcFormHelperTest.php
- lib/Baser/Test/Case/View/Helper/BcUploadHelperTest.php
- lib/Baser/View/Helper/BcFormHelper.php
- lib/Baser/View/Helper/BcUploadHelper.php
`BcUploadHelper`および、`BcFormHelper::file()`メソッドのhasMany対応パッチです。
任意個数の画像をアップロードするような要件のあるプラグインを作成する際に必要になる、hasManyリレーションで取得したデータに対しても、アップロードフォームを表示できるようにしています。
```
$this->BcForm->file('Foo.0.image');
```
> Support hasMany File Upload

- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
> fixed #8437 ログイン時のページリンクに関わるBcBaserHelperの一部のメソッドのテストが失敗する

- app/Config/bootstrap.php
- lib/Baser/Config/bootstrap.php
Dispatcher.filtersに登録されているディスパッチャー
名前：優先度
BcAssetDispatcher: 4
BcRequestFilter: 6 
AssetDispatcher: 9  << 被り
CacheDispatcher: 9  <<  被り
BcCacheDispatcher : 10
のうち被っているCakeの元のAssetとCacheを外しました。
それぞれのディスパッチャーの優先度も振りなおしても良さそうですね。
> fixed #8434 キャッシュとアセットのディスパッチャーが二重登録されていて挙動がわかりにくい

- lib/Baser/Config/bootstrap.php
PR出し直しです。
App::build()の題に引数にApp::APPENDを指定することで、探索パスリストの最後にパスを追加することができます。
array_merge()とApp::path()を利用している冗長な部分を省きました。
テーマヘルパーとテーマプラグインの処理も同様に変更しています。
> クラスの探索パス登録処理を修正

- lib/Baser/Plugin/Blog/Controller/BlogContentsController.php
大文字小文字の違いなので、baserCMS2→3時の修正漏れかなと思います。
確認お願いします。
> fixed #8436 ブログ編集画面から遷移するテンプレート編集のURLが正しくない

- lib/Baser/Plugin/Mail/Model/Message.php
- lib/Baser/Plugin/Mail/View/Helper/MaildataHelper.php
MailDataHelper::control()の出力文字列の先頭のスペースを取り払ったメソッドを新たに作成しました。
確認お願いします。
> fixed #8392 メールプラグインのCSVダウンロードで値の先頭に半角スペースが入る 修正

- lib/Baser/Config/setting.php
> fixed #8435 認証プレフィックスの利用例をセッションキーを共用する設定に書き換える

- lib/Baser/Test/Case/Config/SessionTest.php
ini_get()の返り値がstringとして厳密に比較されていたようです。
> HHVM用にテストコードを調整

- lib/Baser/Model/Page.php
- lib/Baser/Test/Case/Model/PageTest.php
「PHPの構文エラーです」としか表示しておらずわかりにくかったので、PHPの吐き出すエラーを後ろに付け加えました。
> 固定ページ本文のPHP文法チェックエラーの情報量を増やした

- app/Config/core.php
キャッシュの時間が999日になっている。
BcBaserHelper::blogPostsで表示した場合、固定ページのキャッシュが残ってしまい、ブログの公開・非公開の期限が実質無効となってしまう問題が発生しています。
ご検討ください！
> デフォルトのキャッシュが999日なのを5分に変更

- lib/Baser/View/Themes/admin/index.php
標準のアラートウィンドウの初期値変更はできないため、アラート用のウィンドウをjQuery-uiで生成し、選択初期値を キャンセル としました。
> fixes #8398 初期データ読込ボタンを連打した場合でも実行されないようにした

- lib/Baser/Plugin/Blog/Controller/BlogController.php
[追加したフィールド]
id, user_id, blog_category_id, posts_date
[追加理由]
以前はget_recent_entries()では、"no","name"しか取得できず、
その投稿に関連する情報を取得できないため。
id, user_id, blog_category_id, posts_dateを追加することで、
ブログサイドバーをカスタマイズしやすくなると思います。
> [ブログウィジェット] get_recent_entries()にfindのfieldを追加

- lib/Baser/View/SiteConfigs/admin/form.php
v3.0.3 から Google Analytics のコードを googleAnalytics() で出力できるようになり、/lib/Baser/View/Elements/google_analytics.php にもその旨書かれているので、バルーンヘルプの文言を編集しました。
> googleAnalytics() の実装に合わせてバルーンヘルプの文言変更

- lib/Baser/Test/Case/Model/Behavior/BcUploadBehaviorTest.php
エラーメッセージ　Fatal error: Cannot use string offset as an array に対応
> BcUploadBehaviorTest::testSaveTmpFilesの修正

- lib/Baser/Plugin/Mail/webroot/js/admin/mail_fields/form.js
7文字固定だと、ハイフン入りの郵便番号の入力(XXX-XXXXの8文字)に対応できないので、7文字での固定の設定は不要と思われます。
よろしくお願いします！
> fix #9920 メールフォームにてタイプを自動補完郵便番号に設定すると最大値（文字数）が7文字に固定される

- lib/Baser/Config/theme/m-single/Elements/mail_form.php
- lib/Baser/Plugin/Mail/View/Elements/mail_form.php
- lib/Baser/Plugin/Mail/View/Elements/mail_token.php
- lib/Baser/Plugin/Mail/View/Helper/MailHelper.php
mail_form.phpに記述のないフォームは通常動作（ヒストリーバックが効かない）とすることで
既存テーマとの互換性を取りたいとおもいます。
よろしくお願いします。
> fix #9122 ブラウザヒストリーバック（戻るボタン）対応コードをHelperで出力するように変更

- lib/Baser/Test/Case/View/Helper/BcTextHelperTest.php
> BcTextHelperTest::testDateTime()の修正

- lib/Baser/Test/Case/Model/UserGroupTest.php
Travisで失敗したエラーを修正
ローカルでは、falseでも0でも成功しました
> UserGroupTest::testIsAdminGlobalmenuUsedの修正

- lib/Baser/Controller/Component/BcManagerComponent.php
- lib/Baser/Test/Case/Model/PageTest.php
deployTheme()で引数$themeを指定した場合に、
$Folderが初期化されていないため、
1208行目の$Folder->delete($targetPath) でエラーが出るバグ
> BcManagerComponentのバグ修正

- lib/Baser/Plugin/Mail/Controller/MailController.php
メールプラグインの調整後、挙動が変わっていたのでリダイレクトするよう変更しています。
調整後の挙動が正しいようであればリジェクトお願いします。
> 完了画面に直接アクセスした場合に404ではなく入力画面にリダイレクトするよう変更

- lib/Baser/Test/Case/View/Helper/BcGooglemapsHelperTest.php
- GoogleMaps の情報取得に失敗した場合に、テストをスキップするように変更。
> BcGooglemapsHelperTestの修正

- lib/Baser/Config/Schema/plugins.php
> fixes PostgreSQL利用時、バージョン番号表記が長過ぎる場合にstep5でエラーが発生する点を調整

- lib/Baser/View/Helper/BcBaserHelper.php
例: /theme/THEME_NAME/Errors/ 内に配置したビューファイル側から、以下のようにタイトルを設定できない点の調整になります。
```
$this->BcBaser->setTitle('Error');
$this->pageTitle = 'Error';
```
> fixes Errorページで、ビュー側からページタイトルを設定できない点を調整

- lib/Baser/Controller/BcAppController.php
検証される文字列と、実際に利用される文字列が異なっているので修正しています。
よろしくお願いします。
> メール送信時のbccメールアドレス検証と、送信されるメールアドレスが異なる点の修正

- lib/Baser/webroot/css/admin/contents.css
> fixes ブログ記事のアイキャッチ画像に大きい画像を登録した際に、管理側のコンテンツ表示領域をはみ出してしまう点を調整

- lib/Baser/Plugin/Mail/View/Helper/MaildataHelper.php
- lib/Baser/Test/Case/Controller/Component/BcGmapsComponentTest.php
メールプラグインでマルチチェックボックスを使用し、
複数チェックボックス項目を選択し送信されたメールにおいて、
最初の項目のみ半角スペースが空いてしまいます。
原因としては、HelperのMaildataHelperのcontrolメソッドで、
先頭に半角スペースを付加しリターンしているためです。
ですが、このcontrollメソッドの半角スペースを削除してはいけないみたいなので、
チェックされた項目全てに半角スペースが付加されるように修正しました。
> マルチチェックボックスの最初の項目のみ半角スペースが空くため、チェックされた全ての項目に半角スペースを追加。

- lib/Baser/Model/Page.php
通常処理では問題はないのですが、別のプラグインから処理実行時に動作しないので追加して欲しいです。
> 固定ページの検索インデックス作成時の処理をプラグインから実行する時にプラグイン名が有効になってしまうのでパラメータを追加

- lib/Baser/View/SiteConfigs/admin/form.php
- サイト基本設定画面の保存ボタン押下時のクリックイベントが取得できていない
- SMTP設定欄において、IE11では inputタグの autocomplete: off が効かないため、意図しない保存動作が可能となっている。そのため、アラートを表示して確認する動作を追加した
宜しければ取込みお願いします。
> サイト基本設定画面の保存ボタン押下時のクリックイベントが取得できていない点を修正

- lib/Baser/Event/BcEventListener.php
- lib/Baser/Test/Case/BcBasicsTest.php
- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/basics.php
- 先週末の他のテストが失敗した原因は、テスト用に削除したプラグインを再読み込みしていないことでした。再読み込みさせるようにしたら、すべてのテストが成功しました。
- BcBaserHelperTestを少し修正しています。テストランナーにHTMLが出力されていたため、ob_get_clean()を使うようにしました。
> basics.phpのテストを追加

- .travis.yml
例のTravisが落ちていた原因がこれそのものかはわからないですが。
トークンの値は流石に.travis.ymlに直書きできないため、
GITHUB_TOKENという名前の環境変数を拾うようにしました。
GitHubでPersonal Access Tokenを発行して
Travis-CIのEnvironment Variablesに環境変数の追加をお願いします。
https://travis-ci.org/baserproject/basercms/settings
合わせてcomposer self-updateを実行するように変更しました。
> Travis-CI用にGitHubのOAuthトークンを追加

- lib/Baser/Event/BcEventListener.php
ビューイベントリスナで
/**
* 登録イベント
*
* @var array
*/
public $events = array(
'beforeRender',
'beforeLayout',
);
としていたらbeforeRenderが２回呼ばれていました。
BcEventListener::implementedEvents()の$optionsが
繰り返し処理の中で引き継がれてしまっているのが原因。
foreachのループごとに初期化することで対応
> fix #11096 イベントリスナの挙動を修正

- lib/Baser/Controller/ToolsController.php
改修提案のプルリクエストです。
ご検討よろしくお願いします。
- 例えば、承認プラグインを利用している際の固定ページ一覧表示のときや、ブログ記事一覧表示のタイミング
> データの復元を利用した際に、復元後にキャッシュが利用され、復元後の最新状態となっていないように見えてしまう点を調整

- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
やはりわかりづらいので、pull request わけました。
https://github.com/baserproject/basercms/pull/405/files/f653338e473dee1fc172102e8f8ad797c0d7ccff#r62588514
の方は、eyeCatchの方もとりこめたら、削除します。
で、
isPluginContents は、isPluginContent へ変更
>プラグイン名の指定は、アッパーキャメルケースを前提として、isPluginContent() 内にて、Inflector を利用し、アンダースコア区切りに強制的に変換して判定する仕様でどうでしょう？
で調整しています。
まぁ、公式には、アッパーキャメルケースですが、
hollow_world プラグインの場合
HollowWorld
hollowWorld
hollow_world
のどれもで、true になるので、厳密にした方がよければ調整いたします。
>  fixes #12019 isBlog isMail 及びそのテストを追加

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
- lib/Baser/Test/Case/View/Helper/BcUploadHelperTest.php
- lib/Baser/View/Helper/BcUploadHelper.php
実質的には、BcUpload->uploadImage の修正になります。
87行目	$entity = $this->entity(); 
は、利用されてないので削除しました。
getBcUploadSettingは、2つのメソッドで同一処理があったのでまとめました。
その他ハードコーディングされている部分はできるだけまとめるように調整いれてます。
(全部でないですが）
> fixes #12010 eyeCatchのoptionにoutputを追加してurlでの戻り値を取得出来るようにした

- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
第2引数は options として調整しました。後方互換は維持しています。
allowableTags は、strip_tags関数のマニュアルと同じ名称がいいと思いこちらにしています。
> fixes #12038 BcBaser->getTItleの第2引数を調整、tag除去等のオプションを追加

- lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php
- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
>      fixes #12057 BlogHelper に getCurrentBlogId currentBlogId の実装

- lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
> fix #12064 メールフォーム セレクトボックスのオプション欄にてempty|falseが有効にならない

- Vagrantfile.default
新しいバージョンのVagrant環境（下記参照）で、新たに環境構築できない問題を修正しました。
新しいバージョンのChefが上手く利用できておらず、「INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/」等のエラーが出ていたところ、安定して使えそうなChefのバージョンを決め打ちするようにして、環境が立ち上がるようにしました。
■問題を確認した環境
MacOS 10.11.5
Vagrant 1.8.1
VirtualBox 5.0.20
> 最新環境のVagrantで環境を立ちあげられない問題を修正した。

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
- プラグイン側からBlogHelperを利用するケースで発生する
よろしくお願いします。
> fixes #12502 getCategoryUrl() でブログカテゴリURLが取得できない場合がある

- vagrant_cookbooks/httpd/recipes/default.rb
表題の通りです。
そのままマージしても良かったのですが、一応現在開発中のものとの兼ね合いもあるかと思いますので、問題なければマージお願いします。
> yumのphpMyAdminがPHP5.5未満でインストール出来なくなってしまったためバージョン指定を追加

- lib/Baser/Controller/PagesController.php
- lib/Baser/Model/SiteConfig.php
- lib/Baser/View/Pages/admin/index.php
dev-4のコンテンツ一覧のロック機能をdev-3の固定ページ一覧に実装しました。
dev-4との違いは
・ユーザーIDでチェックしているところをセッションIDに変更
　（同一ユーザーの別ブラウザ対応）
・viewにセットする日付けをUNIX Timeに変更
　（比較時にUNIX Timeに変換して比較いたのでそのままのほうが見た目も良いのでは？）
という感じです。
よろしくお願いします！
> Fixes #13162 固定ページの並び順がおかしくなる

- lib/Baser/Plugin/Mail/View/Elements/mail_form.php
おっかけていったら、MailController.php の function submit での画像チェックのロジック調整の時に発生したバグみたいですね。
> fixes #13679 画像認証利用時のフォームテンプレートのバグを調整

- lib/Baser/Controller/Component/BcManagerComponent.php
管理画面のテーマ管理からの初期データ取込ではupdateSequenceされていたので、初期インストールのロジックの所に移植しました。
> fixes #13828 初期インストール時にPostgreSQLのsequenceの数値のデータにあわせてupdate

- lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
ajax error の場合は、jsTree 自体のnodeを削除する処理追加しました。
>     fixes #13837 create error の場合、delete_nodeで追加表示を削除

- lib/Baser/Controller/PagesController.php
- lib/Baser/Model/BcAppModel.php
- lib/Baser/Model/Content.php
とりえあず、ajax経由の方は修正できたので、送ります。
BcAppModel あたりに、validationErrors をため込んでいくロジック追加が
理想的かと思いますので(eventで呼び込みが増えても、エラーハンドリング周りのソースの改修がすくなくてすむ)、もしくは try,catchでやり直す。
いずれそちらに替えたいと思ってます。
必要なら、別途チケット未来向けにつくっておいてくれても大丈夫です。
>  fixes #13827 contents.title にvalidationを追加,ajaxからの登録で適切なエラーが出るように調整

- lib/Baser/View/SiteConfigs/admin/form.php
どうやら、ヘルプ文言は準備されていたのですが、jsで、nextで取得していたので
htmlの構成上取得出来ていなかったみたいです。
元々あった文章と新規の文章をマージして出力調整してみました。
> fixes #13475 GoogleMaps住所のヘルプを記載

- lib/Baser/Config/Schema/pages.php
- lib/Baser/Model/Datasource/DboSource.php
- lib/Baser/Plugin/Blog/Config/Schema/blog_posts.php
増やすために、MEDIUMTEXTを設定、
cakeschema の定義だと、text しか指定出来ないので、強引かもしれないが
after methodで、MEDIUMTEXT に型変換した。(alter table)
本来、after method は、CakeSchemaのコールバックで呼ばれる予定なのだが
baserCMSのオリジナル拡張(というより1系からの下位互換のため)で、コールバック
がうごいてない。(ここ追ってないので他の原因ならそこで修正した方がいいかと思います)
ちょっと強引だけど、createTableに成功して、スキーマファイルに after methodが
あれば呼び出すようにした。引数は、CakeSchemaのコールバックとあわせてるので
CakePHP3にしたときも大幅な改修はしなくて大丈夫と思われる。
全体的に強引な感じはぬぐえないので、とりあえず確認してもらえればと思います。
>   fixes #13943 固定ページ/ブログの本文の容量を増やしたい

- lib/Baser/Controller/ContentsController.php
- lib/Baser/Model/Content.php
- lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
/lib/Baser/webroot/js/admin/lib/jquery.bcTree.js [Line: 99]をコメントしています。
エラーメッセージ表示後、移動前の状態の描画に戻すためloadを走らせるとエラーメッセージの表示がすぐに消されてしまうためです。
確認ください。
> Fixes #14049 同一URLコンテンツが生成される問題の修正

- lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
tokenのコールバック前にリダイレクトしようとしてエラー表示がでてたので、
ajaxの非同期処理をここは禁止して同期処理とした。
>     fixes #14140 ゴミ箱から戻すときは、非同期処理を解除

- lib/Baser/Model/Content.php
ゴミ箱に入れる(update)する段階で、status,self_statusのカラム値をfalseに設定
これで、ゴミ箱から戻した時も、非公開で戻るようになり期待した動作となる
また、その他のゴミ箱周りのチケットもいくつか同時に解消しそうである。
> fixes #13895 ゴミ箱に入れる時に、status,self_statusをfalseにする

- lib/Baser/Controller/InstallationsController.php
#13828 の修正では、コアプラグイン及びプラグインに対して、有効でなかったので
step5の最後で、最終的にprimary key をupdateする処理を追加。
#13828は、処理の場所が、BcManagerComponent.php であり、別から呼ばれる可能性
が否定できないので処理はそのままにしています。
>     fixes #14474 初期データ登録でPostgreSQLの場合primary keyの重複が発生するので調整

- lib/Baser/Model/BcAppModel.php
> fix #14713 固定ページ並び替え時、複数ユーザーで同時に更新される場合に並び順が重複する

- lib/Baser/webroot/js/admin/libs/jquery.bcTree.js
コンテンツ管理内でアイテムの名前変更が失敗します。
AjaxURL生成で、文字列内に挟んであるJS変数が文字列になってしまいURLが正しく生成されていなかったため修正しました。
> 文字列のクオートが混在していて変数名が文字列に含まれてしまっていたためにコンテンツの名前変更が失敗する不具合を修正

- lib/Baser/Plugin/Blog/View/Elements/admin/blog_posts/index_row.php
#14947 管理画面のブログ記事一覧で、アイキャッチを使用するとカラムがずれて表示される
> fix #14947 管理画面のブログ記事一覧で、アイキャッチを使用するとカラムがずれて表示される

- app/Config/core.php
- lib/Baser/Config/bootstrap.php
cache engineにFileを指定した場合は、defaultでtrueが利用される。(※1)
Memcachedのserializeはtrueを許容しておらず (※2) Exceptionが発生するため全てのEnginでtrue or falseを登録するコードを除去しています。
※1 https://github.com/baserproject/basercms/blob/dev-4/lib/Cake/Cache/Engine/FileEngine.php#L75
※2 https://github.com/baserproject/basercms/blob/dev-4/lib/Cake/Cache/Engine/MemcachedEngine.php#L58
> fix #15977 キャッシュの指定に不要なoptionを除去

- lib/Baser/Controller/UsersController.php
フロント認証　異常挙動
フロント認証機能の仕様時に、管理ユーザーから運営ユーザー切替を行い、元のユーザーに戻ろうとすると、/users/login　にリダイレクトされてしまう問題の修正
> fix #16398 フロント認証　異常挙動の修正

- lib/Baser/Model/Behavior/BcUploadBehavior.php
> fix #16738 BcUploadBehaviorにexifが読めない画像ファイルを読ませるとwarningが発生する問題の修正

- lib/Baser/View/Helper/BcAppHelper.php
- lib/Baser/View/Helper/BcBaserHelper.php
BcBaserHelper::getLink() / BcAppHelper::url() の判別方法を同一にし、事項が増えたのでpregにしました。
ご確認おねがいします。
> fix #16838 baserが変換するURLにtel:protocolを追加

- lib/Baser/Controller/SitesController.php
SiteモデルのgetSiteListの仕様が変わったことが原因のようでしたので呼び出し元の引数を変更しています。
よろしくお願いします！
> fix #16749 サブサイト管理にてメインサイトが選択できない

- lib/Baser/Plugin/Mail/Controller/MailController.php
イベント等で書き換えや、メールフォームのemailフィールドを特殊な作り方をしないと発生しないですが、フォーム利用者宛は配信され、管理者宛でエラーが出ます。
取込検討お願いします。
> fix #16839 メールプラグインにてメールアドレスを複数指定した場合に発生するbugの修正

- lib/Baser/Plugin/Blog/Config/setting.php
- lib/Baser/Plugin/Blog/Model/BlogContent.php
/app/Config/setting.php にて下記を追加して上書き可能
$config['Blog'] = [
// ブログアイキャッチサイズの初期値
'eye_catch_size_thumb_width' => 2000,
'eye_catch_size_thumb_height' => 2000,
'eye_catch_size_mobile_thumb_width' => 600,
'eye_catch_size_mobile_thumb_height' => 600,
];
ご検討ください！
> fix #16894 ブログのアイキャッチ初期値override機能の提案

- lib/Baser/Plugin/Mail/Controller/MailController.php
メールフォームではローカル（ブラウザ）にキャッシュさせないヘッダ情報を送信するよう変更しました。
よろしくおねがいします！
> fix #17191 メールプラグインにてローカルキャッシュさせないHTTPヘッダの追加

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
- イベントに引っ掛けている箇所で、記事データ自体は参照できないため、参照できるようにするため
- 引き渡し順は、メソッドの並び順に合わせるため
ご検討よろしくお願いします。
> modify イベント Blog.Blog.beforeGetPostLink 内で、対象となるブログ記事データを参照できるようにするため

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
- ブログ記事のリンク表示の際は、beforeGetPostLink、afterGetPostLink を共通で通過するようにしておくため
> modify 前の記事、次の記事のリンク表示箇所が、getPostLink を通過するように調整

- lib/Baser/Plugin/Blog/Config/Schema/blog_posts.php
下記チケット対応分となります。
テーブル作成時のカラムの型をVARCHAR(30)からTEXTへ変更致しました。
http://project.e-catchup.jp/issues/17275
宜しくお願い致します。
> fix #17275 長いファイル名のブログアイキャッチ画像が保存できない対応

- lib/Baser/Model/Behavior/BcUploadBehavior.php
> PHP7.1でのCUIインストール時に文字列に対する配列アクセスの警告が出るのを修正

- Vagrantfile.default
プロビジョニング後、2回目以降の`vagrant up`で httpd が起動に失敗します（Windows環境にて発生）。
共有ディレクトリマウント前に httpd 起動を試みて失敗しているようなので、マウント後に再度 httpd を起動するよう追記しました。
レビューおねがいいたします。
> ホスト・ゲスト間の共有ディレクトリをマウントした後にhttpdを起動するように追記

- lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php
lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.phpの/archive/をarchive/に修正
> #17708 ブログ詳細のプレビューのURLが「ブログ名//archives/」になってしまう問題の修正

- lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogBaserHelperTest.php
- lib/Baser/Plugin/Blog/View/Helper/BlogBaserHelper.php
BlogBaserHelper::getBlogs()にオプションを追加
http://project.e-catchup.jp/issues/12056
公開記事数のカウントをBlogContent.post_countに追加
```
<?php var_dump($this->BcBaser->getBlogs('', ['postCount' => true])); ?>
array (size=2)
'BlogContent' => 
array (size=19)
'id' => string '1' (length=1)
'description' => string 'baserCMS inc. [デモ] の最新の情報をお届けします。' (length=65)
'template' => string 'default' (length=7)
'list_count' => string '10' (length=2)
'list_direction' => string 'DESC' (length=4)
'feed_count' => string '10' (length=2)
'tag_use' => boolean true
'comment_use' => string '1' (length=1)
'comment_approve' => string '0' (length=1)
'auth_captcha' => boolean true
'widget_area' => string '2' (length=1)
'use_content' => boolean true
'created' => string '2016-08-07 23:10:38' (length=19)
'modified' => null …
```
> fix #12056 ブログに公開している記事の総数を取得したい

- lib/Baser/Plugin/Mail/Model/MailMessage.php
以下のチケットの件になります。
http://project.e-catchup.jp/issues/17717
> fix #17717 メールフォームの「半角数字」バリデーションが動作しない

- lib/Baser/Test/Case/View/Helper/BcMobileHelperTest.php
- lib/Baser/Test/Case/View/Helper/BcPageHelperTest.php
BcMobileHelper/testAfterLayout testHeader追加です。
View　→　BcAppViewにできました。
BcPagesHelper/
testHeaderは実装できませんでした。
treeListは使われていない可能性があります。
> BcMobileHelper/testAfterLayout testHeader追加

- lib/Baser/Plugin/Mail/View/Elements/mail_input.php
バリデーションそのものの動作は正しい。マルチバイトでも問題ないと思われる。ただ表示がおかしく、全てのエラーが"必須項目です"と表示されてしまっていた。
修正後スクショ
・不正
・正
> fix #13621 メールフォームのEメールチェックのバリデーションが正しく動作しない

- lib/Baser/Model/Content.php
4.0.5のコンテンツ管理でルートフォルダの編集で「保存」を押すとエラー
該当箇所
[CORE/Baser/Model/Content.php, line 765]
if($data['Content']['parent_id']) {
変更後
if(!empty($data['Content']['parent_id'])) {
> #17839 コンテンツ管理でルートフォルダの編集で「保存」を押すとエラーの修正

- lib/Baser/webroot/js/admin/libs/jquery.bcToken.js
- lib/Baser/webroot/js/admin/site_configs/form.js
* ページ内のすべてのCSRFトークンの値を更新するように修正
* app/webrootにコピーされたものを修正しないと直らない。どうするか
> fix #17728 システム管理からメール送信テストを行った後にシステム設定を保存するとCSRFエラーが発生

- lib/Baser/Plugin/Blog/Model/BlogCategory.php
- lib/Baser/Plugin/Blog/Test/Case/Model/BlogCategoryTest.php
- lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php
- lib/Baser/Plugin/Blog/webroot/js/admin/blog_posts/form.js
* ブログカテゴリ名のヘルプのバルーンがダイアログ内で見切れていた（overflow:hidden)ので修正
* ブログカテゴリ名が重複禁止であることがわかりやすいように
* バリデーションの表記揺れ・間違いを修正
> fix #14132 [BLOG] 同一名称カテゴリ作成の回避

- lib/Baser/View/Elements/template_dump.php
> fix #12537 デバッグモード２で表示されるテンプレート一覧の表示の調整

- lib/Baser/View/Elements/admin/toolbar.php
> fix #17889 ブログ記事などの新規作成時のプレビュー画面のツールバー編集リンク先が「無効な処理です。」になる を解消

- lib/Baser/View/Elements/admin/toolbar.php
> fix #17888 代理ログイン時、フロント側サブサイトのツールバーで「元のユーザーに戻る」を押すとnotfoundになる を解消

- .travis.yml
travisCIの環境によってテスト結果が変わるので、明示的に
> ymlに[dist: precise]追加

- lib/Baser/Plugin/Mail/Model/MailField.php
入力チェックは行っていましたが、空白を許可していたので、許可しないように変更しました。
よろしくお願いします！
> fix #12497 メールフォームのフィールド名の前に半角空白が入ると保存できてしまうが、その後エラーが発生

- lib/Baser/Plugin/Mail/Model/MailField.php
> fix #12498 メールフォームでラジオボタンなどの選択リストを入力しないで保存するとWarningが表示される の解消

- lib/Baser/Config/theme/bc_sample/Elements/widgets/blog_monthly_archives.php
- lib/Baser/Config/theme/bc_sample/Elements/widgets/blog_yearly_archives.php
- lib/Baser/Plugin/Blog/View/Elements/admin/widgets/blog_yearly_archives.php
- lib/Baser/Plugin/Blog/View/Elements/widgets/blog_monthly_archives.php
- lib/Baser/Plugin/Blog/View/Elements/widgets/blog_yearly_archives.php
- lib/Baser/Test/Case/View/Helper/BcContentsHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
- lib/Baser/View/Helper/BcContentsHelper.php
ブログウィジェット 月別・年別アーカイブ改修
**1、ブログウィジェット 月別・年別アーカイブのリンクURLに現在のURLが入ってしまう問題の解消**
トップページなどで月別・年別アーカイブを使用すると、「ブログのURL/archive/」とならなければならないものが「index/archive/」となってしまう問題の解消
・IDとコンテンツタイプから　コンテンツのURL等を取得できるメソッド「getContentByID($id, $ContentType, $contValue)」を作成し、
　blog_monthly_archives.phpとblog_yearly_archives.phpにて使用する
> #17885 ブログウィジェット 月別・年別アーカイブのリンクURLに現在のURLが入ってしまう問題の解消

- lib/Baser/Controller/Component/BcAuthConfigureComponent.php
[fix] Authコンポーネントの設定箇所で認証プレフィックスにおけるパスワードハッシャーの設定を読み込むよう修正
http://project.e-catchup.jp/issues/18185
宜しくお願い致します。
> #18185 認証プレフィックス機能でパスワードハッシャーの設定が効いていない

- lib/Baser/Plugin/Mail/Controller/MailMessagesController.php
> fix #18274 メールフォームの受信一覧にてCSVダウンロードボタンが２つ表示される

- lib/Baser/View/Layouts/admin/default.php
ログイン状態でない場合キャッシュを利用せずフッターを表示するよう修正しました。
宜しくお願い致します。
> fix #18273 管理画面のフッターの表示が不正確

- lib/Baser/View/Layouts/admin/default.php
empty関数で中身が空かどうかチェックする場合、PHP5.5より前のバージョンでは、次のように関数の戻り値が空かどうかチェックするとエラーになる。
修正方法（）empty()の引数「BcUtil::loginUser()」を変数に入れる
> fix #18290 「管理画面のフッターの表示が不正確」の修正がphp5.5以上の記載方法のため、動作確認ができない

- lib/Baser/basics.php
以下の点について修正しています。
ご確認の程、よろしくお願いします。
http://project.e-catchup.jp/issues/18370
> fix #18370 テーマ用初期データダウンロードのデータにテーマ配下のプラグインのデータが含まれない

- lib/Baser/Plugin/Blog/Model/BlogPost.php
ブログ記事のプレビュー時動作を調整してみました。
http://project.e-catchup.jp/issues/18498
よろしくお願いします。
> fix #18498 ブログ記事プレビュー時、記事に紐付くブログカテゴリ、ブログタグ、ユーザ情報のみしか取得できない点を調整

- lib/Baser/View/Elements/admin/themes/index_list.php
管理画面のテーマ選択画面では、選択できるテーマには編集や削除できるボタンがついているが、「現在のテーマ」の下側にも編集ボタンが残っていた。編集ボタンを押すと、編集画面に飛ばされるが、「編集」や「削除」といったボタンが存在しないため、編集を完了することのできない仕様になっていた。なので、編集画面へのリンクがある編集ボタンを削除。
> 管理画面で現在のテーマから編集画面に飛ぶリンクを削除

- lib/Baser/webroot/js/admin/dblogs/ajax_index.js
- lib/Baser/webroot/js/admin/libs/jquery.bcDashboard.js
特定の環境において、ajaxの「POSTメソッド」+「送信データが空」のリクエストでphpファイルを読み込む際にDeprecatedエラーが発生するため、ダッシュボードのページロード処理の修正を行っています。
ご対応をよろしくお願いします。
> 特定の環境においてダッシュボードの読み込みに失敗する不都合を修正

- lib/Baser/Plugin/Blog/Model/BlogPost.php
取り込み検討、よろしくお願いします。
http://project.e-catchup.jp/issues/18620
> fix #18620 ブログ記事複製時、BlogPost、BlogTag キーのデータは作り直しているが、それ以外のキーのデータは破棄されている点の調整

- lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
[fix] カテゴリ以外の並べ替えの際にモデル名を明示してカラム名を指定するよう修正
フォーラムに寄せられた不具合となります。
http://project.e-catchup.jp/issues/18962
お手数ですがこちらご確認いただけたら幸いです。
> #18962 管理画面ブログ記事一覧でのSQLエラー

- lib/Baser/View/Helper/BcListTableHelper.php
> fix #19056 BcListTableHelper の rowClass メソッドで、指定したオプションが反映されない

- lib/Baser/Test/Case/BcAllAuthTest.php
- lib/Baser/Test/Case/BcAllTest.php
- lib/Baser/Test/Case/BcAllViewTest.php
- lib/Baser/Test/Case/Controller/Component/Auth/BcNoPasswordHaserTest.php
- lib/Baser/Test/Case/Controller/Component/BcAuthComponentTest.php
- lib/Baser/Test/Case/Controller/Component/BcContentsComponent.php
- lib/Baser/Test/Case/Controller/Component/BcEmailConponentTest.php
- lib/Baser/Test/Case/Controller/Component/BcGmapsComponentTest.php
- lib/Baser/Test/Case/Controller/Component/BcManagerComponentTest.php
- lib/Baser/Test/Case/Controller/Component/BcReplacePrefixComponentTest.php
- lib/Baser/Test/Case/View/BcAppViewTest.php
- lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php
- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/Test/Case/View/Helper/BcCkeditorHelperTest.php
- lib/Baser/Test/Case/View/Helper/BcContentsHelperTest.php
・前コミット追加分のAuthテストを動かすためにBcAllAuthTestファイルを追加
・BcAppViewファイル追加のためにBcAllViewTestファイルを追加
上２つを有効化のためにBcAllTestに上２つをテスト対象に追加
・Helperにテストメソッドとファイルを追加
> Helperに未実装テスト追加

- lib/Baser/Plugin/Blog/View/Elements/admin/searches/blog_posts_index.php
http://project.e-catchup.jp/issues/19261
こちらビュー側でエスケープしないようオプションを修正しております。
ご確認宜しくお願い致します。
> fix #19261 ブログ記事検索フォームのプルダウンメニュー特殊文字がエスケープされて表示される事象修正

- lib/Baser/Model/ThemeFile.php
テーマファイルの重複チェックの際に、重複する可能性のある対象ファイルのパスの生成が誤っていたため重複チェックが機能していなかった点を修正しました。
手動テストで重複チェックが正しく行われるようになったことを確認しました。
> テーマファイルの重複チェックが機能していなかったため修正

- lib/Baser/Test/Case/Model/ThemeFileTest.php
テスト用ThemeFileのデータ生成にextキー (拡張子) の情報が欠けていることが原因でテストが失敗していたため、extキーと値を追加しました。
併せて他に欠けていたキー・値 (parent、contents) についても念のため追加しています。
> ThemeFileTestのテスト用ThemeFileデータ生成に欠けていたキー・値を追加

- lib/Baser/Controller/Component/BcManagerComponent.php
- lib/Baser/Controller/PluginsController.php
■原因
テーマに梱包されたプラグインをインストールする際にプラグイン情報のキャッシュの削除を行なっていないため。
■変更内容
installPlugin() 内で clearAllCache() を使用してキャッシュの削除を行なっています。
それにともない、処理が重複する部分を削除しています。
> fix #19453 プラグインをフォルダ内に持つテーマに切り替えた際、プラグインが利用できない場合がある 問題を修正

- lib/Baser/Controller/FavoritesController.php
調整しましたので、取込検討をよろしくお願いします。
http://project.e-catchup.jp/issues/19456
> fix #19456 固定ページ編集画面でよく使う項目を編集して保存すると、処理が正常に終わらず管理画面が崩れる

- lib/Baser/Test/Case/Model/ContentTest.php
#837 からtestFindByType()がdataProviderを使用するように変更しました。
findByType()の結果を一時的に代入したあと、結果が取得できたかどうかで分岐させ、そのあとでassertEquals()にまとめることで対応できました。
@ryuring ご助言ありがとうございました。
> testFindByType()がdataProviderを使用するように変更

- lib/Baser/Test/Case/Model/ContentTest.php
ContentTest::testGetSiteRoot()がdataProviderを使用するよう変更しました。
あわせて異常系として$siteIDの入力に 'あ' なども追加しようと思い、空配列が返ってくることを期待しましたが、なぜかコンテントが取得できるので不思議に思ったところ、MySQLのクエリのWHERE句で、以下のような原因で 'あ' が0に変換されており取得できてしまっていたという学びがありました。
> MySQLでは、左辺と右辺の型が異なる場合、どちらかに合わせて（変換して）比較が行われる。
文字列と文字列であれば変換は発生しないので意図した通りの結果になるが、今回は左辺が文字列で右辺が数値になっている。この場合、MySQLでは左辺と右辺の両方を数値に変換してから比較を行う。今回のケースでは左辺には既存のレコードの値が入ってくるが、数字になり得ないもの（ aaaaa, bbbbb, aa033e など）が来た場合は全て0に変換されてしまう。
(引用: https://haushinka2dx.blogspot.jp/2012/09/mysqlvarcharint.html)
そのため異常系については追加しておりません。
> ContentTest::testGetSiteRoot()がdataProviderを使用するよう変更

- lib/Baser/Test/Case/Model/ContentTest.php
ContentTest::testGetUrlById()を追加しました。
テスト対象が呼び出すgetUrl()のテストで十分なテストデータの量のテストが行われているため、こちらのテストデータ量はもっと少なくてもいいかもしれません。
> ContentTest::testGetUrlById()を追加

- lib/Baser/Model/Content.php
- lib/Baser/Test/Case/Model/ContentTest.php
#846 に加え、テストがPostgreSQLにも対応できるよう$idが整数でなかった場合に空文字を戻すように変更しました。
> Content::getUrlById()をidが見つからなかったり整数でない値を渡した場合に空文字を戻すよう変更

- lib/Cake/Cache/Engine/FileEngine.php
Windowsでファイルハンドラが閉じられていない場合に、正常にキャッシュファイルの削除が行われないことがあります。
以下の、Cake側の変更をマージして修正しています。
ご確認よろしくお願いします。
https://github.com/cakephp/cakephp/commit/c45868e871ba889c158f583b6dc7afd7746dcfe4#diff-638fa6a7b897f6b0f1f07fb2b6282c88
> Windowsで正常にキャッシュファイルの削除が行われない場合がある問題を修正

- lib/Baser/Config/theme/bc_sample/Elements/mail_input.php
- lib/Baser/Config/theme/bc_sample/Elements/smartphone/mail_input.php
- lib/Baser/Controller/BcAppController.php
- lib/Baser/Plugin/Mail/View/Elements/mail_input.php
- lib/Baser/Plugin/Mail/View/Elements/mobile/mail_input.php
- lib/Baser/Plugin/Mail/View/Helper/MailfieldHelper.php
@gondoh 下記チケットの改善コミットです。
http://project.e-catchup.jp/issues/20256
問題としては、no_send オプションかつ、確認画面の際に、hidden タグの生成を行う仕様となっており、その際、マルチチェックボックスだと value に値が入るので処理に失敗している。
そもそもの仕様が間違っていたように思うので、判定文を除外しています。理由は以下のとおり。
- no_send オプションは、「表示しない」という事ではなく、「メールを送信しない」ということなので、確認画面では関係ない
- MailformHelper は、BcFreezeHelper を継承しているので、$freeezed での判定を用いなくても自動的に確認画面でhiddenタグに切り替わる仕様となっている。
間違うと先祖返りとなり得るコミットなのでレビューをお願いします。
> fix #20256 メールフォームで「マルチチェックボックス」フィールドを「メール送信しない」設定で利用すると不正なリクエストと判断される問題を改善

- lib/Baser/View/Helper/BcTimeHelper.php
説明
メールフィールド「和暦日付」を使用した際に、
選択肢平成1〜9年を選ぶと、確認画面で年の表示が消え、
書き直し画面に戻ると値が空になるため、
lib/Baser/View/Helper/BcTimeHalper.php 43行目の正規表現の判定を修正しました。
> fix #20448 メールフォーム　和暦で入力値が一桁だと確認画面で値が空になってしまう問題を改善

- lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php
シングルクォーテーション内に改行コードが含まれていたので、ダブルクォーテーションに書き換えています。
> ブログ記事を削除する際のアラートメッセージの改行が正常に表示されない問題を修正

- lib/Baser/Config/update/4.1.0/updater.php
- lib/Baser/Plugin/Mail/Config/Schema/mail_contents.php
- lib/Baser/Plugin/Mail/Config/update/4.1.0/alter_mail_contents.php
- lib/Baser/Plugin/Mail/Config/update/4.1.0/updater.php
- lib/Baser/Plugin/Mail/Model/MailContent.php
- lib/Baser/Plugin/Mail/Test/Case/Model/MailContentTest.php
- lib/Baser/Plugin/Mail/View/MailContents/admin/form.php
#882 #884 を受けて改めてプルリクエストを追加致します。
お手数ですが宜しくお願い致します。
※マージミス修正しております。
※安部さん変更分のスキーマ構造変更のスクリプトはメールプラグインのものでしたのでMailプラグイン側に移動しております。
> modify #20718 メールフォーム設定編集画面で「送信先メールアドレス」などに255文字以上入力できるようにしたい。

- lib/Baser/Config/theme/bc_sample/Elements/mail_input.php
- lib/Baser/Config/theme/bc_sample/Elements/smartphone/mail_input.php
- lib/Baser/Plugin/Mail/View/Elements/mail_input.php
- lib/Baser/Plugin/Mail/View/Elements/mobile/mail_input.php
- lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
グループ入力チェック設定とバリデーション設定を行なっているメールフィールドに、
バリデーションに通らない値を入力した場合に「必須項目です。」と表示される問題を修正しています。
処理としては、指定したgroup_validをもつメールフィールド全てのエラーをチェックし、表示するようにしています。
そのための、getGroupValidErrorsというヘルパーをMailformHelperに作成しています。
> メールフォームで、グループ入力チェック設定されているフィールドのエラーメッセージを調整

- lib/Baser/Config/setting.php
SSL化後のURLに変更しています。
一部の環境において、クレジットの取得に失敗する場合があるためです。
http://forum.basercms.net/modules/newbb/viewtopic.php?viewmode=flat&topic_id=3109&forum=5
> スペシャルサンクスの取得元URLを修正

- lib/Baser/Plugin/Blog/View/Blog/rss/index.php
- lib/Baser/Plugin/Blog/View/Blog/rss/mobile/index.php
以下の問題を見つけたため、修正のコミットをお届けします。
可能な際に取込検討を、どうかよろしくお願いします。
- enclosure のyj:caption属性が存在すると、フィードが正しく解釈されないケースがあるため（例: Firefox）
- yj:caption属性はYahooRSSの独自仕様のようで、本来は他の3つまでが正しい要素のため
> fix フィードが正しく出力されない点を修正

- lib/Baser/Model/Behavior/BcUploadBehavior.php
baserCMS4.1.0.1で既存アイキャッチ画像と同じファイル名のアイキャッチ画像を別のコンテンツ等で登録すると既存アイキャッチ画像のサムネイル画像が上書きされてしまう事象を確認しましたので修正しております。
http://project.e-catchup.jp/issues/21421
大変お手数お掛けし申し訳ございませんがご確認のほど宜しくお願い致します。
> fix #21421 既存アイキャッチ画像と同じファイル名のアイキャッチ画像を別のコンテンツ等で登録した際の不具合修正

- lib/Baser/Plugin/Mail/Controller/MailController.php
メールフォームにおいて、「ファイル」タイプのメールフィールドに送信されたファイルを、
送信者への自動返信メールに添付しないように変更を行いました。
理由としては、以下2点です：
スマートフォンに送られた場合、パケットを大量に使用してしまう恐れがある
ウィルス配布の踏み台にされる危険性がある
よろしくお願い致します。
> modify #21464 メールフォームの自動返信メールに、送信されたファイルを添付しないよう変更

- lib/Baser/Plugin/Blog/Model/BlogPost.php
気づいたので調整入れてみました。可能な際に取込検討よろしくお願いします。
http://project.e-catchup.jp/issues/21515
> fix #21515 ブログ記事を保存した際に、検索コンテンツのURLにスラッシュが2重で登録される

- lib/Baser/Controller/SearchIndicesController.php
検索結果の一覧ページ内の、サイト内検索のカテゴリにサブサイトのフォルダが表示される問題を修正しています。
（※キャッシュ有効時は再現しない場合があります。）
> サイト内検索のカテゴリにサブサイトのフォルダが表示される問題を修正

- lib/Baser/Config/theme/bccolumn/js/startup.js
スマホ表示時、右上のハンバーガーメニューをクリックした際に、画像が表示されなくなる問題を修正しています。
原因は、JS内で画像パスをルートパスで指定しているため、baserをサブフォルダにインストール際に正しいパス解決が行われないことでした。
ロゴのリンク先のURLをベースURLとして、画像の絶対パスを使用するように変更しています。
> サブフォルダにインストールした際にbcColumnのスマホ用メニューのアイコンが表示されない問題を修正

- lib/Baser/Controller/ContentsController.php
コンテンツ一覧でフォルダを移動した際に発生する不都合を修正しています。ご確認をよろしくお願いします。
□エラー現象
コンテンツ一覧で固定ページの入ったフォルダを、別のフォルダの中に入れたり出したりするとエラーメッセージが表示されます。
□原因
コンテンツ一覧でフォルダを移動した際、フォルダ内のページに対して、ページテンプレートや検索データを作成するために、リクエストが送られます。
その際に、移動前のページに対してリクエストが送られているため、404エラーが発生し、エラーメッセージが表示されるようです。
□対策
コンテンツの移動が発生した直後にキャッシュを消す処理を入れています。
> コンテンツ移動後にキャッシュを削除する

- lib/Baser/Event/ContentFoldersControllerEventListener.php
> fix #21732 コンテンツ一覧画面で、フォルダ階層を変えずに、上下移動した場合に、移動後のページの中身が表示されない問題を改善

- lib/Baser/View/Helper/BcTimeHelper.php
BcTimeHelper::convertToWarekiArray()のPHPDocを実装に合わせて更新しました。
メソッド内で引数にis_array()判定をしており、引数に配列も取れるようですが、判定後の処理を追うと、convertToSeirekiYear()を使用していることから、和暦を期待しているものと思われます。和暦から和暦への変換というのも妙だと思いましたが、何かしら必要な場面があるのだろうと思い、引数に和暦データを取れることもコメントしてあります。
> BcTimeHelper::convertToWarekiArray()のPHPDocを実装に合わせて更新

- lib/Baser/Plugin/Uploader/View/Elements/admin/uploader_files/index.php
ご確認よろしくお願いします。
http://project.e-catchup.jp/issues/21902
> fix #21902 アップロードファイル一覧ページで、ファイルを右クリックした際の削除メニューが表示されない問題を修正

- lib/Baser/View/Helper/BcFormHelper.php
http://project.e-catchup.jp/issues/21979
調整してみましたので、良かったら取込検討お願いします_(．．)_
原因、対策理由とチケット説明欄で考察してます
> fix マルチチェックボックス時のdivを外すオプション指定が効かない点を調整

- lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php
- lib/Baser/Plugin/Blog/View/Helper/BlogBaserHelper.php
- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
「ブログアカウント名」という4系では無くなった表現になっている箇所を「ブログのコンテンツ名」に変更しました。
よろしくお願いします。
> 「ブログアカウント名」という表現を「ブログのコンテンツ名」に変更

- lib/Baser/Plugin/Mail/Controller/MailController.php
こちらの件対応しております。
http://project.e-catchup.jp/issues/21985
お手数ですがご確認のほどよろしくお願いいたします。
> fix #21985 baserCMS4系でメールプラグインのindexアクションを実行すると500エラーが発生する事象対応

- lib/Baser/Plugin/Mail/Controller/MailController.php
メール送信完了時、管理者あてに送信されるメールのオプションにccを追加しています。
このオプションを追加すると、任意のプラグインのControllerEventListenerで以下の関数を定義することで、ccを設定することができるようになります。
```
public function mailMailBeforeSendEmail(CakeEvent $event) {
$Controller = $event->subject();
$Controller->dbDatas['mailContent']['MailContent']['sender_cc'] = 'cc@test.test';
return true;
}
```
理想的には、メールフォームの管理画面で「CC用送信先メールアドレス」を設定できるといいのですが、DBの変更が必要になってくるので、ひとまずオプションの追加のみ行っています。
> Mail.beforeSendEmailにてメール送信のオプションを設定できるようにする

- lib/Baser/Model/Page.php
案件で、固定ページを大量に作成する要件があって、
コピーした際に「説明文」がコピーできないのは困るとの指摘を受けました。
対象箇所
lib/Baser/Model/Page.php
743行目
'description' => ''
となっていて、明示的に空っぽにしてコピーするようになっている。
こちら、厳密には「description」が同じものがあってはいけないということはないが、
Google検索で問題が発生しないように
descriptionが入っている場合、descriptionの末尾に「のコピー」の文字をつけるように調整
> fix #22129 固定ページをコピーした際に、オプションの説明文がコピーできない問題を解決

- lib/Baser/View/Helper/BcCkeditorHelper.php
案件で発生
フォーラムでも同様の問題が発生 「固定ページの編集でFont Awesomeの<i>タグが消える」
CKEditorの仕様が問題
イベント処理でビューにJSを読み込ませて処理をすることもできますが
今後「Font Awesomeの<i>タグ」の使用頻度が増える可能性を考えて、コアも修正しても良いと思います。
> fix #22130 CKEditorが<i></i>を勝手に消してしまう問題を解決

- lib/Baser/Plugin/Mail/Controller/MailController.php
送信完了後にthanksページへ遷移する処理を入れています。
メールフォームの再入力画面と、メール送信完了画面のURLが両方ともsubmitのため、アクセス解析上で見分けがつかないためです。
> メール送信完了後にthanksページへ遷移する

- lib/Baser/Plugin/Mail/Controller/MailMessagesController.php
- lib/Baser/Plugin/Mail/Model/MailMessage.php
アドバイスを元に再調整入れてみました。
https://github.com/baserproject/basercms/pull/938#discussion_r207727397
可能な際に取込検討お願いします
http://project.e-catchup.jp/issues/22085
> fix #22085 グループ化されたメールフィールドの最後が「利用しない」設定となっているとき、HTMLの閉じタグが正しい構造で表示されないため調整

- lib/Baser/Model/Page.php
□問題点
システム管理者以外のアカウントで、コード欄を使用しているページを保存すると、すでにファイルに出力されているコードが消える
□期待値
システム管理者以外での固定ページ保存時に、コード欄の出力に対して影響を与えないこと
□再現方法
1. システム管理者アカウントで固定ページにテキストを入力
2. 運営者アカウントで該当固定ページを保存
-> システム管理者が固定ページに入力したテキストが出力ファイルから消える
□原因
システム管理者以外でページを保存した際のリクエストデータには、コード欄の内容が含まれておらず、そのデータをもとに固定ページの出力を行っているため
□修正点
固定ページ作成に使用するデータをリクエストデータではなく、DBから取得したデータに変更
http://project.e-catchup.jp/issues/22282
> fix #22282 システム管理者以外のアカウントで、コード欄を使用しているページを保存すると、すでにファイルに出力されているコードが消える問題を修正

- lib/Baser/Model/Behavior/BcUploadBehavior.php
□変更点
現在、ファイルをアップロードした際には、BcUploadBehaviorのbeforeSave()から呼び出されるdeleteExistingFiles()にて、既に存在するファイルを削除する処理になっています。
その際、新しくアップロードしたファイルの拡張子をもとに、既に存在するファイルを削除しようとしているため、表題の問題が発生します。
そのため、アップロードしたファイルの拡張子ではなく、DBに保存されているファイル名の拡張子をもとにファイルを削除するよう変更を行っています。
発生条件の詳細は以下のチケットに記載されています。
http://project.e-catchup.jp/issues/22274
> fix #22274 アイキャッチ設定済みのコンテンツに別の拡張子のファイルをアイキャッチに再設定した場合、旧ファイルが残ってしまう問題を修正

- lib/Baser/View/Elements/admin/list_num.php
□ 問題
現在の一覧表示件数の仕様として、10,20,50,100件でページネーションが設定されているため、ページをまたいで並び替えを行うことができないケースがあります。
件数が100件を超えた際に、101番目以降のデータを100番目よりも前の位置に移動することができません。
□ 対策
一覧表示件数の設定を 10, 30, 50, 100件とすることで解決できます。
> fix #22395 管理画面において、並び替えとページネーション機能を併用した際の不都合修正

- lib/Baser/Model/BcAppModel.php
- lib/Baser/Test/Case/Model/BcAppTest.php
> fix #22284 BcAppModel::expects() にて、再帰的な bind 定義を行うとエラーになる問題を改善

- lib/Baser/Controller/ThemeFilesController.php
ThemeFilesController::admin_view()で、viewVersにisWritableが存在しないためエラーが出る不具合を修正しました。
> ThemeFilesController::admin_view()でwarningが出る不具合を修正

- lib/Baser/Plugin/Mail/View/Elements/mail_input.php
以前のコミットで、td trのとじタグがグループフィールド以外で出力されなくなっていたようなので、
復活しました。
> fix #22461 メールフォームView　グループでないと閉じタグが出ない問題を解決

- lib/Baser/View/Helper/BcCkeditorHelper.php
CKEditorのツールバーにページ内リンク用のIDを埋め込むボタンを追加しました。
よろしくお願いします。
> fix #22463 CKEditorにページ内リンクでのアンカーボタンがない問題を解消

- lib/Baser/Model/BcAppModel.php
- lib/Baser/Plugin/Blog/Model/BlogPost.php
- lib/Baser/Test/Case/Model/PageTest.php
下記、２つの条件を満たす場合に限る
- BcApp.allowedPhpOtherThanAdmins が false の場合
- 運営ユーザーの場合
> 固定ページの本文、ブログ記事の概要・本文において、Javascriptを含められないバリデーションを追加

- lib/Baser/View/Helper/BcCkeditorHelper.php
案件で発生。
<i></i>の他に、<span></span>もCKEditorが勝手に消してしまう問題が残っていたので、
それを解決
> fix #22475 CKEditorが<span></span>を勝手に消してしまう問題を解決

- lib/Baser/Plugin/Mail/Model/MailField.php
- lib/Baser/Plugin/Mail/View/Helper/MaildataHelper.php
- lib/Baser/Plugin/Mail/View/Helper/MailfieldHelper.php
- lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
- lib/Baser/View/Helper/BcFreezeHelper.php
お世話になります。メールプラグインでフィールドを作成する際、スマホで使う「type="tel"」の入力フォームが作れなくて困ったので、選択できるようにしてみました。もっとスマートな実装方法があれば教えてください。。。
> メールプラグインのフィールドタイプに「電話番号（type='tel'）」を選べるようにした。

- lib/Baser/webroot/css/admin/login.css
ログイン画面の上部に、空白が表示される問題を修正しています。
□環境
Mac Chrome, Firefox
> ログイン画面上部の空白を削除

- lib/Baser/Model/Page.php
問題内容の詳細です。
http://project.e-catchup.jp/issues/22639
可能な際に、検討取込をお願いします。
> fix #22639 固定ページの複製時、複製先ページ名が50文字を超えるものとなる場合に、複製処理が完了しない点を修正

- lib/Baser/Model/ThemeConfig.php
テーマ設定で画像を削除する際に、サムネイルの画像のファイル名指定に拡張子の前の . (ドット) が足りず実ファイルが削除できていなかったため修正しました。
> 修正: テーマ設定で画像のサムネイルの削除が出来ていなかった

- lib/Baser/Plugin/Mail/Model/MailMessage.php
ファイルを選択しなかった場合もファイルサイズオーバーのメッセージが表示される問題を修正しています。
また、エラーの判別に定数を利用するよう変更しています。
ご確認よろしくお願いします。
> fix #22661 「ファイル」メールフィールドのファイルアップロードサイズ制限のバリデーションが誤っている

- lib/Baser/Controller/BcAppController.php
> fix #22607 サブディレクトリ設置時管理画面アクセスのドメインが異なった場合、誤ったリダイレクトが行われる問題の修正

- lib/Baser/Vendor/Imageresizer.php
lib/Baser/Vendor/Imageresizer.php の 圧縮レベル（quality）パラメータを指定できるようにしてみました。
（ https://d-project.backlog.jp/view/BGR-239 関連です ）
よろしくお願いいたします。
> fix #22721 JPEG画像をアップロードすると元画像より容量が大きくなる件の改善

- lib/Baser/Controller/SearchIndicesController.php
案件で発生
検索機能で、特定のブログの記事を検索する際に、
ブログのカテゴリで絞り込む機能はあるが、
ブログコンテンツで絞り込む機能が無いので追加したい。
lib/Baser/Controller/SearchIndicesController.php
185〜186行目付近　$data['SearchIndex']['f']　でコンテンツIDを指定して検索する箇所
```
$conditions['SearchIndex.rght <'] = $content['Content']['rght'];
$conditions['SearchIndex.lft >'] = $content['Content']['lft'];
```
こちらだと、該当するコンテンツの内容は検索結果に含まれないため
```
$conditions['SearchIndex.rght <='] = $content['Content']['rght'];
$conditions['SearchIndex.lft >='] = $content['Content']['lft'];
```
こうすることで、該当するコンテンツの内容も検索結果に含める。
※現時点で、コンテンツフォルダは検索結果に含まれないため、既存のコンテンツフォルダ内のページ検索結果は変わらない。
> fix #22732 検索機能で特定のブログ内の記事に絞って検索できない問題を解決

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
private functionをpublic function に変更しました。
（権藤さんのOKは頂いています。）
> fix #22753 BlogHelper NextLink・PrevLinkのgetメソッドがない問題を解決

- lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
- lib/Baser/Plugin/Blog/Model/BlogTag.php
- lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php
ブログタグの追加が許可されてない場合でも記事編集画面にタグ追加ボタンが表示される不具合修正
こちらご確認いただけますと幸いです。
http://project.e-catchup.jp/issues/22754
> fix #22754

- lib/Baser/Plugin/Uploader/Model/UploaderFile.php
アップローダープラグインで、ファイル削除に失敗していたので修正しています。
公開期間を設定していない場合にのみ発生していました。
ご確認よろしくお願いします。
http://project.e-catchup.jp/issues/22756
> アップローダープラグインで、アップしたファイルがフォルダから消えない問題を修正

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
既に取得しているURLをgetImg()の前にリターンさせるようにしています。
linkがtrueの場合でも、outputにURLを指定すれば、outputが優先されます。
> fix #22777 BlogHelper getPostImg()にもURLを出力する機能を追加したい問題を解決

- lib/Baser/Controller/BcAppController.php
この Pull-req では、BaserCMS の前段に Nginx のリバースプロキシを経由させる構成で、[ngx_http_proxy_module](http://nginx.org/en/docs/http/ngx_http_proxy_module.html]) を使ったキャッシュを実装した場合の、ログイン状態の時のキャッシュコントロールを実装します。
BaserCMS の管理画面は `/admin` から始まるため、URIベースの判定でキャッシュのコントロールが可能です。しかし、ログイン後のトップページや記事の参照時は、プロキシのレイヤでは未ログイン状態との判別が付かず Nginx の設定ベースによるキャッシュのコントロールができませんでした。
これによって、ログインしていない第三者がトップページ等を閲覧した際に、ログイン時に表示されるツールバーが表示されてしまいます。
そのため、ログイン状態では `Cache-Control` 等のHTTPヘッダを挿入することでこの課題を解決いたします。
HTTPヘッダの挿入内容については、  [`ajax` 時のキャッシュコントロール](https://github.com/baserproject/basercms/blob/dev-4/lib/Baser/Controller/BcAppController.php#L344-L350) と合わせています。
ログイン時は以下のように、HTTPヘッダが挿入されます。
未ログイン時は、通常動作と変更ありません。
ご確認のほど、よろしくお願いいたします。
> ログイン時はキャッシュしないようにHTTPヘッダを挿入する

- lib/Baser/Config/bootstrap.php
現在、baserの実際のバージョンとDBのバージョン値が異なる場合に、メンテナンス画面が表示されます。
その際、メンテナンス画面が表示された原因がどこにも記録されないので、エラーメッセージをログに出力するよう変更しています。
取り込んでいただけるとデバッグ時に大変助かりますのでよろしくお願いします。
> baserの実際のバージョンとDBのバージョン値が異なる場合にログを記録する

- lib/Baser/Model/Behavior/BcUploadBehavior.php
ブログ編集画面でアイキャッチのファイルの選択と削除を同時に行おうとするとエラーが発生するため、修正しています。
エラー
```
Warning (2): Illegal string offset 'name' [CORE/Baser/Model/Behavior/BcUploadBehavior.php, line 351]
Notice (8): Uninitialized string offset: 0 [CORE/Baser/Model/Behavior/BcUploadBehavior.php, line 351]
Notice (8): Undefined index: extension [CORE/Baser/Model/Behavior/BcUploadBehavior.php, line 946]
Notice (8): Array to string conversion [CORE/Baser/Model/Datasource/DboSource.php, line 2233]
エラー: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
```
> ブログ編集画面でアイキャッチのファイルの選択と削除を同時に行おうとするとエラーが発生する問題を修正

- lib/Baser/Plugin/Blog/webroot/js/blog_comments_scripts.js
フォーラムから不都合報告を頂きました。
https://forum.basercms.net/t/topic/109
jquery3系を使用した場合に、ブログをコメントする際の画像認証が表示されない問題を修正しています。
確認バージョン: 4.2.1-dev
> jQuery3系にした場合、blog_comments_scripts.jsでエラーが起き、画像認証が表示されない問題を修正

- lib/Baser/View/Helper/BcBaserHelper.php
fixes #1203
BcBaserHelper::getDescription() がトップページでサイト基本説明文を取得できない問題を修正しました。
`$this->request->params['Content']['site_root']` ではなく `isHome()` を利用してトップページかどうか判定するように変更しました。
ご確認よろしくお願いします。
> Fix #1203 :  BcBaserHelper::getDescription() がトップページでサイト基本説明文を取得できない問題を修正

- lib/Baser/Plugin/Mail/Model/MailMessage.php
・ファイルアップロードフィールドを利用
・PHPの設定値においてアップロード可能
・メールプラグインのファイルアップロードサイズを制限 [maxFileSize]
・ブラウザがMAX_FILE_SIZEを無視
サーバ上にファイルがアップロードされるがMAX_FILE_SIZEのエラーを取得できないため、システムエラーと判別。
> fix #1208 MailPluginのファイルアップロードサイズvalidationメッセージ修正

- lib/Baser/View/Users/admin/login.php
- lib/Baser/webroot/css/admin/contents.css
- lib/Baser/webroot/js/admin/users/login.js
ログイン画面の「アカウント名」「パスワード」の部分に文字を入力しても背景の文字が消えないため修正しています。
今まで、login.js内の、キー入力時に背景の文字を消す処理が動いていましたが、ログイン画面のhtml構造の変更により、動作しない状態になっていました。
ただ、jsに処理を任せるよりもinput要素に対してplaceholder属性を設定したほうが処理が軽いのでそちらの処理に変更しています。
これにより、ブラウザによっては背景の文字が微妙に中央からずれる問題も解決しています。
> ログインフォームに文字を入力しても背景の文字が消えない問題を修正

- app/webroot/theme/admin-third/Elements/admin/sites/form.php
- app/webroot/theme/admin-third/SiteConfigs/admin/form.php
- lib/Baser/View/Elements/admin/sites/form.php
- lib/Baser/View/SiteConfigs/admin/form.php
管理画面のサイト基本設定・サブサイト設定の、「サイト基本キーワード」と「サイト基本キーワード」のヘルプメッセージが古かったため、更新しています。
ご確認をお願いします。
フォーラムから指摘がありました。
https://forum.basercms.net/t/topic/145
> サイト基本設定・サブサイト設定のヘルプメッセージを調整

- app/webroot/theme/admin-third/css/admin/style.css
以下のissueに対応しています。
■issue
[フォーラム]ブログの編集画面でアップローダーを開くと、画像が折り返されず、画面内に収まらない
https://github.com/baserproject/basercms/issues/1214
■問題
flex要素の親要素がtable要素だった場合にIEで起きる不都合のようです。
https://stackoverflow.com/questions/31022747/flexbox-ie11-flex-wrap-wrap-does-not-wrap-images-codepen-inside
■変更
display: flexの指定を解除しています。
ChromeとIE11で確認しましたが、特に表示の違いは発生しませんでした。
> admin-thirdテーマのcssを調整

- lib/Baser/Config/theme/bc_sample/Layouts/default.php
フォーラムからの要望です。
https://forum.basercms.net/t/topic/145/3
bc_sampleテーマに、metaのキーワードとページ説明文が出力されると、サンプルテーマとして便利でないかとのご意見です。
見てみるとスマホ版だと出力されていましたが、PC版には出力されていませんでしたので追加しています。
ご確認よろしくお願いします。
> bc_sampleのmetaを追加

- lib/Baser/Controller/PagesController.php
固定ページ編集画面でnameを変更した際、メッセージに変更前のnameをもとにしたURLが表示されるので修正しました。
ご確認よろしくお願いします。
> ページ名を変更した際、メッセージに以前のURLが表示される問題を改善

- lib/Baser/Model/BcAppModel.php
- lib/Baser/Plugin/Mail/Model/MailMessage.php
- lib/Baser/Test/Case/Model/BcAppTest.php
・必須チェックで検証することとファイルサイズは個別にと判断して変更しています。
・フォームのinput[type=file]をjQueryで$(target).val("")してクリアするとIE11にて検証自体が落ちる問題の修正になります。
・post_max_sizeの検証を追加しています。
> validation用のBcAppModel::fileCheckをアップロードされたか否かを除外

- lib/Cake/Network/Email/CakeEmail.php
CakePHP3系では対応済み
https://github.com/cakephp/cakephp/commit/8099090c919e77bd6fc80958f4d2e765f7c41e69
よろしくおねがいします。
> fix #1043 受信メールで１行の文字数が多い時、文字化けが発生の改善

- lib/Baser/Controller/UsersController.php
管理画面自動ログイン用のCookieにhttpOnly属性を設定しています。
JSから該当cookieにアクセス出来なくなるため、セキュリティが向上します。
ご確認よろしくお願いします。
> 管理画面自動ログイン用のCookieにhttpOnly属性を設定

- lib/Baser/Plugin/Mail/Controller/MailController.php
- lib/Baser/Plugin/Mail/Model/MailField.php
- lib/Baser/Plugin/Mail/Model/MailMessage.php
- lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
- lib/Baser/View/Helper/BcFreezeHelper.php
下記の処理を追加いたしました。
1. 管理画面メールフィールド編集のタイプ項目にパスワード追加
2. フォーム凍結時にパスワードタイプのvalueをマスク表示
3. `convertToDb()` にてデータベース用のパスワードタイプのデータをハッシュ化
4. `_sendMail()` にてメール送信用のパスワードタイプのデータをマスク表示
> fix #1095 メールプラグインのメールフィールド編集にパスワードタイプ追加

- docker/docker-compose.yml.default
sync_volumeの設定にnocopyオプションがありませんでしたので追加しました。
ご確認よろしくお願いします。
参考:https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html
> docker-syncの設定にnocopyオプションを追加

- lib/Baser/Plugin/Mail/View/Helper/MaildataHelper.php
後方互換を考慮して、view側のヘルパー内で処理を完了しています。
どうしてもエスケープしたくない場合は、引数の$escape をfalse にしてください。
> fix #1268 メールプラグインのメール本文がエスケープされていない問題を解決

- lib/Baser/Plugin/Mail/Model/MailMessage.php
フォームのフィールド設定内、拡張入力チェックの日付チェックについて調整しました。
可能な際に見ていただけますとうれしいです(*_ _)人
https://github.com/baserproject/basercms/issues/1271
> fix #1271 メールフィールドのカレンダータイプで拡張入力チェックに「日付チェック」を利用時、必ず入力チェックに引っかかってしまうため

- lib/Baser/Plugin/Mail/View/MailMessages/admin/view.php
@ryuring 
@gondoh 
細かいビューの調整となります。
よろしくおねがいします。
> fix #1277 管理画面 受信メール詳細ページで、送信しないフィールドがグループ内にない場合、trが表示されてしまう問題を解決

- lib/Baser/Plugin/Blog/Model/BlogComment.php
- lib/Baser/Plugin/Blog/Test/Case/Model/BlogCommentTest.php
以下のissueの対応を行いました。
ブログのコメント表示時のエスケープについ https://github.com/baserproject/basercms/issues/1080
ブログのコメントに対して、入力時と出力時両方にエスケープが行われていたので、入力時のエスケープを削除しています。
ご確認お願いします。
> fix #1080 ブログのコメント表示時に二重にエスケープされた状態で表示される問題を改善

- lib/Baser/Lib/BcUtil.php
- lib/Baser/Model/Content.php
https://github.com/baserproject/basercms/issues/1015 の対応を行いました。
タイトルにタブを含むコンテンツを保存しようとすると、コンテンツ一覧の表示がおかしくなるので入力チェックを追加しています。
また、nameの方も同じく不都合が起きるので変換処理を入れています。
ご確認お願いします。
> fix #1015 タイトルにTabを含むコンテンツを作成すると、コンテンツ一覧に正しく表示されない

- docker/docker-compose.yml.default
WindowsでDockerを動かす際の設定を追加していますのでご確認をお願いします。
Docker for windowsでmysqlを使用する場合、権限の問題で"/var/lib/mysql"のマッピングができないので、Docker Volumeを使用する必要があるみたいです。
□関連フォーラム
> Dockerで環境構築を行ったが、MySQLに接続できない 
https://forum.basercms.net/t/topic/186
> docker-compose.ymlにwindows用の設定を追加

- lib/Baser/View/SearchIndices/search.php
以下のissueに対応しています。
> 無条件で検索したときに「 該当する結果が存在しませんでした。」となるのに違和感
> https://github.com/baserproject/basercms/issues/1157
`無条件であれば全ページ表示させる`かどうかの方針は決まっていないようですが、いったん違和感をなくす方向で改修を入れています。
ご確認お願いします。
> fix #1157 検索ワードが入力されていない際の表示文章を変更

- lib/Baser/Controller/PluginsController.php
- lib/Baser/View/Plugins/admin/form.php
以下のissueに対応しています。
> プラグインが想定するフォルダ名以外でインストールされた場合プラグインが正しく動作しない
> https://github.com/baserproject/basercms/issues/1158
プラグインインストール時に、以下の場合にはインストールできないように制限をかけています。
1. 既に同名のプラグインがインストール済
2. プラグインのフォルダが存在しない
3. プラグインのフォルダ名と、プラグインの設定ファイル内の`$name`が異なる
ご確認をお願いします。
> プラグインがインストール可能か判定を追加

- lib/Baser/Plugin/Mail/Model/MailField.php
正規表現の部分で
「|」をエスケープし、文字コードの指定を追加
> fix #1294 メールプラグイン選択リストで特定の文字で終わると文字化けを起こす問題を解決

- lib/Baser/Test/Case/View/Helper/BcCsvHelperTest.php
- lib/Baser/View/Helper/BcCsvHelper.php
BcCsvHelper::download() を文字列結合せずにoutput
> fix #1296 MailPluginのCSVダウンロードでメモリを消費する問題

- lib/Baser/Plugin/Blog/Model/BlogPost.php
- lib/Baser/Plugin/Blog/Test/Case/Model/BlogPostTest.php
BlogHelper::getPosts() 等でカテゴリ指定の条件を複数指定した際に、
指定した1つ目のカテゴリしか検索されない問題を改善しました。
BlogHelper::getPosts()から
BlogPost::_findCustomParams()経由で呼び出している
BlogPost::createCategoryCondition()内にて
Model::field()でカテゴリのIDを取得していますが、
field()ではfindによる検索結果の一番最初の行の値しか渡されないため、
カテゴリを複数指定しても、1つ目のカテゴリのみ指定している状態となります。
今回、find()で検索しHashでBlogCategory.idを取得という形に変更しております。
```
$this->Blog->getPosts('news', 3, array('category' => array('news', 'event')))
```
のような形式に対応できるようになりました。
> BlogPostの修正：カテゴリを複数指定して検索した場合に1つ目のカテゴリしか検索されない問題を改善。

- lib/Baser/Plugin/Blog/View/Helper/BlogBaserHelper.php
- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
@ryuring 
blogPostsで記事一覧を呼び出すときに、
elementに変数を引き渡しできるようにヘルパーに少し手を入れました。
お手数ですが、こちらの機能をマージしていただくことは可能でしょうか？
> fix #1315 blogPostsで呼び出すテンプレートに変数を渡したい要望を解決

- lib/Baser/Test/Case/View/Helper/BcContentsHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
- lib/Baser/View/Helper/BcContentsHelper.php
・[ BcContents] 存在判定をするヘルパーを用意　→　近いヘルパーと読み込み部分を共有
・[ BcBaser] 存在判定の結果のエラーを用意　→ findの発生回数を減らせるように、判定しないようにすることもできるようにした。
> fix #1317 固定ページをエレメントとして読み込む際にページの存在判定をして正しいエラーを返したい問題を解決

- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
既存のprotected function _getThemeImage()をpublicにして、
noimageオプションと　outputオプションを追加しています。
参照メソッドも書き換えています。
> fix #1319 テーマ設定で登録した画像を、表示側で使用したい問題を解決

- lib/Baser/View/Emails/text/installed.php
`Config::read('App.baseUrl')`がデフォルトで設定されていませんでしたので、使用しないようにしました。
また、urlを`topLevelUrl(false)`ではなく`$siteUrl`から取得するようにしました。
マージお願いします。
> fix #1327 インストール完了後のメールの管理画面urlにサブディレクトリを考慮するようにした

- lib/Baser/View/Emails/html/default.php
- lib/Baser/View/Layouts/Emails/html/default.php
現在、basercmsには有効なhtmlメールのテンプレートがなく、
```
//in Controller extends BcAppController
$this->sendMail($to,$subject,$viewVars,[
'format' => 'html'
]);
```
とするとcakeのデフォルトレイアウトが呼ばれてしまい、メールの末尾に`This email was sent using the CakePHP Framework, http://cakephp.org.`と挿入されてしまいます。
これはバグではなく、レイアウトも自作して指定すればcakeのシグネチャは出てきません。
必要性も含めてレビューのほどよろしくお願いします。
> htmlメールテンプレートのデフォルトを追加

- app/webroot/theme/admin-third/Elements/admin/blog_posts/index_row.php
新管理画面を使用した際に、
アイキャッチを登録していてもブログ記事一覧で表示されない問題がございました。
修正しておりますので、マージをお願いできますか？
> fix #1342 新管理画面のブログ記事一覧でアイキャッチが表示されない問題を解決

- lib/Baser/Plugin/Blog/Controller/BlogController.php
下記の処理を追加いたしました。
1. ブログタグアーカイブページでタグが存在しない場合404に遷移
2. ブログ投稿者アーカイブページで投稿者が存在しない場合404に遷移
2.のブログ投稿者の存在確認については[フォーラム](https://forum.basercms.net/t/topic/256/3)に要望がありましたので併せて実装いたしました。
また、`blogURL/archives/author/`と投稿者を指定せずにアクセスした場合の動きも修正しております。今までは記事一覧が表示されましたが、他のアーカイブページに合わせ404に遷移するようにしております。
> fix #1312 ブログタグアーカイブページでタグが存在しない場合404に遷移

- lib/Baser/Plugin/Blog/Controller/BlogController.php
- lib/Baser/Plugin/Mail/Controller/MailController.php
ブログコンテンツ・メールコンテンツのプレビュー時に、アイキャッチ画像に設定した画像が表示されない問題を修正しました。
以前マージいただいたプルリクエストは、固定ページのみの対応でしたので他のコンテンツにも対応しています。
https://github.com/baserproject/basercms/pull/1338
ご確認よろしくお願いします。
> fix #1321 コンテンツプレビュー時、アイキャッチ画像がプレビューで表示されない

- app/webroot/theme/admin-third/js/admin/widget_areas/form.js
- lib/Baser/webroot/js/admin/widget_areas/form.js
Issue: https://github.com/baserproject/basercms/issues/1246
ウィジェットをドラッグアンドドロップで追加した際に、input要素のIDは変更されているにも関わらず、それに対応するlabelのforが追従できていないので修正しています。
ご確認よろしくお願いします。
> fix #1246 ウィジェット管理 ウィジェット内のラジオボタンが押せない

- lib/Baser/Controller/SearchIndicesController.php
- lib/Baser/View/SearchIndices/search.php
https://basercms.net/search_indices/search?q=0
PHP の empty() は 0 に対して true を返すため、空の判定を修正しました。
> 0 で検索できない問題を修正

- lib/Baser/View/ContentLinks/view.php
https://basercms.net/content_links/view
パラメータ無しでアクセスする機会は少ないかと思いますが、
公開されている URL のため、リダイレクトの無限ループを修正しました。
> リンクページで無限ループが起きる問題を修正

- lib/Baser/View/BcAppView.php
https://basercms.net/index.rss
*.rss が存在しないアドレスにアクセスすると、
"Errors/rss" からビューを探すため、設定したテーマが反映されませんでした。
https://github.com/baserproject/basercms/blob/9af525297d0fc0f74bcce9d1c08eba4a685de912/lib/Baser/Config/routes.php#L135
に起因するエラー対応を修正しました。
> *.rss でエラー発生時、テーマが反映されない問題を修正

- app/webroot/theme/admin-third/Elements/admin/blog_comments/index_row.php
- lib/Baser/Plugin/Blog/View/Elements/admin/blog_comments/index_row.php
- lib/Baser/Plugin/Blog/View/Elements/blog_comment.php
第三者が入力するコメント投稿者名に HTML エスケープをかけていないため、任意のスクリプトが実行可能です。
投稿者名の例:
```
<script>alert(1)</script>
```
ブログと管理画面のコメント要素を修正しました。
> コメント投稿者名の XSS 脆弱性を修正

- lib/Baser/Controller/ContentFoldersController.php
https://basercms.net/content_folders/view
#1353 と同様の対応として、存在しない場合は 404 にしました。
> 存在しないコンテンツフォルダのレスポンスを NotFound に変更

- lib/Baser/Controller/PagesController.php
https://basercms.net/pages/display
func_get_args() が空でもリダイレクトしない状態でした。
https://github.com/baserproject/basercms/blob/dd44fa6e87cbea513059e4e48ae7ddd2bd85d10a/lib/Baser/Controller/PagesController.php#L283-L286
この辺りのブロックは CakePHP オリジナル通りなので、パラメータ無しの場合はリダイレクトを想定しているかと思うのですが、
https://github.com/baserproject/basercms/blob/dd44fa6e87cbea513059e4e48ae7ddd2bd85d10a/lib/Baser/Controller/PagesController.php#L279-L280
直前の preg_replace() で $urlTmp が `''` になり、explode() で $path が `['']` になります。
配列要素が常に 1 以上でリダイレクトすることがないため、意図した挙動になるよう修正しました。
> pages/display の引数解析を修正

- lib/Baser/Plugin/Blog/Controller/BlogController.php
ブログの `archives/tag` にいくつか問題があるため、修正しました。
* `archives/tag` のとき、count($pass) は 1 のため、`tag` というタグ名で find をしてしまう。
* `archives/tag/a/b/c` のとき、`a` ではなく `c` のタグ名で find をしてしまう。
* `archives/tag/a&b` のとき、指定のタグ `a&b` を HTML エスケープしてから find するため、一覧に表示されない。
HTML エスケープを処理の途中でかけたかった、とは考えづらいので、単純に過去の負債が残っていただけでは？と推測しています。$tag は最終的に以下で処理されるため、エスケープ漏れの心配もないです。
https://github.com/baserproject/basercms/blob/a53023c46999b7648ed22f84c100ffc36977e584/lib/Baser/View/Helper/BcBaserHelper.php#L393-L395
---
また、これらとは別に、タグに登録できる文字列に不都合な問題があります。
例えば、`%40` というタグの登録を許してしまうと、`archives/tag/%40` でアクセスした際、
`urldecode('%40')` の値を指定されたタグとして処理が進むため、一覧に表示されません。
タグのバリデーション変更やマイグレーションは、後方互換性に影響がでそうなため、この問題については認識しつつも、手をつけていません。取り急ぎ報告として。
> 記事一覧(タグ)の引数解析を修正

- lib/Baser/Plugin/Blog/Controller/BlogController.php
ブログの `archives/author` にいくつか問題があるため、修正しました。
内容は #1359 と同様です。
> 記事一覧(投稿者)の引数解析を修正

- lib/Baser/Plugin/Blog/Controller/BlogController.php
ブログの `archives/category` にいくつか問題があるため、修正しました。
内容は #1359 と同様です。
加えて、二重に URL エンコードしている問題も修正しました。
> 記事一覧(カテゴリ)の引数解析を修正

- lib/Baser/Plugin/Blog/Controller/BlogController.php
ブログの `tags/*` にアクセスした際、常に beforeFilter() で弾かれる状態だったため、
tags アクションが実行できるよう修正しました。
また、find の結果が変わってしまう問題のある HTML エスケープを除去しました。
> ブログの全体タグ一覧が表示されない問題を修正

- lib/Baser/Plugin/Blog/View/Elements/widgets/blog_calendar.php
https://basercms.net/news/archives/date//string/
「数値に暗黙変換できる文字列」の入力を前提としているため、tr タグを閉じられず、ブログカレンダーが崩れてしまいます。
https://github.com/baserproject/basercms/blob/430edc0c0bc2f4d2d434374e8f088fb5101379e6/lib/Baser/Plugin/Blog/View/Elements/widgets/blog_calendar.php#L129-L132
mktime() は不正な引数の場合、 `false` を返すため、$w の値が固定されて、tr の閉じタグが出力できません。ここに到達する前に、正常な引数になるように修正しました。
> ブログカレンダーが崩れる問題を修正

- lib/Baser/Plugin/Blog/Controller/BlogController.php
https://basercms.net/news/archives/date///19string
上記のような URL で、あらゆる年のあらゆる月の "19" 日の記事を出力するため、引数を制限しました。
なお、この項目では記事の存在しない日付だとしても「妥当な日付」であれば、404 にはしていません。
これは、既存の利用者が「明日」や「昨日」などのリンクを実装していた際、404 では影響がでてしまうと
考えたためです。
---
前段の修正で `archives/date` に対する問題は一時的に解消するのですが、
```php
$day = '19string';
```
で "19" 日の記事を取得できてしまうのは、別の箇所に問題を抱えており、
https://github.com/baserproject/basercms/blob/430edc0c0bc2f4d2d434374e8f088fb5101379e6/lib/Baser/Plugin/Blog/Model/BlogPost.php#L1017-L1021
ここで「文字列型」の $year, $month, $day を代入していることが原因です。
MySQL の YEAR(), MONTH(), DAY() は数値型を返すため、
MySQL  内で `'19string'` が `19` に暗黙的に変換されて、結果として "19" 日の記事が引っかかる状態です。
他方、SQLite では文字列同士で比較しているため、 ~~`'19string'` では "19" 日の記事は引っかかりません。~~
(訂正: $day は sprintf() の段階で変換されているので、MySQL と同様の結果です。SQLite の例としては、「`'2020string'` では 2020 …
> 記事一覧(日付)の引数解析を修正

- lib/Baser/Controller/ContentsController.php
- lib/Baser/Model/Content.php
- lib/Baser/Test/Case/Model/ContentTest.php
- lib/Baser/Test/Fixture/Model/Content/ContentIsMovableFixture.php
- 同階層におけるコンテンツとフォルダの同名を許容しない仕様に変更
- 「エイリアスを利用してメインサイトと自動連携する」となっているサブサイトの同階層の同名コンテンツをチェックする仕様に変更
> コンテンツの移動時のエラー判定を厳密化 fix #1375

- lib/Baser/Plugin/Blog/Controller/BlogCategoriesController.php
@ryuring 
取り急ぎ、
`&nbsp&nbsp&nbsp` ＝＞　`   ` に置き換えて正常に表示できるようにしております。
お手数ですが、ご確認の上、マージをお願いします。
> fix #1377 ブログカテゴリ一覧 子カテゴリの前の半角スペースがエスケープ文字で表示されてしまう問題を解決

- lib/Baser/Controller/BcAppController.php
http://trial.basercms.net/maintenance/setMessage/外部からログを書き込まれました。/0/1
外部から任意のログを書き込まれてしまう問題を修正しました。
上記 URL で書き込み後、管理側のダッシュボードで結果を確認できます。
過去のコミットを遡ると public と protected を二転三転しているようでしたが、
現在は機能が BcMessage に移行しているため、メソッドの権限を改めてご検討ください。
> 外部からログを書き込まれる問題を修正

- lib/Baser/Controller/BcAppController.php
下記の処理を追加いたしました。
1. インストールページで表示される404にテーマ適応
インストール済の状態でインストールページにアクセスすると `notFound()` となりCakeErrorControllerが呼ばれ、CakeErrorControllerの `berforeFilter()` で再度インストールページ用の処理に入ります。
CakeErrorControllerの `beforeFilter()` ではインストールページ用の処理に入らないよう条件を追加いたしました。
https://github.com/baserproject/basercms/blob/430edc0c0bc2f4d2d434374e8f088fb5101379e6/lib/Baser/Controller/InstallationsController.php#L107-L111
https://github.com/baserproject/basercms/blob/430edc0c0bc2f4d2d434374e8f088fb5101379e6/lib/Baser/Controller/BcAppController.php#L339-L343
> fix #1385 インストールページで表示される404にテーマ適応

- lib/Baser/Plugin/Blog/Controller/BlogController.php
Blog プラグインについて、CAPTCHA 認証を回避してコメント投稿できる問題が存在します。
表面上は BlogCommentsController の
https://github.com/baserproject/basercms/blob/430edc0c0bc2f4d2d434374e8f088fb5101379e6/lib/Baser/Plugin/Blog/Controller/BlogCommentsController.php#L304
を呼び出して処理しているのですが、
それとは別に BlogController にもコメント投稿機能が存在しており、
https://github.com/baserproject/basercms/blob/430edc0c0bc2f4d2d434374e8f088fb5101379e6/lib/Baser/Plugin/Blog/Controller/BlogController.php#L461
を通すと CAPTCHA 認証を回避してコメント投稿が成功します。
http://trial.basercms.net/news/archives/1 宛てに `data['BlogComment']` を送ることで確認できます。
別の方法としては、http://trial.basercms.net/news/add_comment/1 をクリックするだけでも無言のコメント投稿が確認できます。(こちらは BcAuth が効いているため、事前にログインが必要)
旧機能が残っていただけでは？と推測していますが、何らかの事情で add_comment() を継続するのであれば、このメソッドにも CAPTCHA 認証が必要かと思われます。
こちらではステータスを判断できなかったため、一旦コメントアウトで修正しました。
> CAPTCHA 認証を回避してコメント投稿できる問題を修正

- app/webroot/theme/admin-third/Elements/admin/uploader_files/index_row.php
> fix #1389【admin-third】アップローダーの設定にて、レイアウトタイプを「テーブル」にした場合、記事添付時に画像の説明文に「f」が設定される

- app/webroot/theme/admin-third/Elements/admin/mail_messages/index_list.php
- app/webroot/theme/admin-third/Elements/admin/mail_messages/index_row.php
> fix #1398 システム管理者以外でも受信メッセージの一括削除を可能に変更

- app/webroot/theme/admin-third/SiteConfigs/admin/form.php
#1397 についてです。
自動入力されてしまうフィールドの前に、ダミーのパスワード欄を用意することで対応しました。
なぜssl_urlについて自動入力されてしまうのか不明です・・・。
> fix #1397 admin-thirdの「WebサイトURL[SSL]」前に自動入力防止用のダミーフィールドを追加

- lib/Baser/Lib/BcSite.php
@ryuring 
先程の改修をコミットしています。
お手数ですが、ご確認の上、マージをお願いできますでしょうか？
> fix #1404 URLのクエリがセッションに保存されない問題を解決

- app/webroot/theme/admin-third/BlogPosts/admin/form.php
- lib/Baser/Plugin/Blog/View/BlogPosts/admin/form.php
http://trial.basercms.net/admin/blog/blog_posts/add/1
http://trial.basercms.net/admin/blog/blog_posts/edit/1/1
管理者でないユーザが記事を投稿する際、「作成者」の項目がエスケープされていない状態です。
`<script>alert(0)</script>` などがニックネームの記事を編集時、任意のスクリプトが実行可能なため、エスケープ処理を追加しました。
> 記事作成者名の XSS 脆弱性を修正

- lib/Baser/Plugin/Blog/View/Elements/blog_tag_list.php
> fix #1282 ウィジェット内ブログタグ一覧で表示するタグのリンク先がNotFoundになるため

- app/webroot/theme/admin-third/SiteConfigs/admin/form.php
- app/webroot/theme/admin-third/Sites/admin/edit.php
- lib/Baser/View/SiteConfigs/admin/form.php
- lib/Baser/View/Sites/admin/edit.php
> 管理画面でアラートに改行タグが表示される問題を改善

- lib/Baser/Model/Behavior/BcUploadBehavior.php
- lib/Baser/Model/Content.php
#1396 のアイキャッチ画像のファイルアップロードエラーのチェックを下記画面にも追加いたしました。
1. 固定ページ情報編集
2. ブログ設定編集
3. メールフォーム設定編集
4. フォルダ編集
5. エイリアス編集
6. リンク編集
> #1012 ブログ記事以外のアイキャッチ画像登録時にファイルサイズのエラーメッセージ追加

- lib/Baser/Controller/ContentFoldersController.php
- lib/Baser/Controller/ContentLinksController.php
- lib/Baser/Controller/ContentsController.php
- lib/Baser/Controller/EditorTemplatesController.php
- lib/Baser/Controller/PagesController.php
- lib/Baser/Controller/PluginsController.php
- lib/Baser/Controller/ThemeConfigsController.php
- lib/Baser/Controller/ThemeFilesController.php
- lib/Baser/Controller/ThemesController.php
- lib/Baser/Controller/ToolsController.php
- lib/Baser/Locale/baser.pot
- lib/Baser/Locale/eng/LC_MESSAGES/baser.po
- lib/Baser/Model/BcAppModel.php
- lib/Baser/Plugin/Blog/Controller/BlogContentsController.php
- lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
- lib/Baser/Plugin/Mail/Controller/MailContentsController.php
- lib/Baser/Plugin/Uploader/Controller/UploaderFilesController.php
下記の処理を追加いたしました。
1. POSTが `post_max_size` 超過で初期化されているかチェックする処理を追加
2. ファイルアップロード時に `post_max_size` 超過のエラーメッセージを追加
3. 言語ファイルにエラーメッセージを追加
> fix #1011 ファイルアップロード時にpost_max_size超過のエラーメッセージ追加

- lib/Baser/Plugin/Uploader/Controller/UploaderFilesController.php
アップローダープラグインで名前に「%」と「+」を含むファイルをアップロードすると画像が表示されなくなる問題を修正しました。
また、既存の処理だと記号は削除する動作になっていますが、その場合ファイル名が記号のみの場合にファイル名が空になる問題が発生するため、記号を「_」に置換するよう変更しています。
ご確認お願いします。
https://github.com/baserproject/basercms/issues/1384
> fix #1384 【アップローダー】名前に%を含むファイルをアップロードすると画像が表示されない問題を改善

- lib/Baser/Controller/BcAppController.php
BcAppControllerのsendMail()をシェル等から呼んだ時に$this->siteConfigが読めずに文字コードがISOになってしまい、送信したメールが文字化けしていました。
なので、文字コードのデフォルトをUTF-8に変更しています。
レビューよろしくお願いします。
> sendMail()のデフォルト文字コードをUTF-8に変更

- lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
http://trial.basercms.net/admin/blog/blog_posts/add/1
http://trial.basercms.net/admin/blog/blog_posts/edit/1/1
管理者でないユーザが記事を投稿する際、「作成者」を `input type="hidden" name=data[BlogPost][user_id]` の値で確定しているため、なりすまし投稿が可能な状態です。
管理者でない場合は、ログイン情報を参照するように修正しました。
> なりすまし投稿ができる問題を修正

- lib/Baser/Config/theme/bc_sample/Emails/text/mail_data.php
- lib/Baser/Config/theme/bc_sample/Emails/text/smartphone/mail_data.php
- lib/Baser/Plugin/Mail/Model/MailMessage.php
- lib/Baser/Plugin/Mail/Test/Case/Model/MailMessageTest.php
- lib/Baser/Plugin/Mail/View/Emails/text/mail_data.php
- lib/Baser/Plugin/Mail/View/Emails/text/mobile/mail_data.php
@gondoh @ryuring ご指摘、アドバイスありがとうございました。
https://github.com/baserproject/basercms/pull/1290#issuecomment-563830556
指摘内容を元に調整してきたので、可能な際に取込み検討よろしくお願いします。
> メールフォームのテキストタイプフィールドにhtml改行タグを入力すると、通知メール内に改行が反映されるため調整

- lib/Baser/Plugin/Mail/Model/MailMessage.php
案件で発生。
フリガナの入力の際に姓・名の間にスペースを入れてもバリデーションが通るようにしたい。
例）タカヤマ タロウ
（現在はエラーになります。）
対応内容
正規表現のカナチェックに
・「 」（半角スペース）
・「　」（全角スペース）
を追加
> fix  #1514 【メール】全角カタカナチェックの際にスペースも許可したい問題を解決

- lib/Baser/Plugin/Blog/Model/BlogCategory.php
- lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php
下記Issue対応しました。
https://github.com/baserproject/basercms/issues/1496
> 【ブログ】ブログカテゴリごとの記事数を表示した際に親カテゴリの記事数が子カテゴリの記事数の合計にならない問題を修正 #1496

- lib/Baser/Plugin/Mail/Controller/MailFieldsController.php
可能な際に取り込み検討いただけるとうれしいです。
issue内容はこちらです。
https://github.com/baserproject/basercms/issues/1526
> fix #1526 メールフォームの受信データをcsvダウンロードした際に、並び順が受信日時降順となっていない点を調整

- app/webroot/theme/admin-third/Elements/admin/content_fields.php
@gondoh 
@ryuring 
お手数ですが、ご確認の上、マージお願いできますでしょうか？
> fix #1536 コンテンツ編集画面のURL表示のリンクの箇所がエスケープされている問題を解決

- lib/Baser/Config/theme/bc_sample/Elements/google_maps.php
- lib/Baser/Config/theme/bc_sample/Elements/smartphone/google_maps.php
- lib/Baser/View/Elements/google_maps.php
- lib/Baser/View/Elements/smartphone/googlemaps.php
フォーラムのトピック
> サイト名にシングルクォートを使えるようにして欲しい
> https://forum.basercms.net/t/topic/440 
の修正です。レビューお願いいたします。
> サイト名・GoogleMaps住所にシングルクオートが含まれているときの表示不具合を修正

- lib/Baser/View/Helper/BcContentsHelper.php
@ryuring 
該当問題の修正にて
lib/Baser/View/Helper/BcContentsHelper.php
getFolderLinkedUrl()
の、サブサイトのエイリアスの判定に $urlarrayの最初とサブサイトのエイリアスが同じではないことを条件として追加しました。
ご確認の上、マージをお願いできますでしょうか？
> fix #1538 サブサイトのコンテンツ編集画面のリンクURLがおかしくなる問題

- lib/Baser/Plugin/Blog/Model/BlogPost.php
https://github.com/baserproject/basercms/issues/1524
こちらの件対応しておりますのでお手数ですがご確認ください。
`'allowEmpty' => true`
が設定されているため空登録が可能になっているようでした。
以上、よろしくお願いいたします。
> fix #1524 投稿日時必須チェック不具合修正

- lib/Baser/Controller/SearchIndicesController.php
実際に使用する場合、
/element/site_serch_form.php などで
１，ブログコンテンツのリストを呼び出し
`$blogContents = $this->BcContents->getTree($this->BcContents->getSiteRootId($siteId), null, ['type' => 'BlogContent']);
$blogs = [];
foreach ($blogContents as $blogContent) {
$blogs[$blogContent['Content']['id']] = $blogContent['Content']['title'];
}
`
２，検索の絞り込み条件に追加することができます。
`	<?php if (!empty($blogs)) : ?>
<?php echo $this->BcForm->label('SearchIndex.c', __('ブログ')) ?><br>
<?php echo $this->BcForm->input('SearchIndex.c', ['type' => 'select', 'options' => $blogs, 'empty' => __('指定しない'), 'escape' => false]) ?><br>
<?php endif ?>
`
> fix #1553 【検索】ブログを指定して記事を検索する機能が欲しい問題を解決

- lib/Baser/Config/theme/bc_sample/Elements/mail_form.php
bc_sample テーマのレスポンシブ対応時にメールフォームの動作に必要なクラス名が消えていたので該当箇所を戻しました。
（書き直すボタンを押すとそのまま送信の動作になってしまっておりました）
よろしくお願いいたします。
> fix bc_sample テーマのメールフォームの書き直すボタンが動作していない件を修正

- app/webroot/theme/admin-third/js/admin/libs/jquery.bcToken.js
- lib/Baser/webroot/js/admin/libs/jquery.bcToken.js
ブログ記事のタイトルに `/` が入る場合、削除時のアラートに`\/` と表示されている問題の改善を行いました。
ブログ記事を削除する際には、削除ボタンに submit-tokenクラス がついている関係で、confirmイベントを書き換える処理が実行されます。
この、confirmのメッセージ取得後の変換処理が原因で、`/` が `\/` として表示されてしまっていました。
もともとconfirmのイベントはJSONとしてHTMLに出力されます。
https://github.com/baserproject/basercms/blob/dev-4/lib/Cake/View/Helper.php#L553
これに合わせて、メッセージ表示時の変換もJSONとして処理するように変更を行いました。
ご確認お願いします。
> ブログ記事のタイトルに「/」が入る場合、削除時に「\/」と表示される問題を改善

- lib/Baser/Controller/FavoritesController.php
管理画面でお気に入りを削除する際に「サーバーでの処理に失敗しました。」と表示される問題の修正を行いました。
ご確認お願いします。
> 管理画面 お気に入り削除時のエラーを改善

- app/webroot/theme/admin-third/BlogCategories/admin/index.php
アラート内の改行が`\n`として表示されていたので調整しています。
ご確認お願いします。
> 管理画面 ブログカテゴリ一覧 カテゴリ削除時のメッセージを調整

- lib/Baser/Model/Page.php
ini_set('memory_limit ', '-1');
memory_limitの後ろの不要なスペースを削除しました。
> fix #1593 固定ページの読込時、書出時に処理が止まらないように調整されているはずが、値が適用されていない問題を解決

- lib/Baser/Plugin/Blog/Model/BlogTag.php
- lib/Baser/Plugin/Blog/Test/Case/Model/BlogTagTest.php
- lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php
- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
再挑戦です。可能な際に取込み検討お願いします。
- issueはこちら https://github.com/baserproject/basercms/issues/1280
- travis-ci の結果はこちら https://travis-ci.org/github/materializing/basercms/builds/751927334
> #1280 ブログのタグアーカイブで、閲覧中のブログタグ情報をビュー側で取得する機能を実装

- app/webroot/theme/admin-third/__assets/css/components/_update-log.scss
- app/webroot/theme/admin-third/css/admin/style.css
issueはこちらです。 https://github.com/baserproject/basercms/issues/1607  
> fix #1607 admin-third利用時「最近の動き」の表示テキストが折り返して表示されない点を修正

- lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
issueはこちらです。 #1609
引数, $lastTextに文字列を設定且つ本文の長さが$cutより大きい際に最後に文字列が追加される仕様となっております。
> fix : #1609 BlogHelper::getPostContentで、文字数をカットした際に最後に「・・・」等の文字列を挿入できるよう修正

- lib/Baser/Plugin/Mail/Controller/MailMessagesController.php
ゴミ箱に入っているメールフォームの受信一覧にアクセスすると404になるよう変更しております。
> fix #1616 削除した（ゴミ箱に入れた）メールフォームの設定画面や受信一覧が閲覧できる

- lib/Baser/View/Elements/crumbs.php
- lib/Baser/View/Helper/BcBaserHelper.php
パンくずリストまわりの修正です。
``<li>...</li>`` 内で改行が入るとブラウザでの表示時に意図しない空白が入ることがあるので、1行で記述するようにしました。
レビューお願いいたします。
> BcBaserHelper::crumbs() で onSchema が true の時、ソースの改行に起因する空白が入るのを回避

- lib/Baser/Plugin/Mail/Model/MailMessage.php
・dev-4とのコンフリクトを解消
・半角英数以外で「-_@.*+」を許可
> fix #1629 メールフォーム emailチェックで、全角文字がバリデーションを通過してしまう問題を解決

- lib/Baser/Config/Schema/dblogs.php
DBのnameカラムを
varchar(255) → text 型に変更
> fix #1638 ブログ記事のタイトルを255文字にして保存しようとすると500エラーになる問題を解決

- app/webroot/theme/admin-third/Elements/admin/blog_posts/index_list.php
issue https://github.com/baserproject/basercms/issues/1643 で挙げた点を解消しました。  
> fix #1643 管理側ブログ記事一覧画面のBcListTable->dispatchShowHead()の記述場所が間違っている点を修正

- lib/Baser/Plugin/Blog/Model/BlogCategory.php
Treeビヘイビアを使用している場合、デフォルトの並び順はidよりもlftを参照したほうが自然なので変更しています。
ご確認よろしくお願いします。
> ブログカテゴリ取得時のデフォルトの並び順を変更

- lib/Baser/Plugin/Mail/Config/Schema/mail_fields.php
- lib/Baser/Plugin/Mail/Model/MailField.php
こちら、案件ベースで発生しており、
現状では$this->Mailform->control()で出力された内容を置換して設置する必要があるため、
対応が必要です。
・長過ぎるclassにも対応できるように255文字くらいまで増やす必要がある。
・バリデーションの調整
・DBカラムの調整
> fix #1654 メールフィールド　区切り文字が20文字以内では、classなどがつけられない問題を解決

- lib/Baser/Controller/ThemesController.php
https://forum.basercms.net/t/topic/607
上記の件です。よろしくお願いします。
> fix #1656 テーマ用初期データダウンロード時のメモリー制限を無効にする

- lib/Baser/View/Helper/BcTimeHelper.php
ご確認お願いします。
対象issue: https://github.com/baserproject/basercms/issues/1658
> fix #1658 【メール】和暦フィールドの年だけ選択している状態で、バリデーションエラーが発生すると選択した年が現在の年になる

- app/webroot/theme/admin-third/__assets/css/components/_notification.scss
- app/webroot/theme/admin-third/css/admin/style.css
- lib/Baser/Controller/PagesController.php
https://github.com/baserproject/basercms/issues/1651 を改善しました。良かったら可能な際に取込み検討お願いします。  
修正前の画面はissueに貼ってます。  
修正後はこちら。
> fix #1651 セッションメッセージの表示テキストが折り返して表示されないため修正

- app/webroot/theme/admin-third/js/admin/startup.js
issue: https://github.com/baserproject/basercms/issues/1633
HTML上で、ヘルプアイコンのすぐ隣にヘルプテキストが存在しないとヘルプテキストが表示されない状態でした。
ビュー側を調整して隣になるようにヘルプテキストの位置を変更しようと思ったのですが、表示の崩れが発生する場合がありました。
ですのでJS側を調整しています。
ご確認お願いします。
> fix #1633 【システム】管理画面において、バリデーションエラーが発生した際にヘルプテキストが表示されない場合がある

- lib/Baser/Plugin/Mail/View/Mail/default/confirm.php
- lib/Baser/Plugin/Mail/View/Mail/default/index.php
- lib/Baser/Plugin/Mail/View/Mail/smartphone/default/confirm.php
- lib/Baser/Plugin/Mail/View/Mail/smartphone/default/index.php
- lib/Baser/View/Layouts/mypage/default.php
リンク切れが原因で500エラーになる件、の元の件です。
マージよろしくお願いします。
既存の案件を修正する場合は、サーバ上のjquery-ui.min.cssをui.all.cssにリネームするのが
簡単・安全かなと思います。
> fix #1640 デフォルトテンプレート内で指定しているcssのパスがリンク切れ

- lib/Baser/Plugin/Blog/Model/BlogPost.php
issueはこちらです。 https://github.com/baserproject/basercms/issues/1690
良かったら可能な際に取込検討お願いします。
> fix #1690 ブログ記事にブログタグを付与して更新した直後、ブログタグアーカイブの記事一覧に記事が表示されない動作を調整

- lib/Baser/Model/Behavior/BcUploadBehavior.php
アップロード時のチェックでファイルサイズ0かどうかでチェックしている箇所を、アップロードエラーの有無でチェックするように変更しました。
よろしくお願いします！
> fix #1664 Uploaderで0バイトのファイルをアップするとリンク先が ajax_image//midium になる不具合を修正

- app/webroot/theme/admin-third/Elements/admin/dblogs/index_list.php
- lib/Baser/View/Elements/admin/dblogs/index_list.php
issueはこちら。 https://github.com/baserproject/basercms/issues/1708
調整しましたので取込み検討お願いします。
> fix #1708 管理側「最近の動き」が0件のとき一覧画面の表示が崩れている動作を修正

- app/webroot/theme/admin-third/js/admin/dblogs/ajax_index.js
- lib/Baser/webroot/js/admin/dblogs/ajax_index.js
「最近の動き」にデータが存在しないとき、常に処理失敗のアラートメッセージを表示する動作となっているのを修正しました。
取込み検討お願いします。
> fix #1706 「最近の動き」に1件もデータが存在しない場合に「処理に失敗しました。」メッセージが表示される動作を修正

- lib/Baser/View/Helper/BcFormHelper.php
フォームでマルチチェックボックスを使用している場合に、確認画面から入力画面・送信画面に遷移する際にセキュリティエラーが出る場合があるので修正しています。
■発生条件
- マルチチェックボックスが使用されている
- メールのビューで `$this->Mailform->control` を実行する前に ` $this->Mailform->label` や `$this->Mailform->value` が使用されていない
■問題
- BcFormHelperから呼び出す`_secure()`は引数でフィールド名が指定されていない場合、`entity()`からフィールド名を取得する
- ここで正しいフィールド名を取得できないと、その後の処理でセキュリティエラーが発生する原因になる
- マルチチェックボックス以外では、`_secure()`を実行する前に`_initInputField()`経由で`setEntity()`を呼び出し、フィールド名を設定している
- マルチチェックボックスの場合には`_initInputField()`を実行する前に`_secure()`を実行している
■修正内容
- BcFormHelperの`hidden()`内に`setEntity()`の実行処理を追加
> 【フォーム】マルチチェックボックスを使用しているとエラーがでる場合がある問題を改善

- lib/Baser/Plugin/Mail/Model/MailField.php
- lib/Baser/Plugin/Mail/Model/MailMessage.php
メールフォームのバリデーションについて、下記の変更をしました。
Eメールチェックについて、
- 全角文字を半角に変換
- 認められない文字を明確に指摘する。例: 「*はEメールに利用できません。取り除いてください。」
- @がない場合指摘する。例:「@が必要です。」
全角カタカナチェックについて、
- 全角ひらがなは全角カタカナに変換
- 半角カタカナは全角カタカナに変換
- 認められない文字を明確に指摘する。例: 「ひらがなでない『漢字ABC』は〇〇に利用できません。ひらがなに変更してください。」
- 変換できるのであれば自動で変換（確認ページで）
全角ひらがなチェックについて、
- 全角ひらがなは全角ひらがなに変換
- 半角カタカナは全角ひらがなに変換
- 認められない文字を明確に指摘する。例: 「カタカナでない『漢字ABC』は〇〇に利用できません。ひらがなに変更してください。」
- 変換できるのであれば自動で変換（確認ページで）
> #1700　【フォーム】Eメールチェックの機能追加 #1700

- lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
- lib/Baser/View/Helper/BcFreezeHelper.php
アクセシビリティ向上のため、フィールドタイプが「email」の場合のinput typeを「email」に変更しました。
> 【フォーム】フィールドタイプ「Eメール」の場合、input typeを「email」に変更 #1714

- app/Config/Schema/sessions.php
- app/Config/Schema/sessions.sql
- app/Config/session.php
- lib/Baser/Controller/UploadsController.php
- lib/Baser/Model/Behavior/BcUploadBehavior.php
MySQLの場合はDBのカラムをバイナリにしたらそのまま動作してましたが、PostgreSQL/SQLiteが動作していない感じでしたので、セッションに保存時にbase64エンコードして保存、読み出し時にデコードするようにしました。
よろしくおねがいします。
> fix #1661【システム】セッションをDBに保存する場合のファイル関係の不都合を解消

- lib/Baser/Config/theme/bc_sample/Emails/text/mail_data.php
- lib/Baser/Plugin/Mail/View/Emails/text/mail_data.php
> fix #1196【メール】テキストエリア項目について、未入力にて送信した場合送信メールに見出しが表示されない件の修正

- lib/Baser/Plugin/Mail/webroot/js/admin/mail_fields/form.js
テキストエリアの時もmaxlength値の設定項目を使えるようにしました。
よろしくお願いします！
> fix #1649 メールフォーム・テキストエリアで6,553,500文字入力後「確認画面へ」ボタンを押下するとエラー画面へ遷移する問題の解消

- lib/Baser/Plugin/Mail/Model/MailField.php
メールフィールドの各数値項目にバリデーションを追加しました。
各DBのINTEGER最大桁数は下記のとおりだったので上限を9桁（999,999,999）にしています。
MySQL int(11)
4bytes 
-2,147,483,648〜2,147,483,647
https://dev.mysql.com/doc/refman/8.0/ja/integer-types.html
PostgreSQL integer
4bytes 
-2,147,483,648〜2,147,483,647
https://www.postgresql.jp/document/12/html/datatype-numeric.html
SQLite INTEGER
1, 2, 3, 4, 6, or 8 bytes
-9,223,372,036,854,775,808〜9,223,372,036,854,775,807
https://www.sqlite.org/datatype3.html
※ 操作誤ってコミットしたり消してしまったので再度プルリクします、、、
> fix #1692【フォーム】フィールド設定にて、「表示サイズ」に数値以外を入力するとシステムエラーになる件の修正

- app/webroot/theme/admin-third/UploaderFiles/admin/ajax_image.php
よろしくおねがいします！
前回の修正について、サブディレクトリ上に設置するとパスがミスってる問題も合わせて改善となります。
> fix #1744 アップローダーで誤ったURLが表示される問題の改善

- lib/Baser/View/Helper/BcWidgetAreaHelper.php
ウィジェット内のエレメントがすべてキャッシュされる動作になっていたので、
デフォルトはキャッシュしないように変更しました。
よろしくおねがいします。
> fix #1045 【ウィジェット】ローカルナビゲーション出力で、表示とリンクが別の内容になる件を修正

- README.md
The link to the baserCMS Users Manual was broken, so it has been fixed.
> Fixed a broken link in the README.md.

- README.md
baserCMS Users Manual のリンクが切れていたので、修正しました。
> 修正 README.md のリンク切れを修正

- lib/Baser/Plugin/Mail/Model/MailMessage.php
issueはこちらです。 https://github.com/baserproject/basercms/issues/1770  
フォーム複製時、受信用テーブルに不足フィールドが発生することがあるため、動作調整を入れてみました。  
よかったら取込み検討お願いします。
> fix #1770 メールフィールドの数が多い場合に、受信データ用テーブルのフィールドが不足状態で作成されるケースが発生する点を改修

- lib/Baser/View/Helper/BcFormHelper.php
> fix #1772 【メールフォーム】フィールドをマルチチェックボックス→自動補完郵便番号の順にすると郵便番号自動補完が動作しない問題を修正

- lib/Baser/Plugin/Mail/Event/MailControllerEventListener.php
コンテンツ管理でメールフォームコンテンツをゴミ箱に入れた場合、ゴミ箱からもどした場合、および、コンテンツ管理の右クリックメニューからの公開・非公開の変更時にサイト内検索データが変更されない件を修正しました。
よろしくお願いいたします。
> fix #1754 ゴミ箱に入れたメールフォームコンテンツがサイト内検索の検索結果に表示される問題を修正

- lib/Baser/Plugin/Blog/Event/BlogControllerEventListener.php
コンテンツ管理でブログコンテンツをゴミ箱に入れた場合、ゴミ箱からもどした場合、および、
コンテンツ管理の右クリックメニューからの公開・非公開の変更時に
サイト内検索データが変更されない件を修正しました。
ただ、ブログ記事は１件づつ検索データを再作成しているので、
もっと効率いいやり方があればアドバイスいただければと思います。
よろしくお願いいたします。
> fix #1669 【ブログ】ゴミ箱に入れたブログコンテンツの記事が、サイト内検索の検索結果に表示されてしまう件を修正

- lib/Baser/Plugin/Mail/Config/update/4.1.0/updater.php
複数のメールフォームがある場合に、MailMessageモデルが初期化されていない問題があったので修正しました。
よろしくお願いいたします。
>  fix #1746 メールメッセージのアップデート中に処理が中断される問題を解決

- lib/Baser/Plugin/Blog/Config/setting.php
- lib/Baser/Plugin/Mail/Config/setting.php
非公開のコンテンツがサイドメニューから消える点は設定変更時などに使いづらいと思いましたので、
サイドメニューに常に表示するように変更してみました。
よろしくお願いいたします。
> fix #1611 【admin-third】特に非公開中のブログやフォーム等のコンテンツについて、設定画面への導線が不便に感じる件を修正

- app/Config/core.php
- lib/Baser/Config/bootstrap.php
- lib/Baser/Lib/Error/BcErrorHandler.php
- lib/Baser/Lib/Log/Engine/BcFileLog.php
@ryuring 
すいません、いったん白旗です。ログまわりのcake2の作りがちょっとどうなのかという感じがします・・
cake4はもっと分かりやすくなっているはず。
とりあえず最低限の整理を済ませて、しばらく寝かせて来月あたりにじっくり取り組みます。
1. ErrorHandlerをBcErrorHandlerとしてまるごと複製
2. 複製したBcErrorHandlerをリファクタリング
3. error404は分離した。これだけでもだいぶ実用性が上がるはず
4. ログの区切りを分かりやすくするためにFileLog::write()をBcFileLog::write()としてextends
というところまでやっておきました。
> fix #1666 ログ機構を整理

- lib/Baser/Plugin/Blog/Config/setting.php
- lib/Baser/Plugin/Mail/Config/setting.php
管理画面にてゴミ箱に入っているコンテンツがサイドナビに表示されており、リンクが無効になっている箇所があったため「ゴミ箱に入ったコンテンツはサイドナビに表示させない」ように改修を入れております。
> 管理画面にてゴミ箱に入っているコンテンツがサイドナビに表示されてしまう #1793

- lib/Baser/Plugin/Mail/Model/MailMessage.php
マルチチェックボックスの場合だけ、
入力チェック：なし
拡張入力チェック：チェックボックス未入力チェック
としないと、入力必須にできない仕様になっていたので、
他のタイプと同様に
入力チェック：入力必須
だけでも動作するようにしてみました。
（下位互換の為、これまで同様の設定でもOKにしたほうがいいかと思い、拡張入力チェックの項目は残しています。）
どうでしょうか。
> fix #1747 メールフォーム マルチチェックボックスの入力必須の動作を改善

- lib/Baser/Controller/BcAppController.php
1つ目のアドレスをFROMに設定してcakeEmailでエラーにならないように改修しました。
（メールフォームのFROMの部分の仕様と同様にしています。）
> fix #1784 管理者メールアドレスを複数設定時にパスワードリセット、メール送信テストでエラーになる問題を解決

- app/webroot/theme/admin-third/MailContents/admin/form.php
- lib/Baser/Plugin/Mail/Controller/MailController.php
- lib/Baser/Plugin/Mail/Model/MailContent.php
- lib/Baser/Plugin/Mail/Test/Case/Model/MailContentTest.php
- lib/Baser/Plugin/Mail/View/MailContents/admin/form.php
下記のような仕様に変更してみました。いかがでしょう？
- メールフォーム作成時に「送信先名」は空の状態とし、「送信先名を入力してください」はプレースホルダーにする
- フォーム送信時に条件分岐
- 空白の場合、サイト名を送信先名とする
- 入力されている場合、そちらを送信先名とする
> メールフォーム送信時の「送信先名」を空白許容とし、空の際の送信名にサイト名を設定するよう変更 #1648

- app/webroot/theme/admin-third/Elements/admin/content_fields.php
- app/webroot/theme/admin-third/Elements/admin/content_options.php
- lib/Baser/Controller/Component/BcContentsComponent.php
- lib/Baser/Plugin/Mail/Test/Case/View/Helper/MailHelperTest.php
- lib/Baser/View/Elements/admin/content_fields.php
- lib/Baser/View/Helper/BcContentsHelper.php
- $disableEditを$editableに変更
- 使用してないdisableEditContentを削除
- BcContentsHelper-Editable()にて$content['site_root']が1の場合編集不可になるよう修正
> disableEditをeditableに変更し、使用してないdisableEditContentを削除

- lib/Baser/Controller/PluginsController.php
- lib/Baser/Controller/ThemesController.php
マーケット側のRSSを修正してRSSは正しく生成されるようにしました。
ただ、設置するサーバの状態によってはbaserCMSコア側で読み込み時にSSL関連エラーが出る場合があるようでしたので読み込めるように変更してみました。
よろしくお願いいたします。
> fix #1810 テーマ一覧、プラグイン一覧のbaserマーケットタブの内容が空になる問題を修正

- lib/Baser/Test/Case/View/Helper/BcAppHelperTest.php
- lib/Baser/View/Helper/BcAppHelper.php
BcAppHelper->urlに以下のURLを渡した時だけHTMLエスケープが行われない問題があったので修正しました。
ご確認お願いします。
- httpから始まるURL
- 静的ファイルへのパスを含むURL
変更前
```
<?php $this->BcBaser->url('<b>b</b>') ?>
/_baser/seto1/blog/&lt;b&gt;b&lt;/b&gt;
<?php $this->BcBaser->url('https://<b>b</b>') ?>
https://<b>b</b>
<?php $this->BcBaser->url('/a/img/<b>b</b>') ?>
/_baser/seto1/a/img/<b>b</b>
```
変更後
```
<?php $this->BcBaser->url('<b>b</b>') ?>
/_baser/seto1/blog/&lt;b&gt;b&lt;/b&gt;
<?php $this->BcBaser->url('https://<b>b</b>') ?>
https://&lt;b&gt;b&lt;/b&gt;
<?php $this->BcBaser->url('/a/img/<b>b</b>') ?>
/_baser/seto1/a/img/&lt;b&gt;b&lt;/b&gt;
```
> BcAppHelper->url にエスケープ処理を追加

- lib/Baser/Model/BcAppModel.php
- lib/Baser/Model/Content.php
- lib/Baser/Plugin/Mail/Model/MailContent.php
fix #1758 
mysql8.0環境でbasercmsのインストールが失敗する問題を修正しました。
mysql8.0に対してsqlを投げるときに、`datetime`として`0000-00-00 00:00:00`を投げることで発生するエラーのようでした。
`lib/Baser/Model/BcAppModel.php`の`getConditionAllowPublish()`について、既にor条件でnullかどうかをチェックしているようでしたので、エラーになる部分は削除することで対応しています。
また、今回は該当箇所と他に同じ条件を指定している箇所についてもその部分を削除することで、インストールが正常に終わることを確認しています。
`./app/Console/cake baser_test baser BcAll`を実行して途中で同じエラーがでないことは確認済みです。
ご確認よろしくお願いいたします。
> mysql8.0環境でインストールが失敗する問題を修正

- lib/Baser/Model/Content.php
issue: https://github.com/baserproject/basercms/issues/1829
@ryuring mtgでお時間をとっていただいて申し訳ないのですが、原因としてはシンプルでしたので軽い修正ですみました。
原因としては親要素に公開期間が設定されている場合、親要素の公開状態まで上書きされてしまうということでした。
でしたので、以下のように調整しています。
- 親要素が非公開の場合は子要素も非公開
- 親要素に公開期間が設定されている場合は子要素の公開期間を上書き
今までこのあたりの処理が混ざっていたので分割しています。
また、親要素と子要素、両方に公開期間が設定されていた場合はどうするか、という問題なのですが、
現在の仕様でも親要素の公開期間を優先する仕様でしたので特に対応は不要でした。
ご確認お願いします。
> fix #1829 親フォルダが公開状態の非公開の固定ページが閲覧できる

- lib/Baser/Controller/ContentFoldersController.php
- lib/Baser/Controller/ContentLinksController.php
- lib/Baser/Controller/PagesController.php
- lib/Baser/Model/Content.php
- lib/Baser/Plugin/Blog/Controller/BlogCategoriesController.php
- lib/Baser/Plugin/Blog/Controller/BlogContentsController.php
- lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
- lib/Baser/Plugin/Mail/Controller/MailContentsController.php
- lib/Baser/Plugin/Mail/Controller/MailFieldsController.php
- lib/Baser/Test/Case/Model/ContentTest.php
- lib/Baser/Test/Fixture/Model/Site/SiteSubDomainFixture.php
issue: https://github.com/baserproject/basercms/issues/1833
ご確認お願いします。
- 公開用URL取得時の判定が不正確
- 公開されているコンテンツのURLを取得する関数を作成
- この関数の中で公開判定とURLの取得を行う
- 各コントローラーからその関数を使用して公開用のURLを取得するよう変更
- ブログカテゴリとブログ記事は公開用URLが他とは違うので独自処理
> fix #1833 【ページ】管理画面で公開期間外の固定ページへの確認リンクが表示される

- app/webroot/theme/admin-third/Elements/admin/toolbar.php
@ryuring 
@gondoh 
管理画面にアクセス可能な権限がある場合と同様のHTML形状にしました。
ただし、フロント側なのでbaserCMSのロゴマークは外しています。
お手数ですが、ご確認の上、マージお願いします。
> fix #1853 [ツールバー]管理画面にアクセス権限がない場合表示がおかしくなる問題を解決

- app/webroot/theme/admin-third/Users/admin/form.php
> ユーザー追加時のパスワードの必須表記の位置調整

- app/webroot/theme/admin-third/Elements/admin/blog_categories/index_list.php
- app/webroot/theme/admin-third/Elements/admin/contents/index_list_table.php
- app/webroot/theme/admin-third/Elements/admin/dblogs/index_list.php
- app/webroot/theme/admin-third/Elements/admin/search_indices/index_list.php
- app/webroot/theme/admin-third/Elements/admin/theme_files/index_list.php
- app/webroot/theme/admin-third/Elements/admin/uploader_categories/index_list.php
- app/webroot/theme/admin-third/Elements/admin/uploader_files/index.php
- app/webroot/theme/admin-third/Elements/admin/uploader_files/index_list.php
- app/webroot/theme/admin-third/Elements/admin/uploader_files/index_panel.php
- app/webroot/theme/admin-third/Elements/admin/user_groups/index_list.php
- app/webroot/theme/admin-third/Elements/admin/users/index_list.php
- app/webroot/theme/admin-third/Elements/admin/widget_areas/index_list.php
ユーザーの一覧画面だけでなく他の一覧画面のスタイル、表示位置など揃っていない所が他にもあったのであわせて揃えました。
管理画面一覧の右上
・ページネーション 
管理画面一覧の右下
・ページネーション 
・ページ数切り替え
よろしくおねがいします。
> fix #1858【ユーザー】ユーザー一覧のページネーションに隙間がない

- lib/Baser/Config/data/default/contents.csv
・コンテンツが2つしか無いためlftとrghtが完結できるように調整しました。
@ryuring お手数ですが、ご確認の上マージをお願いします。
> fix #1869 初期テーマをコアにするとツリー構造が最初からエラーになる問題を解決

- lib/Baser/Plugin/Blog/Config/setting.php
@ryuring 
こちら、コンテンツツリーと同じ順番で表示できるのが良いと思いましたので、プッシュしました。
ご確認下さい。
> fix #1872 管理画面 ブログが複数ある場合id順で表示されてしまうため並び替えができない問題を解決

- lib/Baser/Controller/BcAppController.php
直接実行できないようにすべき関数なので調整しています。
調整内容はsendMailに対する制限と同様のものです。
https://github.com/baserproject/basercms/blob/dev-4/lib/Baser/Controller/BcAppController.php#L864
ご確認よろしくお願いします。
> BcAppController->dispatchEventに直接アクセスできないように変更

- lib/Baser/View/Helper/BcFormHelper.php
@ryuring 
@gondoh 
お手数ですが、ご確認の上、マージをお願いします。
> fix #1894 メールフォーム ラジオボタンがphp8.1~に対応していない問題を解決

- app/webroot/theme/admin-third/MailContents/admin/form.php
@gondoh 
@ryuring 
admin-thirdのヘルプに追記しました。
ご確認の上マージお願いできますでしょうか？
> fix #1891【フォーム】自動返信メールのタイトルに{$フィールド名}といれると入力値に変換される機能をヘルプなどに追記

- app/webroot/theme/admin-third/__assets/css/components/_main.scss
- app/webroot/theme/admin-third/css/admin/style.css
バルーンチップがサイドバーに重なる際に状態を修正しました。
表示順の優先度ではなく overflow で切り取られていた為、overflow を設定する要素をバルーンチップの兄弟要素に変更しております。
> fix #1704 ヘルプのバルーンチップをサイドバーより前面に表示

- app/webroot/theme/admin-third/Elements/admin/blog_posts/index_row.php
・コンテンツの表形式と同様に、非公開ページの「目」のアイコンは押せない仕様に変更
@ryuring 
@gondoh 
こちら、ご確認の上、この仕様で良ければマージをお願いします。
> fix #1886 【管理画面】 ブログ記事一覧ページで非公開の記事でも「目」のマークが押せる問題を解決

- plugins/bc-blog/src/Service/BlogPostsService.php
@ryuring 
引数の$queryを上書きしてしまい、公開側ののブログ記事一覧が投稿日時順に表示されない問題を修正しました。
ご確認お願いします。
> 記事一覧が投稿日時順に表示されない問題を修正

- lib/Baser/View/Helper/BcBaserHelper.php
@ryuring 
@gondoh 
@$を使わずに変数を初期化することで対応してます。
ご確認のうえ、マージをお願いします。
> fix #1899 php8系で$this->BcBaser->crumbs()を使用するとWarningがでる問題を解決

- plugins/bc-mail/src/Service/MailContentsService.php
- plugins/bc-mail/tests/Scenario/MailContentsScenario.php
- plugins/bc-mail/tests/TestCase/Service/MailContentsServiceTest.php
MailContentsService::get のユニットテストを実装 #2107
MailContentsService::getNew のユニットテスト実装 #1965
MailContentsService::create のユニットテストを実装 #2108
MailContentsService::copy のユニットテストを実装 #2111
MailContentsService::update のユニットテストを実装 #2109
> fix #2107 #1965 #2108 #2111 #2109 MailContentsService Unit Test

- plugins/baser-core/src/Service/UsersService.php
- plugins/baser-core/src/Utility/BcUtil.php
issue: https://github.com/baserproject/basercms/issues/1938
loginUserの引数削除が良さそうとのことでしたので調整しています。
引数ありの呼び出し箇所を調べたところ、どれもリクエストのプレフィックスを渡していたため、大きな変更は不要でした。
ご確認お願いします。
> fix #1938 BcUtil::loginUser 引数削除

- plugins/baser-core/tests/TestCase/Service/ContentsServiceTest.php
- plugins/bc-favorite/tests/TestCase/Service/FavoritesServiceTest.php
issue: https://github.com/baserproject/basercms/issues/1928
expectExceptionのあとに書かれていたテストが実行されていなかったため修正しています。
修正して正常にテストが実行されるようになって発見したエラーもあるのですが、テストと処理どちらの修正が必要か判断できなかったので確認をお願いします。
https://github.com/baserproject/basercms/compare/dev-5...seto1:fix-test?expand=1#diff-fdfa30dcde75d58ad4d44f372e41ca69c5038ddceb556f8601ce618d96740a56R289
```
$this->assertTrue($this->ContentsService->hardDelete(16, true));
...
try {
$this->ContentsService->getTrash(17); // 子要素
$this->fail();
} catch (RecordNotFoundException $e) {}
```
親コンテンツを削除しても子コンテンツが削除されない
https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/src/Service/ContentsService.php#L499
一方、ContentsService->hardDeleteの第2引数は使用されていない
> fix #1928 expectExceptionを使用したテストの修正

- plugins/baser-core/src/Model/Table/AppTable.php
- plugins/baser-core/tests/TestCase/Model/Table/AppTableTest.php
- plugins/baser-core/tests/TestCase/Model/Table/ContentsTableTest.php
issue: https://github.com/baserproject/basercms/issues/1930
BcFormHelper->dateTimePickerのhiddenの日時が「Y/m/d H:i:s」形式だと、エンティティ変換時にnullになってしまうため「Y-m-d H:i:s」に変更しています。
「Y/m/d H:i:s」だと以下のフォーマットに含まれていないためnullになります。
https://github.com/cakephp/cakephp/blob/4.x/src/Database/Type/DateTimeType.php
```
protected $_marshalFormats = [
'Y-m-d H:i',
'Y-m-d H:i:s',
'Y-m-d\TH:i',
'Y-m-d\TH:i:s',
'Y-m-d\TH:i:sP',
];
```
日付の取り扱いは「Y-m-d」の方が統一されているようです。
https://ja.wikipedia.org/wiki/%E6%97%A5%E4%BB%98#%E5%B9%B4%E6%9C%88%E6%97%A5%E3%81%AE%E9%A0%86%E5%BA%8F%E3%81%AE%E6%B7%B7%E4%B9%B1
基本的に、日付の取り回しは「Y-m-d」の形式で、必要に応じて表示のタイミングでformatするのが良いのではと思います。
ご確認お願いします。
> fix #1930 FrozenTime::setToStringFormat 書式変更

- plugins/baser-core/src/Controller/Api/Admin/BcAdminApiController.php
APIにrefresh_tokenを送信した場合401ステータスが返却されるのですが、処理自体は実行されていたので止めています。
ご確認お願いします。
> jwtトークンタイプチェック修正

- plugins/baser-core/src/View/Helper/BcAdminFormHelper.php
`<?php echo $this->BcAdminForm->control('sample', ['type' => 'number']) ?>`でも`'type' => 'text'`と同様のclassが適用されるように調整しました。
> BcAdminFormHelper::controlでnumberの入力フィールドを出力できるように調整

- plugins/bc-blog/tests/TestCase/Service/BlogTagsServiceTest.php
- plugins/bc-mail/src/Service/MailFieldsService.php
- plugins/bc-mail/tests/TestCase/Service/MailFieldsServiceTest.php
MailFieldsService::getIndex のユニットテストを実装 #2229
> fix #2229 MailFieldsService::getIndex のユニットテストを実装

- lib/Cake/Event/CakeEvent.php
> fix #2286 PHP 8.2 deprecation notices in CakeEvent class.

- plugins/bc-mail/src/Service/MailFieldsService.php
- plugins/bc-mail/tests/TestCase/Service/MailFieldsServiceTest.php
fix #2240 MailFieldsService::update のユニットテストを実装
> fix #2240 MailFieldsService::update のユニットテストを実装 

- app/webroot/theme/admin-third/Users/admin/reset_password.php
[issue](https://github.com/baserproject/basercms/issues/2282)はこちらです。
静的関数でない関数を静的関数として呼び出そうとしてエラーが出ていました。
> php8以上でパスワード再発行完了画面でエラーがでる問題解決

- plugins/bc-admin-third/templates/Admin/element/Permissions/index_row.php
- plugins/bc-admin-third/templates/plugin/BcBlog/Admin/element/BlogPosts/index_row.php
よろしくお願いします。
同様の箇所が他にもあったので合わせて変更しています。
> fix #2304  ブログ記事一覧画面で削除→キャンセルするとローディングが消えない件を修正

- plugins/bc-blog/src/Service/BlogPostsService.php
where句部分にモデル名を入れています。
よろしくお願いします！
> fix #2372 ブログ記事一覧にて「一括処理に失敗しました」が発生する件を修正

- plugins/baser-core/src/Model/Table/AppTable.php
- plugins/baser-core/src/Model/Table/ContentFoldersTable.php
- plugins/baser-core/src/Model/Table/PagesTable.php
- plugins/baser-core/src/Model/Table/PasswordRequestsTable.php
- plugins/baser-core/src/Model/Table/PluginsTable.php
- plugins/baser-core/src/Model/Table/SiteConfigsTable.php
- plugins/baser-core/src/Model/Table/SitesTable.php
- plugins/baser-core/src/Model/Table/UserGroupsTable.php
- plugins/baser-core/src/Model/Table/UsersTable.php
- plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
- plugins/bc-blog/src/Model/Table/BlogContentsTable.php
- plugins/bc-blog/src/Model/Table/BlogPostsTable.php
- plugins/bc-blog/src/Model/Table/BlogTagsTable.php
- plugins/bc-content-link/src/Model/Table/ContentLinksTable.php
- plugins/bc-custom-content/src/Model/Table/CustomContentsTable.php
- plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php
- plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php
- plugins/bc-custom-content/src/Model/Table/CustomLinksTable.php
- plugins/bc-custom-content/src/Model/Table/CustomTablesTable.php
- plugins/bc-mail/src/Model/Table/MailConfigsTable.php
- plugins/bc-mail/src/Model/Table/MailContentsTable.php
- plugins/bc-mail/src/Model/Table/MailFieldsTable.php
- plugins/bc-search-index/src/Model/Table/SearchIndexesTable.php
- plugins/bc-search-index/src/View/Helper/BcSearchIndexHelper.php
- plugins/bc-uploader/src/Model/Table/UploaderCategoriesTable.php
- plugins/bc-widget-area/src/View/Helper/BcWidgetAreaHelper.php
AppTableを継承したモデルに必ずイベントを発火してほしいので、BcEventDispatcherTraitの読み込みを各クラスからAppTableに移動しました。
他の基底クラスであるAppControllerやAppViewはすでに追加済みのようです。
https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/src/Controller/AppController.php#L53
https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/src/View/AppView.php#L41
ご確認お願いします。
> BcEventDispatcherTraitをAppTableに追加

- plugins/baser-core/src/Plugin.php
- plugins/baser-core/tests/TestCase/Error/BcExceptionRendererTest.php
以下のissueに対応しました。ご確認お願いします。
https://github.com/baserproject/basercms/issues/2302
> fix #2302 Jwt認証領域でも未認証の場合はCSRFチェックをスキップしない

- plugins/baser-core/config/setting.php
- plugins/baser-core/src/Plugin.php
現在、API以外ではPOST送信時のCSRFチェックを回避する手段がないので、設定URLによるスキップ判定の優先度を上げています。
独自のtokenで検証するような場合に必要になる想定です。
ご確認お願いします。
> CSRFチェックのURLチェックの優先度を上げる

- plugins/baser-core/src/Controller/Api/BcApiController.php
- plugins/baser-core/src/Identifier/Resolver/PrefixOrmResolver.php
- plugins/baser-core/src/Plugin.php
- plugins/baser-core/src/Utility/BcApiUtil.php
JWTのトークン生成時に指定したプレフィックスと、認証時のプレフィックスが一致しないと認証が通らないように制限を追加しました。
例えば今までは、以下のどちらの方法で生成したトークンでも管理画面のAPIの認証が通っていました。
```
\BaserCore\Utility\BcApiUtil::createAccessToken(1, 'Api/Admin');
\BaserCore\Utility\BcApiUtil::createAccessToken(1, 'Test');
```
ご確認お願いします。
> JWT認証時にプレフィックスチェック

- lib/Baser/Plugin/Blog/Controller/BlogController.php
@gondoh 
@kaburk 
@ryuring 
タグの存在確認判定を追加しました。
ご確認の上、baserCMS 4系にマージお願いします。
> fix #2406 [ver4] /tags/{存在しないタグ名} がステータス200として戻される問題を解決

- lib/Baser/Lib/Error/BcErrorHandler.php
@ryuring 
@gondoh 
@kaburk 
ここを修正すれば、php5.4で開いたときにいきなり画面が真っ白になることがなくなります。
お手数ですが、ご確認の上マージお願いします。
> fix #2177 PHP5.4に対応していない問題を解決 [ver4]

- lib/Baser/Model/Content.php
@ryuring 
@gondoh 
@kaburk 
_1がついているname値と同nameでないかどうかの判定を入れました。
ご確認の上マージお願いします。
> fix #2173 [コンテンツ]同一階層にindexがなくてもindex_1があるとindexが作成できない問題を解決

- plugins/baser-core/src/Model/Behavior/BcUploadBehavior.php
issue: https://github.com/baserproject/basercms/issues/2505
deleteExistingFilesにはoldEntityを渡す必要があるので修正しました。
参考: 4系
https://github.com/baserproject/basercms/blob/dev-4/lib/Baser/Model/Behavior/BcUploadBehavior.php#L211
ご確認お願いします。
> fix #2505 BcUpload 前回と異なる拡張子のファイルをアップロードすると前回のファイルが削除されない

- plugins/baser-core/src/Model/Table/UsersTable.php
emailバリデーションが怪しいので半角チェックを追加しました。
ご確認お願いします。
１２３@example.com => NG
てすと@example.com => OK
> ユーザーメールアドレスの半角チェックを追加

- plugins/baser-core/src/Event/BcEventDispatcherTrait.php
- plugins/baser-core/src/Event/BcMailerEventListener.php
- plugins/baser-core/src/Mailer/BcMailer.php
- plugins/baser-core/src/Utility/BcEvent.php
メール送信前のイベントを追加しました。
動機としては、管理画面のパスワード再発行時のメールの内容をカスタマイズすることです。
ご確認お願いします。
利用例
```
<?php
namespace BcBlog\Event;
use BaserCore\Event\BcMailerEventListener;
use Cake\Event\EventInterface;
class BcBlogMailerEventListener extends BcMailerEventListener
{
public $events = ['BaserCore.PasswordRequest.beforeDeliver'];
public function baserCorePasswordRequestBeforeDeliver(EventInterface $event)
{
$mailer = $event->getSubject();
$mailer->setFrom(['from@example.com' => '送信者'])
->setSubject('メールタイトル')
->viewBuilder()
->setVars(['var' => 'test']);
}
}
```
> メール送信前のイベントを追加

- plugins/bc-blog/src/Controller/Admin/BlogPostsController.php
管理画面 ブログ記事一覧のタイトル部分をクリックしても並び順が切り替わらない
> fix #2527 管理画面 ブログ記事一覧のタイトル部分をクリックしても並び順が切り替わらない

- lib/Baser/Controller/Component/BcContentsComponent.php
・php 8系では'+5 min'など、string型で指定されていた場合、5分後と判定されないため、numeric型以外はstrtotimeで型を変更する処理を入れた
@ryuring 
@gondoh 
@kaburk 
お手数ですが、ご確認お願いします
> fix #2638 baserCMS4系　php８でビューキャッシュが生成されない問題を解決

- lib/Baser/Lib/BcFileUploader.php
issueはこちら。 https://github.com/baserproject/basercms/issues/2570
> fix #2570 4系版メールフォームで1フォーム内で複数のファイルタイプを利用すると送信完了前にエラーが起こる動作を改善

- lib/Baser/View/Helper/BcBaserHelper.php
https://github.com/baserproject/basercms/issues/1868#ref-commit-c20a3ce
上記issueを解消しました。
エラーページでサイトIDが参照できていな方ので、参照できるようにしエラー解消しました。
ご確認お願いいたします。
> bccolumテーマのグローバルメニューの挙動に関する不具合解消

- plugins/baser-core/src/Middleware/BcRequestFilterMiddleware.php
- plugins/baser-core/src/Plugin.php
- plugins/baser-core/tests/TestCase/PluginTest.php
> fix #2783 CGIモードでJWT認証が可能になるようにしたい

- plugins/baser-core/src/Model/Validation/UserValidation.php
別テーブルをcontainしている場合にどのテーブルのidか特定できずに以下のSQLエラーが出るため調整しました。
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
```
ご確認お願いします。
> beforeFindなどで別テーブルをcontainする場合に、sqlエラーが出る問題を解消

- plugins/baser-core/src/Mailer/BcMailer.php
@ryuring 
コマンドからBcMailerを実行する際に、Requestが取得できない場合でも getAttribute() を呼び出そうとしてエラーとなるため、修正しました。
ご確認お願いします。
> BcMailerをコマンドから実行した際にエラーになる問題を修正

- lib/Baser/Lib/BcUtil.php
@ryuring 
先程お話したルビ用のタグとなります。
ご確認の上、マージお願いします。
cc @kaburk @gondoh
> fix #2860 [baserCMS4系]メールとブログの説明文について rubyタグが除外されてしまう問題を解決

- plugins/bc-blog/src/Service/BlogCategoriesService.php
- plugins/bc-blog/tests/TestCase/Service/BlogCategoriesServiceTest.php
管理画面のブログカテゴリ一覧の表示崩れとブログカテゴリ追加・編集画面の表示の調整を行いました。
ご確認お願いします。
> ブログの子カテゴリの表示を調整

- plugins/bc-blog/src/Service/BlogPostsService.php
@ryuring 
こちらが先程の修正箇所となります。
ループでfindを繰り返すと重くなりそうだったので、findメソッドを変更して、
Hash::extractにてentity_idの配列にしています。
> fix #2991 baserCMS 5系 blogPosts()でカテゴリの指定を行うとエラーになる問題を解決

- plugins/baser-core/src/View/AppView.php
@ryuring 
こちら調整しましたので、お手数ですが、ご確認お願いできますでしょうか？
> fix #2996 【baserCMS5系】BcArrayHelperがBcBlogなどで使用できない問題を解決

- plugins/baser-core/src/View/AppView.php
作ってみました。どうでしょうか？
↓ みたいなプラグイン名、ファイル名を指定して プラグイン内に設置したファイルに差し替える使い方想定です。
```
public $events = array(
'BcBlog.Blog.beforeGetLayoutFileName',
'BcBlog.Blog.beforeGetElementFileName',
'BcBlog.Blog.beforeGetTemplateFileName',
);
public function bcBlogBlogBeforeGetLayoutFileName(Event $event)
{
$event->setData('name', 'HogePlugin.fuga');
return $event->getData('name');
}
public function bcBlogBlogBeforeGetElementFileName(Event $event)
{
if ($hoge == 'fuga') {
$event->setData('name', 'HogePlugin.hoge');
}
return $event->getData('name');
}
public function bcBlogBlogBeforeGetElementFileName(Event $event)
{
if ($hogehoge == 'fugafuga') {
$event->setData('name', 'HogePlugin.hogehoge');
}
return $event->getData('name');
}
```
> fix #2404 Vew関連のイベント（beforeGetTemplateFileName/ beforeGetElementFileName / beforeGetLayoutFileName）を実装

- plugins/baser-core/config/bc_form.php
@ryuring 
`<textarea></textarea>`内の改行コード2つを削除しました。
お手数ですが、ご確認お願いできますでしょうか？
> fix #2998 管理画面 テキストエリアに自動で空白文字（改行）が入ってしまう問題を解決

- lib/Baser/Plugin/Mail/Controller/MailController.php
常に英語表記となるテキストのみの調整です。
可能な際に取り込み検討お願いします。
> fix メールフォームでの送信完了へ進むタイミングで入力エラーが起こった際のアラートメッセージが常に英語で表示されるテキストを調整

- plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php
@ryuring 
シンプルにWarning対策を行っています。
お手数ですが、ご確認の上、マージをお願いします。
`Warning (2) : Attempt to read property "display_front" on bool [in /var/www/html/vendor/baserproject/bc-custom-content/src/View/Helper/CustomContentHelper.php, line 217]`
> fix #3120 カスタムコンテンツを２つ以上トップページなどで一覧表示させるとアイキャッチが取得できない問題を解決

- lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
- lib/Baser/View/Helper/BcBaserHelper.php
issueはこちらです。 https://github.com/baserproject/basercms/issues/2987
可能な際に取込み検討をよろしくお願いします。
> fix #2987 BcBaserHelper::getThemeUrl()でサブサイトに設定しているテーマURLが取得できない動作を修正

- plugins/bc-admin-third/templates/plugin/BcBlog/Admin/element/BlogPosts/popup_blog_category.php
issueはこちら https://github.com/baserproject/basercms/issues/3128
可能な際に取込み検討お願いします
> fix #3128 ブログ記事編集画面内の「新しいカテゴリを追加」ポップアップ内のヘルプ文言をエラーメッセージ内容と同じに調整

- plugins/bc-blog/src/View/Helper/BlogHelper.php
- plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> add unitTest_BlogHelper_isSingle

- plugins/baser-core/src/Model/Table/PermissionsTable.php
> テーブル名にmysiteなどのprefixがついている場合アクセスルールの追加ができない問題を修正

- lib/Baser/Plugin/Mail/Model/MailMessage.php
@ryuring 
cc @kaburk 
こちら、お話させていただきました、メールフォームの半角変換で、
`mb_convert_kana($value, 'a');`
では、全角スペースが半角変換できない問題を解消するためのコミットとなります。
4系の対応となりますが、お手数ですが、ご確認・マージお願いできますでしょうか？
> fix #3275 baserCMS4系 メールフォームで半角変換を有効にしても全角ハイフンが半角ハイフンにならない問題を解決

- plugins/baser-core/src/Model/Validation/BcValidation.php
- plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php
- plugins/bc-admin-third/templates/plugin/BcThemeConfig/Admin/ThemeConfigs/index.php
- plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
- plugins/bc-theme-config/tests/TestCase/Model/Table/ThemeConfigTest.php
管理画面テーマ設定のテーマカラーにてカラーコード以外の任意の文字列も保存できる為、下記の処理を追加いたしました。
1. BcValidation に16進数カラーコード判定のバリデーションを追加
1. 管理画面テーマ設定でテーマカラーにバリデーションを追加
カラーコードのバリデーションには CakePHP の `hexColor` もあるものの6桁以外も判定できるように BcValidation に追加しております。3桁、4桁、6桁、8桁を許容するようにしました。
> fix #2930 テーマ設定のテーマカラーにエラーメッセージ追加

- app/webroot/theme/admin-third/Elements/admin/mail_fields/index_row.php
- lib/Baser/Plugin/Mail/Controller/MailFieldsController.php
- lib/Baser/Plugin/Mail/View/Elements/admin/mail_fields/index_row.php
- 副次的な効果として、メールフィールド数が多数（14000件超）、かつphp5.6環境でメッセージテーブルが正しく作成されない場合がある動作を改善
- メールフィールド複製時、debugログにUndefinedが残る動作を改善
> fix メールフィールド複製時、受信データ用テーブルを作り直す動作となっていることで、保持している受信データを削除している動作を調整

- plugins/bc-mail/src/Model/Table/MailFieldsTable.php
- plugins/bc-mail/tests/TestCase/Model/Table/MailFieldsTableTest.php
add MailFieldsTable_sourceMailField
> add MailFieldsTable_sourceMailField

- plugins/bc-widget-area/src/Model/Entity/WidgetArea.php
- plugins/bc-widget-area/tests/TestCase/Model/Entity/WidgetAreaTest.php
> add WidgetArea_getCount

- plugins/bc-admin-third/templates/plugin/BcMail/Admin/element/MailMessages/index_row.php
issue はこちらです。 https://github.com/baserproject/basercms/issues/3472
> fix #3472 【メールフォーム】受信一覧画面で BcListTable.showHeadとshowRowを利用したときに列が揃わない

- plugins/baser-core/src/Utility/BcComposer.php
> fix baserproject#3509 baserCMSコアのアップデートがxdebug不足により失敗する事象の修正

- plugins/baser-core/src/Service/UtilitiesService.php
> fix baserproject#3488 ごみ箱にファイルがある状態でツリー構造チェックを行うと常にエラーになる問題を修正

- plugins/baser-core/src/Controller/AppController.php
以下のissueに対応しました。ご確認お願いします。
https://github.com/baserproject/basercms/issues/3523
変更内容
- 権限が無いページにアクセスした際のリダイレクト処理を調整
- ログイン時: loginRedirect
- 非ログイン時: loginAction + 現在のURLをredirectパラメーターとする
- リファラへのリダイレクトが存在すると、以下の条件で無限ループになるため削除
- 未ログイン状態で、アクセスルールで禁止されたページからログインする
権限が無いページへのリンクは表示されないはずなのでリファラへのリダイレクトは不要ではないかと思います。
また、非ログイン時のリダイレクトは無くても動きますがちょっと怖いので残してます。
> fix #3523 【システム】管理画面ログイン後のリダイレクトが動作していない 

- plugins/bc-uploader/src/Controller/Admin/UploaderCategoriesController.php
- plugins/bc-uploader/src/Controller/Admin/UploaderFilesController.php
ご確認お願いします。
issue: https://github.com/baserproject/basercms/issues/3106
変更内容
- アップロードファイル・カテゴリ一覧でデフォルトの表示件数指定が効いていなかったので修正
> アップロードファイル・カテゴリ ページネーション調整

- plugins/baser-core/src/Model/Table/AppTable.php
- plugins/baser-core/tests/TestCase/Model/Table/AppTableTest.php
@ryuring 
findの前後にイベントを追加するために、AppTableにCake\ORM\Table::find()をオーバーライドしてイベントを追加しました。
リードレプリカへの接続切り替えなどでの利用を想定しています。
ご確認お願いします。
> Cake\ORM\Table::find()の前後にイベントを追加

- plugins/bc-blog/src/Controller/BlogController.php
- plugins/bc-blog/src/Service/BlogPostsService.php
- plugins/bc-blog/src/Service/BlogPostsServiceInterface.php
- plugins/bc-blog/src/Service/Front/BlogFrontService.php
- plugins/bc-blog/src/Service/Front/BlogFrontServiceInterface.php
- plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
- plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
- plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
- plugins/bc-front/templates/plugin/BcBlog/element/widget/blog_author_archives.php
issue: https://github.com/baserproject/basercms/issues/3244
ブログの投稿者別記事一覧のURLのキーをアカウント名からユーザーIDに変更しました。
ご確認お願いします。
変更前: https://trial.basercms.net/news/archives/author/demo
変更後: https://trial.basercms.net/news/archives/author/2
APIの方は現状で以下の形式のため対応不要でした。
/baser/api/bc-blog/blog_posts.json?user_id=2
> ブログ 投稿者別記事一覧URL変更

- plugins/baser-core/src/Service/ThemesService.php
issue: https://github.com/baserproject/basercms/issues/3140
こちらのissueの問題、プラグインの方は以下コミットで修正されていたのでテーマの方にも適用しました。
ご確認お願いします。
https://github.com/baserproject/basercms/commit/02fb2787ebc3cbd2c82365fefb775f85af619e4b
> テーマのzipファイル名がテーマ名と異なる場合に追加に失敗する

- plugins/baser-core/src/Service/BcDatabaseService.php
#3599 のプルリクです。
CSVの読み込み処理を見る限り、「””,」(空文字)と「,」(カンマだけ)の場合どちらも配列では「""」になっているので、
明示的にnullを代入するのは配列の中身が「""」(空文字)の場合だけで良いかと思ってますが、いかがでしょうか。
> fix baserproject#3599 CSVファイルの"0"がnullとして読み込まれてしまう事象を修正

- docker/docker-compose.yml.default
docer-compose up -dを実行したとき以下のwarningが出ていたため修正しました。
```
WARN[0000] /{baser設置ディレクトリ}/docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```
ご確認お願いします。
> fix #3767 docer-compose.ymlの不要なversion指定を削除

- app/webroot/theme/admin-third/Elements/admin/footer.php
[fix](https://github.com/baserproject/basercms/commit/35324229a6ec0c940a59e9874c8870d65defe529) https://github.com/baserproject/basercms/issues/2680
admin-thirdテーマ、フッターデザイン表示切り替えの条件分岐が admins縛りになっているのをログインユーザーに変更。
`<?php if (BcUtil::isAdminUser()): ?>`
↓
`<?php $user = BcUtil::loginUser(); ?><?php if ($user): ?>`
ご確認、お願いします。
> fix #2680 admin-thirdテーマ、フッターデザイン表示切り替えの条件分岐を修正。

- plugins/baser-core/src/Model/Table/AppTable.php
- plugins/baser-core/tests/TestCase/Model/Table/AppTableTest.php
`plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php`
に参照されない変数が使われていたので、修正しました。
plugins/bc-theme-file/config/setting.phpの
```'BcThemeFile.allowedThemeEdit' => false```
でも、URLを打ち込むとテーマ編集画面に入れていましたが、今回の修正で入れないようになったことを確認しました。
ご確認お願いします！
> fix #3745 テーマテンプレートの編集設定の名称にブレがあるのを修正

- lib/Baser/Controller/ContentsController.php
@ryuring 
@kaburk 
取り急ぎ、こちらで動作するようになると思います。
> fix #3735 【baserCMS4】コンテンツ管理で固定ページのタイトルを変更してもフロント側に反映されない問題を解決

- app/webroot/theme/admin-third/Elements/admin/toolbar.php
- app/webroot/theme/admin-third/__assets/css/components/_toolbar.scss
- lib/Baser/View/Elements/admin/toolbar.php
- lib/Baser/webroot/css/admin/toolbar.css
reviewお願いします。
4系、admin-second/admin-thirdについて、toolbar.phpで使用しているBcBaser->getImg()のオプションの['width' => 8, 'height' => 11, ]を削除し、5系に倣って、cssのスタイルに移行しました。
> fix #3836 

- plugins/baser-core/src/Utility/BcAbstractDetector.php
- plugins/baser-core/tests/TestCase/Utility/BcAbstractDetectorTest.php
カスタムコンテンツでのフィールド編集にて、
ファイル拡張子チェックのエラーメッセージの末尾に「jpg,pdf」といった具体例を表示するような修正になります。
あわせてtestコードの文言も修正しています。
@ryuring @fuchigam1 
ご確認おねがいします。（ReviwerとAssignneを私の方で変更できなかったためメンションでのご案内失礼します）
> #3881 カスタムコンテンツ：エラーメッセージに情報不足な部分がある：エラーメッセージ修正

- app/webroot/theme/admin-third/Elements/admin/blog_posts/index_row.php
- lib/Baser/Lib/BcSite.php
@ryuring 
メインサイトの管理画面から独自ドメインのサブサイト記事にアクセスすると、
```
{メインサイトドメイン}/{サブサイトドメイン}/記事URL
```
のようにURLが正しく生成されない問題を解消しました。
ご確認お願いします！
> メインサイトの管理画面からサブサイト記事にアクセスするとURLが正しく生成されない問題を解消 #3889

- plugins/bc-admin-third/templates/Admin/element/Plugins/index_row_market.php
@ryuring 
以下修正を追加しました。ご確認お願いします。
- 開発者名内のHTMLタグを削除
- 開発者リンクが設定されていない場合はaタグを出力しない
> #3918【プラグイン管理】開発者の表記にbrタグが入ってる＆リンク先がおかしい

- config/.env.example
- plugins/baser-core/config/setting.php
- plugins/baser-core/src/BaserCorePlugin.php
- plugins/baser-core/src/Controller/Admin/UsersController.php
@ryuring 
.env にて
`export HASH_TYPE="sha1"`
を追記し、
`export SECURITY_SALT="４系のときのSECURITY_SALT"`
とすることで、旧パスワードのDBを持ってきてそのまま使うことができるようになります。
よろしくお願いします。
> fix #3882 [要望]baserCMS4系で使用していたときのパスワードが引き継げない問題を解決

- plugins/baser-core/config/setting.php
- plugins/baser-core/src/BaserCorePlugin.php
- plugins/baser-core/src/View/AppView.php
- plugins/baser-core/src/View/BcAdminAppView.php
- plugins/baser-core/tests/TestCase/BaserCorePluginTest.php
- plugins/bc-mail/config/setting.php
- plugins/bc-mail/src/View/MailFrontAppView.php
１）Themeのconfig/setting.phpが、Pluginの後に読み込まれて上書きされるため、Themeが最後に読み込まれるように、addThemeの位置を変更。
２）config/bc_form.phpの読み込むファイルを、Plugin/Themeのconfig/setting.phpで変更できるように、setting.phpに設定値を追加。
追加した設定値は以下3つ
```
BcApp.AdminFormTemplate
BcApp.AppFormTemplate
BcMail.formTemplate
```
デフォルトの設置値
```php
'BaserCore.bc_form'
```
それぞれ以下のViewファイルに対応
```
BcApp.AdminFormTemplate -> BcAdminAppView
BcApp.AppFormTemplate -> AppView
BcMail.formTemplate -> MailFrontAppView （フロントのbc-mailに対応）
```
独自Plugin/Themeのconfig/setting.phpで次のように書いて、
```php
return [
'BcMail' => [
'formTemplate' => 'ThemeName.bc_form'
],
];
```
baser-core/config/bc_form.phpを、独自Plugin/Themeのconfig/bc_form.phpへコピーして、内容を書き換える。
> Themeの読み込み順変更。bc_form.phpをsetting.phpで変更できるように。

- plugins/bc-admin-third/templates/Admin/element/main_body_header_links.php
@ryuring 
お待たせしています...!
アドバイスいただいた通り、以下修正を追加しました。
actionの指定がない場合`data-bca-btn-type` を指定せずボタンを出力するようになります。
以下を確認しています
- actionを指定しない（外部リンクを指定する）場合でもボタンが出力され、クリックで正しく遷移できる
- actionを指定した（既存処理の）場合でもボタンが出力され、クリックで正しく遷移できる
> addAdminMainBodyHeaderLinks()で外部リンクを設定できるように修正 fix #4030

- plugins/bc-mail/src/Model/Table/MailContentsTable.php
@fuchigam1 
お待たせしております...!
こちら修正対応反映しましたのでご確認お願いします。
メールフォーム受付期間の終了日付（publish_end）に開始日付以後であるかのバリデーションが適用されていなかっため追加しました。
ローカル環境にて以下を確認しています
- 終了日付が開始日付以前の場合、エラーが表示され保存できないこと
- 終了日付が開始日付以後の場合（正常系）、正しく保存されること
> メールフォーム受付期間のpublish_endにバリデーション追加 fix #4000

- src/Application.php
@ryuring 
@seto1 
BASERCMSクッキーにsecure属性がつく場合は、csrfTokenにもsecure属性がつくように調整しました。
ご確認ください。
php.iniでsession.cookie_secure = 1になっていても、csrfTokenにはsecure属性がつかないので、
BASERCMSクッキーにsecure属性がつくときと同じ条件で、secure属性がつくように調整しました。
（cakePHPの仕様でSessionは.envにHTTPSパラメータを追記するとサーバーの状態に関係なくsecure属性がつくようになります。それも引き継ぐようにしています。）
> fix #4067 Cookie（csrfToken）にsecure属性が付かない問題を解決

- plugins/baser-core/src/Controller/Admin/PluginsController.php
#3990 のプルリクになります。
プラグイン無効化時に既存アクセスルールを削除することで、有効化時の登録による重複を防ぎます。
> fix #3990 プラグインを無効にして再度インストールするとアクセスルール設定が重複して登録される

- lib/Baser/View/Helper/BcAppHelper.php
> 【アップローダー】サブフォルダコンテンツにて、ブログなどアイキャッチ画像をクリックすると表示に失敗する fix #4136

- plugins/baser-core/src/Service/Admin/BcAdminContentsService.php
@ryuring 
@seto1 
修正方法は
https://github.com/baserproject/basercms/pull/4040/commits/9a296d9056c527f390e0d8f0fc7eb8753ddd6d8d
と全く同じです。
こちらで、正常動作になることを確認しました。
お手数ですが、ご確認の上、マージをお願いできますでしょうか？
> fix #4126 【コンテンツ】5.0.x にてレイアウトテンプレートの取得順序がおかしくなる問題を解決

- plugins/bc-blog/src/View/Helper/BlogHelper.php
@ryuring 
こちら、ISSUEに記述した通り、
BlogHelperの `posts()` の中の
```
if ($options['preview'] === false) {
$options['status'] = 'publish';
}
```
を `getPosts()` に移動することで対応しています。
ご確認の上、問題なさそうでしたら、マージをお願いします。
> fix #4162 ブログ】getBlogPosts()をデフォルトのままで使うと非公開記事まで取得されてしまう問題を解決

- plugins/bc-custom-content/src/Controller/CustomContentController.php
@ryuring 
本来であれば
```
$this->set($service->getViewVarsForIndex(
$customContent,
$this->paginate(
$service->getCustomEntries($customContent, $this->getRequest()->getQueryParams()),
['limit' => $customContent->list_count,
'sort' => $customContent->list_order,
'direction' => $customContent->list_direction
]
)
));
```
のほうが望ましいのですが、一旦5.1.xと同様に
```
$this->set($service->getViewVarsForIndex(
$customContent,
$this->paginate(
$service->getCustomEntries($customContent, $this->getRequest()->getQueryParams()),
['limit' => $customContent->list_count]
)
));
```
としています。
お手数ですが、ご確認の上、5.0.xへとマージお願いします。
> fix ##4099 5.0.x系にて、カスタムコンテンツ一覧表示件数が管理画面通りにならない問題を解決

- plugins/bc-favorite/src/Service/FavoritesService.php
- plugins/bc-favorite/tests/TestCase/Service/FavoritesServiceTest.php
@ryuring 
すみません。
案件でも対応しているため、
お手数ですが、ご確認の上、5.0.x系にマージをお願いします。
> fix #4105 5.0.x系にて【お気に入り】お気に入り一覧に別のユーザーのデータまで表示される問題 を解決

- plugins/bc-mail/src/Controller/MailController.php
当該Issue(#4124)において再現性のある、「captcha.phpに関するエラーがログ出力される事象」について
Controller側の自動レンダリングを停止し、Action名と同じView「captcha.php」を参照しないよう
修正しております。
（$service->renderによりkcaptcha側で生成された画像データのみが直接レスポンスとして返却される）
> fix #4124 【メール】BcMail プラグインのイメージ認証（captcha）で画像が表示されない

- plugins/bc-admin-third/templates/plugin/BcBlog/Admin/element/BlogContents/form.php
@ryuring 
bc-admin-third/templates/Admin/element/content_fields.phpに合わせて
`"content.name"`
にて調整しています。
ご確認の上、マージをお願いします。
> fix #4174 【ブログ】ブログ設定編集画面にて、ヘルプのRSSフィードのリンクがおかしくなる問題を解決

- plugins/baser-core/src/Service/Admin/ContentsAdminService.php
削除権限が無いのに固定ページ編集画面に削除ボタンが表示されていたので修正しています。
パス生成の部分で/が抜けていたので、以下のパスで権限のチェックを行っていたのが原因のようです。
/baser/adminbaser-core/contents/delete
ご確認お願いします。
> コンテンツ削除権限チェック調整

- plugins/baser-core/src/View/Helper/BcContentsHelper.php
- plugins/baser-core/tests/TestCase/View/Helper/BcContentsHelperTest.php
issue: https://github.com/baserproject/basercms/issues/3739
こちらのissueの5系の対応を行いました。
4系の際の対応はこちらです。
https://github.com/baserproject/basercms/pull/3743/files
4系の際は権限チェックの直前でpreg_replaceでURLのフォルダの部分の削除を行っていました。
5系では権限チェック用のURLを別に生成することで対応しています。
ご確認お願いします。
> コンテンツ管理 権限チェック調整

- plugins/bc-search-index/src/Model/Behavior/BcSearchIndexManagerBehavior.php
@ryuring 
@seto1 
@kaburk 
結構クリティカルな問題なので、取り急ぎ応急処置として、保存時のデータ検索に
content_idを追加しています。
お手数ですが、ご確認お願いできますでしょうか？
> fix #4188 【カスタムコンテンツ】検索テーブルに別のカスタムコンテンツの情報で上書きされてしまう問題を解決

- plugins/baser-core/src/Event/BcShortCodeEventListener.php
遅くなりましたが、以下の課題を対応しました。
https://github.com/baserproject/basercms/issues/4190
- ショートコードを読み込む際にエラーが発生しないようにhasメソッドで分岐
- ショートコードを読み込んだ際にhasメソッドによる分岐が機能していることを確認
ご確認よろしくお願いします。
> fix #4190 hasメソッドに変更

- plugins/baser-core/src/Controller/AppController.php
- plugins/bc-blog/src/Service/Front/BlogFrontService.php
- plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
> fix #4176 【フィード 】index.rssがErrorになる問題を解決

- plugins/bc-custom-content/src/Service/Front/CustomContentFrontService.php
こちら本当はわかりやすいように以下のコードで修正をしたかったのですが、
現在のコードに合わせて調整しています。
```
// カスタムエントリーのエンティティをパッチ
if ($customEntriesTable->hasBehavior('BcUpload')) {
// BcUpload ビヘイビアがある場合は、アップロードファイルを保存
$entity = $customEntriesTable->patchEntity(
$customEntry ?? $customEntriesTable->newEmptyEntity(),
$customEntriesTable->saveTmpFiles($postEntity, mt_rand(0, 99999999))->toArray()
);
} else {
// BcUpload ビヘイビアがない場合は、通常のパッチ
$entity = $customEntriesTable->patchEntity(
$customEntry ?? $customEntriesTable->newEmptyEntity(),
$postEntity
);
}
```
> fix #4201 【カスタムコンテンツ】特定のカスタムコンテンツでプレビューを押すとエラーになる問題を解決

- plugins/bc-blog/src/Model/Table/BlogTagsTable.php
https://github.com/baserproject/basercms/issues/4002
- WEBAPIのルートの末尾にjsonを追加して、権限チェックが正しく機能するように
- サイト運営権限でログインして記事追加ページのタグ追加ボタンが表示されて追加できること
- `ブログタグAPI`権限でwebapiのルートを無効化に変更して非表示になることを確認(タイプ：Api/Admin)
この部分は管理システムの権限チェックではなく
ajaxから送信するようになっているため、webapiのルートでチェックするようになっている
ご確認よろしくお願いします。
> fix #4002 運用者：タグ追加ボタンが表示されていない

- plugins/bc-admin-third/templates/plugin/BcBlog/Admin/element/BlogCategories/index_row.php
https://github.com/baserproject/basercms/issues/4003
- 管理者権限かどうかで表示をチェックしていたので、分岐を削除(ヘルパー内で権限チェックが行われる認識のため)
- サイト運用者などの役割で「ブログカテゴリ管理」権限の編集と削除の機能を**ON**と**OFF**に切り替えて機能していることを確認
ご確認よろしくお願いします。
> fix #4003 カテゴリー一覧 運用者：アクションアイコンが表示されない

- plugins/bc-custom-content/plugins/BcCcRelated/src/View/Helper/BcCcRelatedHelper.php
- plugins/bc-custom-content/plugins/BcCcRelated/templates/Admin/element/custom_field_meta.php
@uchin0 (@ryuring )
https://github.com/baserproject/basercms/issues/4221
上記の問題を解消しました。
レビューお願いします！
> fix#4221【カスタムコンテンツ】フィールド編集で関連データとして指定したテーブルのエントリーがセレクトボックスしか設定できない問題を解消

- plugins/baser-core/src/Model/Behavior/BcUploadBehavior.php
該当コードの直前でイベントをオフにしているものの、関連テーブルのイベントが実行されてしまうようなので対応しています。
ご確認お願いします。
plugins/bc-blog/src/Model/Table/BlogTestsTable.php
作成
```
<?php
namespace BcBlog\Model\Table;
class BlogTestsTable extends BlogAppTable
{
public function initialize(array $config): void
{
parent::initialize($config);
$this->addBehavior('BaserCore.BcUpload', [
'saveDir' => 'test',
'fields' => [
'test' => [
'type' => 'image',
'namefield' => 'id',
'nameformat' => '%08d'
]
]
]);
}
}
```
plugins/bc-blog/src/Model/Table/BlogPostsTable.php
initialize内に追加
```
$this->hasOne('BlogTests', [
'className' => 'BcBlog.BlogTests',
]);
```
plugins/bc-admin-third/templates/plugin/BcBlog/Admin/element/BlogPosts/form.php
form内のどこかに追加
```
<?php echo $this->BcAdminForm->control('blog_test.test', [
'type' => 'file',
'imgsize' => 'thumb', …
```
> BcUploadBehavior->afterSaveで関連データを保存しない

- plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php
- plugins/bc-custom-content/tests/TestCase/Model/Table/CustomEntriesTableTest.php
issue: https://github.com/baserproject/basercms/issues/4233
CustomEntriesに関連する項目以外に対してもjson_encodeが実行されてしまうため調整しています。
こちらの記述だと、if文でマッチしない場合は$this->linksの最後の項目が使われてしまうようでした。
```
foreach($this->links as $link) {
if ($link->name === $key) break;
}
```
> CustomEntriesに関連づけたテーブルのデータが保存されない

- plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php
@ryuring 
以下のように修正しました！
レビューお願いします！
・デフォルトで公開状態のエントリーのみを取得する
・デフォルトで最新のエントリーから表示する
・エントリーリスト取得時にcrrentContentをセットする
> fix エントリーリスト取得条件のデフォルト値追加と、currentContentが取得できていない問題を解消
